INSERT INTO JPM_AUTHORITY(PROCESS_DEPLOY_ID, ROLE_ID, PERMISSION_DEPLOY_ID, CREATED_ID, CREATED_DATE)
SELECT /*newProcessDeployId*/ AS PROCESS_DEPLOY_ID, a.ROLE_ID, d1.ID as PERMISSION_DEPLOY_ID, /*userIdLogin*/ , /*sysDate*/
FROM JPM_AUTHORITY a 
    INNER JOIN JPM_PERMISSION_DEPLOY d2 ON a.PERMISSION_DEPLOY_ID = d2.ID
    LEFT JOIN JPM_PERMISSION_DEPLOY d1 ON d1.PERMISSION_ID = d2.PERMISSION_ID      
WHERE d1.PROCESS_DEPLOY_ID = /*newProcessDeployId*/ AND d2.PROCESS_DEPLOY_ID = /*oldProcessDeployId*/