SELECT 
	/*roleId*/10 			AS ROLE_ID
	, per.PERMISSION_NAME 	AS PERMISSION_NAME
	, per.ID 				AS PERMISSION_DEPLOY_ID
	, CASE WHEN aut.ROLE_ID IS NULL 
	THEN 0
	ELSE 1 END 				AS ACCESS_FLAG
FROM
	JPM_PERMISSION_DEPLOY per
LEFT JOIN 
	JPM_AUTHORITY aut 
ON 
	per.ID = aut.PERMISSION_DEPLOY_ID
	AND aut.ROLE_ID = /*roleId*/10
WHERE
	per.PROCESS_DEPLOY_ID = /*processDeployId*/41
ORDER BY
	per.ID