SELECT 
	   button.BUTTON_TEXT					AS BUTTON_TEXT
	, buttonLang.LANG_CODE        			AS LANG_CODE
	, buttonLang.BUTTON_NAME      			AS BUTTON_NAME
	, buttonLang.BUTTON_DEPLOY_ID 			AS BUTTON_DEPLOY_ID
	, buttonLang.BUTTON_NAME_IN_PASSIVE 	AS BUTTON_NAME_IN_PASSIVE
FROM
	JPM_BUTTON_DEPLOY button
LEFT JOIN
	JPM_BUTTON_LANG_DEPLOY buttonLang
ON
	button.ID = buttonLang.BUTTON_DEPLOY_ID
WHERE
	button.DELETED_ID = 0
	AND buttonLang.BUTTON_NAME IS NOT NULL
	AND button.ID = /*buttonDeployId*/