SET NOCOUNT ON;
	DROP TABLE IF EXISTS #ROLE_TMP_FOR_USER;

	SELECT 
		ACC.id
		, vw.USERNAME
		, VW.ROLE_ID
		, role.NAME
	INTO #ROLE_TMP_FOR_USER
	FROM VW_AUTHORITY_DETAIL vw
	INNER JOIN JCA_ACCOUNT acc
		ON ACC.USERNAME = vw.username
		and ACC.id = /*userId*/1
	inner join JCA_ROLE role
		ON role.ID = VW.ROLE_ID
	WHERE
		VW.ACTIVED = 1
		AND ROLE_ACTIVED = 1
	GROUP BY ACC.id, vw.USERNAME, VW.ROLE_ID, role.NAME;
WITH MAIN AS (
			SELECT 
				btn.ID											AS ID
				, btn.BUTTON_CODE								AS BUTTON_CODE
				, CASE WHEN btnLang.BUTTON_NAME IS NOT NULL
					THEN btnLang.BUTTON_NAME 
					ELSE btn.BUTTON_TEXT END					AS BUTTON_TEXT
				, btn.BUTTON_VALUE								AS BUTTON_VALUE
				, btn.BUTTON_CLASS								AS BUTTON_CLASS
				, btn.BUTTON_TYPE								AS BUTTON_TYPE
				, btnStep.OPTION_SAVE_FORM						AS SAVE_FORM
				, btnStep.OPTION_SAVE_EFORM						AS SAVE_EFORM
				, btnStep.PERMISSION_CODE						AS PERMISSION_CODE
				, btnStep.STEP_DEPLOY_ID						AS STEP_ID
				, btnStep.OPTION_AUTHENTICATE					AS AUTHENTICATE
				, btnStep.OPTION_SIGNED							AS SIGNED
				, btnStep.OPTION_EXPORT_PDF 					AS EXPORT_PDF
				, btn.DISPLAY_ORDER								AS ORDERS
				, btnStep.OPTION_SHOW_HISTORY 					AS DISPLAY_HISTORY
				, btnLang.BUTTON_NAME_IN_PASSIVE				AS BUTTON_NAME_PASSIVE
				, step.USE_CLAIM_BUTTON							AS USE_CLAIM_BUTTON	
			FROM JPM_BUTTON_FOR_STEP_DEPLOY btnStep
			LEFT JOIN JPM_BUTTON_DEPLOY btn
				ON btnStep.BUTTON_DEPLOY_ID = btn.ID
			LEFT JOIN JPM_STEP_DEPLOY step
				ON btnStep.STEP_DEPLOY_ID = step.Id
			LEFT JOIN JPM_BUTTON_LANG_DEPLOY btnLang
				ON btn.ID = btnLang.BUTTON_DEPLOY_ID
				AND btnLang.LANG_CODE = UPPER(/*lang*/'VI')
			INNER JOIN JPM_AUTHORITY authJpm
				ON authJpm.PERMISSION_DEPLOY_ID = btnStep.PERMISSION_DEPLOY_ID
			INNER JOIN #ROLE_TMP_FOR_USER roleAccount
				ON roleAccount.ROLE_ID = authJpm.ROLE_ID
			WHERE 
				btn.DELETED_ID = 0      
				/* IF null != processDeployId && processDeployId != '' */ 
 				AND btnStep.PROCESS_DEPLOY_ID = /*processDeployId*/73
				/* END */
				/* IF null != stepCode && stepCode != '' */ 
				AND btnStep.STEP_CODE = /*stepCode*/'taskSubmit'
				/* END */ 
)
SELECT * FROM MAIN
	GROUP BY ID, BUTTON_CODE, BUTTON_TEXT, BUTTON_VALUE, BUTTON_CLASS, BUTTON_TYPE, SAVE_FORM,
	SAVE_EFORM, PERMISSION_CODE, STEP_ID, AUTHENTICATE , SIGNED, EXPORT_PDF , ORDERS, DISPLAY_HISTORY, BUTTON_NAME_PASSIVE, USE_CLAIM_BUTTON		
	ORDER BY ORDERS, BUTTON_TEXT

SET NOCOUNT OFF;