SELECT
	buttonStep.STEP_DEPLOY_ID       AS STEP_DEPLOY_ID
	, buttonStep.BUTTON_DEPLOY_ID     AS BUTTON_DEPLOY_ID
	, buttonStep.PERMISSION_DEPLOY_ID AS PERMISSION_DEPLOY_ID
	, buttonStep.OPTION_SAVE_FORM 				AS OPTION_SAVE_FORM
	, buttonStep.OPTION_SAVE_EFORM 				AS OPTION_SAVE_EFORM
	, buttonStep.OPTION_AUTHENTICATE 	   		AS OPTION_AUTHENTICATE 
	, buttonStep.OPTION_SHOW_HISTORY 	   		AS OPTION_SHOW_HISTORY
	, buttonStep.OPTION_SIGNED    				AS OPTION_SIGNED 
	, buttonStep.OPTION_FILL_TO_EFORM    		AS OPTION_FILL_TO_EFORM 
	, buttonStep.OPTION_EXPORT_PDF		    	AS OPTION_EXPORT_PDF
FROM
	JPM_STEP_DEPLOY step
LEFT JOIN
	JPM_BUTTON_FOR_STEP_DEPLOY buttonStep
ON
	step.ID = buttonStep.STEP_DEPLOY_ID
WHERE
	step.DELETED_ID = 0
	AND buttonStep.BUTTON_DEPLOY_ID IS NOT NULL
	AND step.PROCESS_DEPLOY_ID = /*processDeployId*/