SELECT
	buttonStep.STEP_ID              AS STEP_ID
	, buttonStep.BUTTON_ID            AS BUTTON_ID
	, buttonStep.PERMISSION_ID        AS PERMISSION_ID
	, buttonStep.OPTION_SAVE_FORM 				AS OPTION_SAVE_FORM
	, buttonStep.OPTION_SAVE_EFORM 				AS OPTION_SAVE_EFORM
	, buttonStep.OPTION_AUTHENTICATE 	   		AS OPTION_AUTHENTICATE 
	, buttonStep.OPTION_SHOW_HISTORY 	   		AS OPTION_SHOW_HISTORY
	, buttonStep.OPTION_SIGNED    				AS OPTION_SIGNED 
	, buttonStep.OPTION_FILL_TO_EFORM    		AS OPTION_FILL_TO_EFORM 
	, buttonStep.OPTION_EXPORT_PDF		    	AS OPTION_EXPORT_PDF
FROM
	JPM_STEP step
LEFT JOIN
	JPM_BUTTON_FOR_STEP buttonStep
ON
	step.ID = buttonStep.STEP_ID
WHERE
	step.DELETED_ID = 0
	AND buttonStep.STEP_ID = /*stepId*/