SELECT
	buttonStep.PERMISSION_DEPLOY_ID AS PERMISSION_DEPLOY_ID
FROM
	JPM_BUTTON_FOR_STEP_DEPLOY buttonStep
WHERE
	buttonStep.STEP_DEPLOY_ID = /*stepId*/
	AND buttonStep.BUTTON_DEPLOY_ID = /*actionId*/