SELECT
   lang.ID AS LANG_ID,
   lang.CODE AS LANG_CODE,
   button.BUTTON_NAME AS BUTTON_NAME,
   button.BUTTON_NAME_IN_PASSIVE AS BUTTON_NAME_IN_PASSIVE,
   button.BUTTON_ID AS BUTTON_ID
FROM
   JPM_BUTTON_DEFAULT_LANG button
LEFT
JOIN JCA_LANGUAGE lang ON lang.CODE = button.LANG_CODE