SELECT
	button.ID               AS BUTTON_ID
	, button.PROCESS_ID     AS PROCESS_ID
	, button.BUTTON_CODE    AS BUTTON_CODE
	, button.BUTTON_TEXT    AS BUTTON_TEXT
	, button.BUTTON_VALUE   AS BUTTON_VALUE
	, button.BUTTON_CLASS   AS BUTTON_CLASS
	, button.BUTTON_TYPE    AS BUTTON_TYPE
	, button.DISPLAY_ORDER  AS DISPLAY_ORDER
FROM
	JPM_BUTTON button
WHERE
	button.DELETED_ID = 0
	AND button.PROCESS_ID = /*processId*/
ORDER BY
	button.DISPLAY_ORDER