SELECT
	button.ID               		AS BUTTON_DEPLOY_ID
	, button.PROCESS_DEPLOY_ID     	AS PROCESS_DEPLOY_ID
	, button.BUTTON_CODE    		AS BUTTON_CODE
	, button.BUTTON_TEXT    		AS BUTTON_TEXT
	, button.BUTTON_VALUE   		AS BUTTON_VALUE
	, button.BUTTON_CLASS   		AS BUTTON_CLASS
	, button.BUTTON_TYPE    		AS BUTTON_TYPE
	, button.DISPLAY_ORDER         	AS DISPLAY_ORDER
FROM
	JPM_BUTTON_DEPLOY button
WHERE
	button.DELETED_ID = 0
	AND button.PROCESS_DEPLOY_ID = /*processDeployId*/
	AND button.BUTTON_TEXT = /*buttonText*/
ORDER BY 
	button.DISPLAY_ORDER