SELECT 
	hitask_sla.JPM_TASK_ID 				AS JPM_TASK_ID
	,hitask.DOC_ID						AS DOC_ID
	,hitask.OWNER_ID					AS OWNER_ID
    ,hitask.OWNER_ORG_ID				AS OWNER_ORG_ID
	,hitask_sla.SLA_CONFIG_ID			AS SLA_CONFIG_ID
	,hitask_sla.PLAN_START_DATE			AS PLAN_START_DATE
	,hitask_sla.PLAN_DUE_DATE			AS PLAN_DUE_DATE
	,hitask_sla.PLAN_ESTIMATE_TIME		AS PLAN_ESTIMATE_TIME
	,hitask_sla.PLAN_CALANDAR_TYPE		AS PLAN_CALANDAR_TYPE
	,hitask_sla.PLAN_ESTIMATE_UNIT_TIME	AS PLAN_ESTIMATE_UNIT_TIME
	,hitask_sla.PLAN_TOTAL_TIME			AS PLAN_TOTAL_TIME
	,hitask_sla.ACTUAL_START_DATE		AS ACTUAL_START_DATE
	,hitask_sla.ACTUAL_END_DATE			AS ACTUAL_END_DATE
	,hitask_sla.ACTUAL_ELAPSE_TIME		AS ACTUAL_ELAPSE_TIME
FROM 
	JPM_HI_TASK_SLA hitask_sla
INNER JOIN 
	JPM_HI_TASK hitask
	ON hitask.ID = hitask_sla.JPM_TASK_ID
WHERE 
	hitask.DOC_ID = /*docId*/