SELECT
	permission.ID                  	 AS PERMISSION_DEPLOY_ID
	, permission.PROCESS_DEPLOY_ID   AS PROCESS_DEPLOY_ID
	, permission.PERMISSION_CODE     AS PERMISSION_CODE
	, permission.PERMISSION_NAME     AS PERMISSION_NAME
	, permission.PERMISSION_TYPE     AS PERMISSION_TYPE
FROM
	JPM_PERMISSION_DEPLOY permission
WHERE
	permission.PROCESS_DEPLOY_ID = /*processDeployId*/