SELECT 
	proLang.LANG_CODE        	AS LANG_CODE
	, proLang.PROCESS_NAME     	AS PROCESS_NAME
	, proLang.LANG_ID	     	AS LANG_ID
	, proLang.PROCESS_DEPLOY_ID 		AS PROCESS_DEPLOY_ID
FROM 
	JPM_PROCESS_DEPLOY_LANG proLang
WHERE
	proLang.PROCESS_DEPLOY_ID = /*processDeployId*/