SELECT
   lang.ID AS LANG_ID,
   lang.CODE AS LANG_CODE,
   status.STATUS_NAME AS STATUS_NAME,
   status.STATUS_ID AS STATUS_ID
FROM
   JPM_STATUS_DEFAULT_LANG status
LEFT
JOIN JCA_LANGUAGE lang ON lang.CODE = status.LANG_CODE