SELECT 
	statusLang.LANG_ID	  AS LANG_ID
	, statusLang.LANG_CODE     	  AS LANG_CODE
	, statusLang.STATUS_NAME      AS STATUS_NAME
	, statusLang.STATUS_DEPLOY_ID AS STATUS_DEPLOY_ID
FROM
	JPM_STATUS_DEPLOY status
LEFT JOIN
	JPM_STATUS_LANG_DEPLOY statusLang
ON
	status.ID = statusLang.STATUS_DEPLOY_ID
WHERE
	status.DELETED_ID = 0
	AND statusLang.STATUS_NAME IS NOT NULL
	AND status.ID = /*statusDeployId*/