SELECT 
	sla.ID							AS ID
	,jsla.JPM_SLA_INFO_ID			AS JPM_SLA_INFO_ID
	,jsla.ID 						AS JPM_SLA_CONFIG_ID
	,jsla.BUSINESS_ID				AS BUSINESS_ID
	,jsla.PROCESS_DEPLOY_ID			AS PROCESS_DEPLOY_ID
	,jsla.STEP_DEPLOY_ID			AS STEP_DEPLOY_ID
	,jsla.SLA_CALENDAR_TYPE_ID		AS SLA_CALENDAR_TYPE_ID
	,jsla.COMPANY_ID				AS COMPANY_ID
	,sla.SLA_DUE_TIME				AS SLA_DUE_TIME
	,sla.SLA_TIME_TYPE				AS SLA_TIME_TYPE
	,sla.ACTIVED					AS ACTIVED
FROM 
	JPM_SLA_CONFIG jsla
LEFT JOIN 
	SLA_CONFIG sla 
	ON jsla.SLA_CONFIG_ID = sla.ID AND sla.DELETED_ID = 0
WHERE jsla.DELETED_ID = 0
	AND jsla.PROCESS_DEPLOY_ID = /*processDeployId*/
	AND jsla.STEP_DEPLOY_ID = /*stepDeployId*/