SELECT
	status.ID                  AS STATUS_DEPLOY_ID
	, status.PROCESS_DEPLOY_ID AS PROCESS_DEPLOY_ID
	, status.STATUS_CODE       AS STATUS_CODE
	, status.STATUS_NAME       AS STATUS_NAME
FROM
	JPM_STATUS_DEPLOY status
WHERE
	status.DELETED_ID = 0
	AND status.PROCESS_DEPLOY_ID = /*processDeployId*/