SELECT 
	task_sla.JPM_TASK_ID 				AS JPM_TASK_ID
	,task_sla.DOC_ID					AS DOC_ID
	,task.DOC_ID						AS DOC_ID
	,task.OWNER_ID						AS OWNER_ID
    ,task.OWNER_ORG_ID					AS OWNER_ORG_ID
	,task_sla.SLA_CONFIG_ID				AS SLA_CONFIG_ID
	,task_sla.PLAN_START_DATE			AS PLAN_START_DATE
	,task_sla.PLAN_DUE_DATE				AS PLAN_DUE_DATE
	,task_sla.PLAN_ESTIMATE_TIME		AS PLAN_ESTIMATE_TIME
	,task_sla.PLAN_CALANDAR_TYPE		AS PLAN_CALANDAR_TYPE
	,task_sla.PLAN_ESTIMATE_UNIT_TIME	AS PLAN_ESTIMATE_UNIT_TIME
	,task_sla.PLAN_TOTAL_TIME			AS PLAN_TOTAL_TIME
	,task_sla.ACTUAL_START_DATE			AS ACTUAL_START_DATE
	,task_sla.ACTUAL_END_DATE			AS ACTUAL_END_DATE
	,task_sla.ACTUAL_ELAPSE_TIME		AS ACTUAL_ELAPSE_TIME
FROM 
	JPM_TASK_SLA task_sla
INNER JOIN 
	JPM_TASK task
	ON task.ID = task_sla.JPM_TASK_ID
WHERE 
	task.DOC_ID = /*docId*/