SELECT 1 as ID,
	GA_CODE,
	PERIOD,
	AGENT_CODE,
	MAX(OTP) AS OTP,
    MAX(CONFIRM_TIME) AS CONFIRM_TIME,
    MAX(REJECT_REASON) AS REJECT_REASON,
    MAX(REJECT_TIME) AS REJECT_TIME
FROM dbo.M_CONFIRM_PAYMENT
WHERE AGENT_CODE = /*agentCode*/
	AND PERIOD = /*period*/
	AND GA_CODE = /*gaCode*/
GROUP BY GA_CODE, PERIOD, AGENT_CODE