SELECT  
	cal.ID                  		AS ID
	, cal.CODE						AS ALERT_TYPE
	, cal.NAME						AS NAME
	, cal.ORG_ID					AS ORG_ID
	, cal.DESCRIPTION				AS DESCRIPTION
	, cal.START_MORNING_TIME		AS START_MORNING_TIME
	, cal.END_MORNING_TIME			AS END_MORNING_TIME
	, cal.START_AFTERNOON_TIME		AS START_AFTERNOON_TIME
	, cal.END_AFTERNOON_TIME		AS END_AFTERNOON_TIME
	, cal.WORKING_HOURS             AS WORKING_HOURS
FROM 
	SLA_CALENDAR_TYPE cal
WHERE
	cal.DELETED_ID = 0
	AND cal.ORG_ID = /*orgId*/