SELECT  
	cal.ID                  		AS ID
	, cal.CODE						AS CODE
	, cal.CODE						AS ALERT_TYPE
	, cal.NAME						AS NAME
	, cal.DESCRIPTION				AS DESCRIPTION
	, cal.ACTIVED					AS ACTIVED
	, cal.COMPANY_ID				AS COMPANY_ID
	, cal.WORKING_HOURS				AS WORKING_HOURS
	
FROM 
	SLA_CALENDAR_TYPE cal
WHERE
	cal.DELETED_ID = 0
	AND cal.ID = /*id*/