SELECT  ID                  			AS ID
		,SLA_CONFIG_ID					AS SLA_CONFIG_ID
		,SLA_TYPE						AS SLA_TYPE
		,USER_TO						AS USER_TO
		,USER_CC						AS USER_CC
		,USER_BCC						AS USER_BCC
		,NOTI_TITLE						AS NOTI_TITLE
		,NOTI_DESCRIPTION				AS NOTI_DESCRIPTION
		,EMAIL_CONTENT					AS EMAIL_CONTENT
		,EMAIL_SUBJECT					AS EMAIL_SUBJECT
FROM SLA_CONFIG_DETAIL
WHERE ID = /*id*/