SELECT  ID                 				AS ID
		,ORG_ID							AS ORG_ID
		,CALENDAR_TYPE_ID				AS CALENDAR_TYPE_ID
		,SLA_TYPE						AS SLA_TYPE
		,SLA_DUE_TIME					AS SLA_DUE_TIME
		,SLA_TIME_TYPE					AS SLA_TIME_TYPE
		,CALENDAR_OPTION				AS CALENDAR_OPTION
		,ACTIVE_FLAG					AS ACTIVE_FLAG
		,DISPLAY_ORDER					AS DISPLAY_ORDER
FROM SLA_CONFIG
WHERE DELETED_DATE IS NULL

/*IF orders != null*/
ORDER BY /*$orders*/ID
-- ELSE ORDER BY ID DESC
/*END*/

/*BEGIN*/
  /*IF offset != null*/
		OFFSET /*offset*/ ROWS FETCH NEXT  /*size*/ ROWS ONLY
  /*END*/
/*END*/