SELECT 
	doff.ID						AS ID
	, doff.DAYOFF				AS DAY_OFF
	, doff.CALENDAR_TYPE_ID		AS CALENDAR_TYPE_ID
	, doff.DAYOFF_TYPE			AS DAY_OFF_TYPE
	, doff.DESCRIPTION			AS DESCRIPTION	
	, doff.COMPANY_ID			AS COMPANY_ID
FROM 
	SLA_DAY_OFF doff
WHERE 
	doff.DELETED_ID = 0
	AND doff.ID = /*id*/