SELECT
	detail.USERNAME        AS USERNAME
	, detail.FUNCTION_CODE AS FUNCTION_CODE
	, detail.FUNCTION_NAME AS FUNCTION_NAME
	, detail.ACCESS_FLG    AS ACCESS_RIGHT
	, detail.ACCOUNT_ID    AS ACCOUNT_ID
FROM 
	VW_GET_USER_AUTHORITY detail
WHERE
	detail.COMPANY_ID = /*companyId*/1
	AND detail.FUNCTION_CODE IN /*functionCodeList*/()
	AND detail.ACCESS_FLG = '0'
ORDER BY 
	ACCOUNT_ID
	, FUNCTION_NAME