SELECT
	 ITEM.FUNCTION_NAME AS FUNCTION_NAME
	,ITEM.FUNCTION_CODE AS FUNCTION_CODE
	,ITEM.FUNCTION_TYPE AS FUNCTION_TYPE
	,AUTHORITY.ACCESS_FLG AS ACCESS_FLG
	,PS.STATUS_CODE AS STATUS_CODE
	,PS.PROCESS_ID AS PROCESS_ID
FROM
	JCA_AUTHORITY AUTHORITY
INNER JOIN JCA_ROLE ROLE ON AUTHORITY.ROLE_ID = ROLE.ID
INNER JOIN JCA_ITEM ITEM ON AUTHORITY.ITEM_ID = ITEM.ID
INNER JOIN JCA_ROLE_FOR_ORG RFO ON ROLE.ID = RFO.ROLE_ID
INNER JOIN JCA_ACCOUNT ACCOUNT ON RFO.ORG_ID = ACCOUNT.BRANCH_ID
LEFT JOIN JCA_M_STATUS_AUTHORITY SA ON (
	ITEM.FUNCTION_TYPE = '1' AND ITEM.BUSINESS_CODE IS NOT NULL 
	AND ROLE.ID = SA.ROLE_ID AND SA.ITEM_ID = ITEM.ID
)
LEFT JOIN JCA_T_PROCESS_STATUS PS ON (
	ITEM.FUNCTION_TYPE = '1' AND ITEM.BUSINESS_CODE IS NOT NULL
	AND PS.BUSSINES_CODE = ITEM.BUSINESS_CODE
	AND PS.ID = SA.PROCESS_STATUS_ID
)
WHERE
	ACCOUNT.ID = /*accountId*/
	AND
	ROLE.ACTIVE = '1'