SELECT DISTINCT
    CA.ID AS category_id
  ,CA.NAME AS category_name
FROM EFO_OZ_DOC doc
 LEFT JOIN EFO_FORM FR ON doc.FORM_ID = FR.ID

 LEFT JOIN EFO_CATEGORY CA ON CA.COMPANY_ID = FR.COMPANY_ID AND CA.DELETED_ID = 0 AND CA.ID = FR.CATEGORY_ID
 LEFT JOIN EFO_CATEGORY_LANGUAGE LANG ON CA.ID = LANG.CATEGORY_ID AND UPPER(LANG.LANGUAGE_CODE) = UPPER(/*languageCode*/'')
 LEFT JOIN jca_company CP ON CP.ID = FR.COMPANY_ID AND CP.DELETED_ID = 0 

 WHERE FR.DELETED_ID = 0

 	AND doc.DELETED_ID = 0

 	AND cp.DELETED_ID = 0

 	AND CA.DELETED_ID = 0

 	AND FR.ACTIVED = 1 
 	
	AND FR.COMPANY_ID = /*companyId*/

 ORDER BY CA.ID
