SELECT
    ITEM.ID AS category_id
    ,LANG.NAME AS NAME
FROM 
	EFO_CATEGORY ITEM
    LEFT JOIN EFO_CATEGORY_LANG LANG ON ITEM.ID = LANG.CATEGORY_ID AND UPPER(LANG.LANG_CODE) = UPPER(/*languageCode*/'')
LEFT JOIN jca_company CP ON ITEM.COMPANY_ID = CP.ID

WHERE ITEM.DELETED_ID = 0
	AND CP.ID = /*companyId*/
ORDER BY ITEM.DISPLAY_ORDER, LANG.NAME