SELECT distinct
    ITEM.ID AS category_id
  ,ITEM.NAME AS category_name
FROM EFO_FORM form
LEFT JOIN jca_company cp
ON form.COMPANY_ID = cp.ID
LEFT JOIN EFO_CATEGORY ITEM
ON
	form.CATEGORY_ID = ITEM.ID 
LEFT JOIN EFO_CATEGORY_LANG LANG ON ITEM.ID = LANG.CATEGORY_ID AND UPPER(LANG.LANG_CODE) = UPPER(/*languageCode*/'')
INNER JOIN VW_GET_AUTHORITY_ACCOUNT role
ON
	role.FUNCTION_CODE = form.FUNCTION_CODE
WHERE form.DELETED_ID = 0 
	AND form.COMPANY_ID = /*companyId*/
	AND
		role.ACCOUNT_ID = /*accountId*/
	AND
		ACCESS_FLG = 0
ORDER BY ITEM.ID