DELETE EFO_COMPONENT_AUTHORITY 
WHERE ID IN (SELECT CA.ID
			FROM EFO_COMPONENT_AUTHORITY CA
			LEFT JOIN EFO_COMPONENT CO ON CA.COMP_ID = CO.ID
			WHERE CA.ITEM_ID = /*itemId*/
				AND CO.FORM_ID = /*formId*/)