
SELECT
    CONTEST_ID,
    TERRITORY,
    AREA,
    REGION,
    OFFICE,
    POSITION,
    AGENT_NAME,
    AGENT_CODE,
    REPORTINGTO_CODE,
    REPORTINGTO_NAME,
    IS_PERSON
FROM M_CONTEST_APPLICABLE_DETAIL
WHERE CONTEST_ID = /*id*/'286'