
SELECT ID
	 , MEMO_NO
     , APPLICABLE_OBJECT
     , IS_ODS
	 , TERRITORY
	 , AREA
	 , REGION
	 , OFFICE
	 , POSITION
	 , REPORTINGTO_CODE
FROM M_CONTEST_SUMMARY
WHERE SAVE_DETAIL = '1'
AND DELETED_DATE IS NULL 
AND	CONVERT(DATE, CREATED_DATE) <= CONVERT(DATE, /*dateNow*/)