
SELECT ID
	 , EVENT_CODE
	 , EVENT_TITLE
	 , EVENT_DATE
     , APPLICABLE_OBJECT
     , TERRITORRY
     , AREA
     , REGION
     , OFFICE
     , POSITION
     , CONTENTS
     , LINK_NOTIFY
     , CREATE_DATE
     , CREATE_BY
FROM M_EVENTS
WHERE SAVE_DETAIL = '1'
  AND DEL_FLG = 0
  AND DELETE_DATE IS NULL
  AND	CONVERT(DATE, CREATE_DATE) <= CONVERT(DATE, /*date*/)