SELECT DISTINCT
	FR.COMPANY_ID 			AS company_id
	,CP.NAME 				AS company_name
	,CP.SYSTEM_CODE
	,CP.SYSTEM_NAME
	,CP.LOGO_MINI_REPO_ID	AS logo_repo_id
	,CP.LOGO_MINI			AS	logo_path
  	,FR.CATEGORY_ID			AS category_id
FROM EFO_OZ_DOC doc
LEFT JOIN EFO_FORM FR ON doc.FORM_ID = FR.ID
LEFT JOIN EFO_CATEGORY CA ON CA.COMPANY_ID = FR.COMPANY_ID AND CA.DELETED_ID = 0 AND CA.ID = FR.CATEGORY_ID
LEFT JOIN EFO_CATEGORY_LANGUAGE LANG ON CA.ID = LANG.CATEGORY_ID AND UPPER(LANG.LANGUAGE_CODE) = UPPER(/*languageCode*/'')
LEFT JOIN jca_company CP ON CP.ID = FR.COMPANY_ID AND CP.DELETED_ID = 0
INNER JOIN 
(	SELECT DISTINCT 
		FUNCTION_CODE 
	FROM 
		VW_GET_AUTHORITY_ACCOUNT 
	WHERE 
		ACCOUNT_ID =  /*accountId*/
		AND access_flg = 0
) AU 
ON 
	AU.FUNCTION_CODE = FR.FUNCTION_CODE
WHERE FR.DELETED_ID = 0
	AND FR.ACTIVED = 1
	/*IF companyIdList != null*/
	AND FR.COMPANY_ID IN /*companyIdList*/()
	/*END*/
	/*IF keySearch != null*/
	AND	(
			UPPER(CA.NAME) LIKE CONCAT('%',CONCAT(UPPER(/*keySearch*/''),'%'))
			OR UPPER(FR.SUMMARY) LIKE CONCAT('%',CONCAT(UPPER(/*keySearch*/''),'%'))
		)
	/*END*/
ORDER BY FR.COMPANY_ID ,FR.CATEGORY_ID 
/*IF pageSize!=null*/
		OFFSET /*page*/ ROWS FETCH NEXT  /*pageSize*/ ROWS ONLY
/*END*/