SELECT
	FR.*, 
	LANG.CATEGORY_NAME CATEGORY_NAME
FROM EFO_FORM FR
LEFT JOIN EFO_CATEGORY CA ON CA.COMPANY_ID = FR.COMPANY_ID AND CA.DELETED_ID = 0 AND CA.ID = FR.CATEGORY_ID
LEFT JOIN EFO_CATEGORY_LANGUAGE LANG ON CA.ID = LANG.CATEGORY_ID AND UPPER(LANG.LANGUAGE_CODE) = UPPER(/*languageCode*/'')
WHERE FR.DELETED_ID = 0
AND FR.ACTIVED = 1
/*IF companyId != null*/
	AND FR.COMPANY_ID = /*companyId*/1
/*END*/ 
/*IF categoryId != null*/
	AND FR.CATEGORY_ID = /*categoryId*/1
/*END*/
ORDER BY FR.DISPLAY_ORDER, FR.NAME