SELECT
	CASE WHEN MAX(DISPLAY_ORDER) IS NULL THEN 0 ELSE MAX(DISPLAY_ORDER) END AS DISPLAY_ORDER
FROM 
	EFO_FORM
WHERE DELETED_ID = 0
/*IF companyId != null*/
	AND COMPANY_ID = /*companyId*/1
/*END*/ 