SELECT COUNT(*)
FROM(SELECT DISTINCT
	FR.COMPANY_ID AS company_id
	,CP.NAME 			AS company_name
	,CP.SYSTEM_CODE
	,CP.SYSTEM_NAME
	,CP.LOGIN_LOGO_REPO_ID
	,CP.LOGIN_LOGO

	,CP.LOGIN_LOGO
  	,FR.ID
  	,FR.CATEGORY_ID
FROM EFO_OZ_DOC doc
LEFT JOIN EFO_FORM FR ON doc.FORM_ID = FR.ID
LEFT JOIN EFO_CATEGORY CA ON CA.COMPANY_ID = FR.COMPANY_ID AND CA.DELETED_ID = 0 AND CA.ID = FR.CATEGORY_ID
LEFT JOIN jca_company CP ON CP.ID = FR.COMPANY_ID AND CP.DELETED_ID = 0 
WHERE FR.DELETED_ID = 0
	AND doc.DELETED_ID = 0
	AND cp.DELETED_ID = 0
	AND CA.DELETED_ID = 0
	AND FR.ACTIVED = 1
	/*IF companyIdList != null*/
	AND FR.COMPANY_ID IN /*companyIdList*/()
	/*END*/
	)