SELECT
	FR.ID				AS ID,
    CASE WHEN formLang.FORM_NAME IS NULL THEN FR.NAME ELSE formLang.FORM_NAME END AS NAME,
    CASE WHEN formLang.FORM_NAME IS NULL THEN FR.NAME ELSE formLang.FORM_NAME END AS TEXT
FROM EFO_FORM FR
LEFT JOIN EFO_CATEGORY CA ON CA.COMPANY_ID = FR.COMPANY_ID AND CA.DELETED_ID = 0 AND CA.ID = FR.CATEGORY_ID
LEFT JOIN EFO_CATEGORY_LANGUAGE LANG ON CA.ID = LANG.CATEGORY_ID AND UPPER(LANG.LANGUAGE_CODE) = UPPER(/*languageCode*/'')
LEFT JOIN EFO_FORM_LANG formLang ON FR.ID = formLang.FORM_ID AND UPPER(formLang.LANG_CODE) = UPPER(/*languageCode*/'')
LEFT JOIN 
	JPM_BUSINESS business
ON
	business.ID = FR.JPM_BUSINESS_ID
WHERE 
	FR.DELETED_ID = 0
	AND FR.ACTIVED = 1
	/*IF companyId != null*/
	AND FR.COMPANY_ID = /*companyId*/0
	/*END*/ 
	/*IF categoryId != null*/
	AND CA.ID = /*categoryId*/0
	/*END*/ 
	
	/*IF processTypeIgnores != null*/
	AND business.PROCESS_TYPE NOT IN /*processTypeIgnores*/()
	/*END*/ 
	/*IF keySearch !=null && keySearch !=''*/
	AND (FN_CONVERT_TO_VN_ONLY_UPPER(UPPER(FR.NAME)) LIKE CONCAT(CONCAT('%', FN_CONVERT_TO_VN_ONLY_UPPER(UPPER(/*keySearch*/''))), '%')
		OR FN_CONVERT_TO_VN_ONLY_UPPER(UPPER(formLang.FORM_NAME)) LIKE CONCAT(CONCAT('%', FN_CONVERT_TO_VN_ONLY_UPPER(UPPER(/*keySearch*/''))), '%')
	)
	/*END*/
ORDER BY FR.ID, FR.NAME 
/*IF isPaging*/
OFFSET 0 ROWS FETCH NEXT 30 ROWS ONLY
/*END*/
