SELECT
	FR.ID				AS ID
    , CASE WHEN formLang.FORM_NAME IS NULL THEN FR.NAME ELSE formLang.FORM_NAME END AS NAME
	,FR.CATEGORY_ID		AS CATEGORY_ID
	,LANG.CATEGORY_NAME	AS CATEGORY_NAME
	,FR.BUSINESS_CODE	AS BUSINESS_CODE
	,FR.FUNCTION_CODE	AS FUNCTION_CODE
	,FR.COMPANY_ID		AS COMPANY_ID
	,FR.DESCRIPTION		AS DESCRIPTION
	,FR.FILE_NAME		AS FILE_NAME
	,FR.IMAGE			AS IMAGE
	,FR.REPOSITORY_ID	AS REPOSITORY_ID
	,FR.DISPLAY_ORDER	AS DISPLAY_ORDER
	,FR.DEVICE_TYPE		AS DEVICE_TYPE
	,FR.ACTIVED		AS ACTIVED
	,FR.CREATED_ID		AS CREATED_ID
	,FR.CREATED_DATE	AS CREATED_DATE
	,FR.UPDATED_ID		AS UPDATED_ID
	,FR.UPDATED_DATE	AS UPDATED_DATE
	,FR.DELETED_ID		AS DELETED_ID
	,FR.DELETED_DATE	AS DELETED_DATE
	,FR.JPM_BUSINESS_ID	AS BUSINESS_ID
	,business.NAME		AS BUSINESS_NAME
	,CA.DISPLAY_ORDER 	AS CATEGORY_ORDER
	,FR.FORM_TYPE		AS FORM_TYPE
	,business.PROCESS_TYPE AS PROCESS_TYPE
FROM EFO_FORM FR
LEFT JOIN EFO_CATEGORY CA ON CA.COMPANY_ID = FR.COMPANY_ID AND CA.DELETED_ID = 0 AND CA.ID = FR.CATEGORY_ID
LEFT JOIN EFO_CATEGORY_LANGUAGE LANG ON CA.ID = LANG.CATEGORY_ID AND UPPER(LANG.LANGUAGE_CODE) = UPPER(/*languageCode*/'')
LEFT JOIN EFO_FORM_LANG formLang ON FR.ID = formLang.FORM_ID AND UPPER(formLang.LANG_CODE) = UPPER(/*languageCode*/'')
LEFT JOIN 
	JPM_BUSINESS business
ON
	business.ID = FR.JPM_BUSINESS_ID
WHERE FR.DELETED_ID = 0
AND FR.ACTIVED = 1
/*IF companyList != null*/
AND FR.COMPANY_ID IN /*companyList*/()
/*END*/ 
/*IF formId != null*/
AND FR.ID = /*formId*/0
/*END*/
/*IF processTypeIgnores != NULL && processTypeIgnores.size()>0*/
AND business.PROCESS_TYPE NOT IN /*processTypeIgnores*/()
/*END*/
ORDER BY FORM_TYPE DESC, DISPLAY_ORDER, NAME
