SELECT AGENT_CODE
FROM M_NOTIFYS_APPLICABLE_DETAIL 
where  1=1
AND CHARINDEX(CONCAT(';',AGENT_CODE), /*stringData*/';135482;144834;149651;') > 0
AND FORMAT(GETDATE(),'dd/MM/yyyy') = FORMAT(CREATE_DATE,'dd/MM/yyyy')
AND NOTIFY_ID = /*notifyId*/


