
SELECT ID
     , APPLICABLE_OBJECT
     , TERRITORRY
     , AREA
     , REGION
     , OFFICE
     , POSITION
     , NOTIFY_CODE
     , NOTIFY_TITLE
     , CONTENTS
     , LINK_NOTIFY
     , IS_SEND_IMMEDIATELY
     , CREATE_DATE
     , CREATE_BY
	 , SEND_DATE
FROM M_NOTIFYS
WHERE SAVE_DETAIL = '1'
  AND DELETE_DATE IS NULL
  AND	CONVERT(DATE, CREATE_DATE) <= CONVERT(DATE, /*date*/)