SELECT
	ITEM.ID
	,ITEM.COMPANY_ID
	,co.NAME 		  AS company_name
	,ITEM.CATEGORY_ID
	,JP.BUSINESS_CODE BUSINESS_CODE
	--,ITEM.FUNCTION_CODE
	,ITEM.NAME
	,ITEM.DESCRIPTION
	,ITEM.OZ_FILE_PATH
	,ITEM.ICON_FILE_PATH
	,ITEM.DISPLAY_ORDER
	,ITEM.DEVICE_TYPE
	,ITEM.ACTIVED
	,ITEM.CREATED_ID
	,ITEM.CREATED_DATE
	,ITEM.UPDATED_ID
	,ITEM.UPDATED_DATE
	,ITEM.DELETED_ID
	,ITEM.DELETED_DATE
	,ITEM.OZ_FILE_PATH FORM_FILE_NAME
	,LANG.NAME CATEGORY_NAME
	--,FC.FUNCTION_NAME
	,JP.BUSINESS_NAME BUSINESS_NAME
	,ITEM.FORM_TYPE
	,CON.NAME AS FORM_TYPE_NAME
FROM EFO_FORM ITEM
LEFT JOIN EFO_CATEGORY CA ON CA.ID = ITEM.CATEGORY_ID AND CA.DELETED_ID = 0 AND CA.COMPANY_ID = ITEM.COMPANY_ID
LEFT JOIN EFO_CATEGORY_LANG LANG ON CA.ID = LANG.CATEGORY_ID AND LANG.LANG_CODE = UPPER(/*languageCode*/'EN')
LEFT JOIN JPM_BUSINESS JP ON JP.ID = ITEM.BUSINESS_ID
LEFT JOIN JCA_COMPANY co ON ITEM.COMPANY_ID = co.ID and co.DELETED_ID = 0
LEFT JOIN (
	SELECT DL.KIND ,DL.CODE, DL.NAME
	FROM JCA_CONSTANT DL
	WHERE DL.KIND = 'BUSINESS_FORM_TYPE'
		AND DL.LANG_CODE = UPPER(/*languageCode*/'EN')
) CON ON CASE WHEN ITEM.FORM_TYPE IS NULL THEN '1' ELSE ITEM.FORM_TYPE END = CON.CODE 
WHERE ITEM.DELETED_ID = 0
/*IF search.companyId != null && search.companyId != 0*/
	AND ITEM.COMPANY_ID = /*search.companyId*/1
/*END*/ 
/*BEGIN*/
	AND (
		/*IF search.name != null && search.name != ''*/
			OR UPPER(ITEM.NAME) LIKE UPPER(concat(concat('%',  /*search.name*/''), '%'))
		/*END*/
		/*IF search.description != null && search.description != ''*/
			OR UPPER(ITEM.DESCRIPTION) LIKE UPPER(concat(concat('%',  /*search.description*/''), '%'))
		/*END*/
		/*IF search.fileName != null && search.fileName != ''*/
			OR UPPER(ITEM.OZ_FILE_PATH) LIKE UPPER(concat(concat('%',  /*search.fileName*/''), '%'))
		/*END*/
	)
/*END*/
/*IF search.formType != null && search.formType != ''*/
	AND CASE WHEN ITEM.FORM_TYPE IS NULL THEN '1' ELSE ITEM.FORM_TYPE END = /*search.formType*/
/*END*/
/*IF search.categoryId != null*/
	AND ITEM.CATEGORY_ID = /*search.categoryId*/0
/*END*/
ORDER BY ITEM.DISPLAY_ORDER, ITEM.NAME
OFFSET /*offset*/ ROWS FETCH NEXT  /*sizeOfPage*/ ROWS ONLY