SELECT
	FR.ID AS FORM_ID,
	FR.COMPANY_ID AS COMPANY_ID,
	FR.NAME  AS FORM_NAME,
	FR.FORM_TYPE AS FORM_TYPE,
	FR.DISPLAY_ORDER AS DISPLAY_ORDER,
	FR.ACTIVED AS ACTIVED,
	FR.DEVICE_TYPE AS DEVICE_TYPE,
	FR.DESCRIPTION AS DESCRIPTION,
	FR.OZ_FILE_PATH AS OZ_FILE_PATH,
	FR.ICON_REPO_ID AS ICON_REPO_ID,
	FR.ICON_FILE_PATH AS ICON_FILE_PATH,
	LANG.CATEGORY_ID AS CATEGORY_ID,
	LANG.NAME AS CATEGORY_NAME,
	BU.BUSINESS_NAME AS BUSINESS_NAME,
	BU.ID AS BUSINESS_ID,
	--IT.FUNCTION_NAME,
	CON.NAME AS FORM_TYPE_NAME
FROM EFO_FORM FR
LEFT JOIN EFO_CATEGORY CA ON CA.ID = FR.COMPANY_ID AND CA.ID = FR.CATEGORY_ID AND CA.DELETED_ID = 0
LEFT JOIN EFO_CATEGORY_LANG LANG ON LANG.CATEGORY_ID=FR.CATEGORY_ID AND LANG.LANG_CODE = UPPER(/*languageCode*/'EN')
LEFT JOIN JPM_BUSINESS BU ON BU.ID = FR.BUSINESS_ID
LEFT JOIN (
	SELECT DL.KIND ,DL.CODE, DL.NAME
	FROM JCA_CONSTANT DL
	WHERE DL.KIND = 'BUSINESS_FORM_TYPE'
		AND DL.LANG_CODE = UPPER(/*languageCode*/'EN')
) CON ON CASE WHEN FR.FORM_TYPE IS NULL THEN '1' ELSE FR.FORM_TYPE END = CON.CODE 
WHERE FR.DELETED_ID = 0
AND FR.ID = /*id*/0