SELECT
	FR.*,
	LANG.NAME NAME,
	IT.FUNCTION_NAME
FROM EFO_FORM FR
LEFT JOIN EFO_CATEGORY CA ON CA.COMPANY_ID = FR.COMPANY_ID AND CA.ID = FR.CATEGORY_ID AND CA.DELETED_ID IS NULL
LEFT JOIN EFO_CATEGORY_LANG LANG ON CA.ID = LANG.CATEGORY_ID AND LANG.LANG_CODE = UPPER(/*languageCode*/'EN')
LEFT JOIN JCA_ITEM IT ON IT.DELETED_ID IS NULL
WHERE FR.DELETED_ID IS NULL
AND FR.ID = 1;