INSERT INTO JCA_SYSTEM_SETTING(SETTING_KEY, SETTING_VALUE, COMPANY_ID, CREATED_ID, CREATED_DATE)
SELECT source_table.SETTING_KEY, source_table.SETTING_VALUE, /*companyId*/1 COMPANY_ID, source_table.CREATED_ID, source_table.CREATED_DATE 
FROM JCA_SYSTEM_SETTING source_table
LEFT JOIN JCA_SYSTEM_SETTING target_table ON target_table.SETTING_KEY = source_table.SETTING_KEY 
AND target_table.COMPANY_ID = /*companyId*/1 
WHERE source_table.COMPANY_ID IS NULL 
