SELECT tp.*
	,CASE WHEN tp.LANGUAGE_CODE IS NULL THEN tp.PARAMETER_NAME ELSE CONCAT(tp.PARAMETER_NAME, CONCAT('_', tp.LANGUAGE_CODE)) END AS PARAMETER_FULL_NAME
FROM JCA_EMAIL_TEMPLATE_PARAMETER tp
WHERE DELETED_ID = 0
AND (tp.LANGUAGE_CODE IN (SELECT CODE FROM JCA_LANGUAGE)
	OR tp.LANGUAGE_CODE IS NULL)
/*IF companyId != null */
	AND (tp.COMPANY_ID = /*companyId*/ OR tp.COMPANY_ID IS NULL)
/*END*/
ORDER BY PARAMETER_FULL_NAME