/*
 * Created on 2019-01-15 ( Date ISO 2019-01-15 - Time 10:30:06 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package vn.com.unit.cms.admin.all.enumdef;
public enum ExportProductConsultExportEnum {

    //----------------------------------------------------------------------
    //  DATA FIELDS 
    //----------------------------------------------------------------------    
	STT("0"),
	FULLNAME("1"),
	PRODUCTNAME("2"),
	PHONENUMBER("3"),
	ADDRESS("4"),
	DISTRICT("5"),
	PROVINCE("6"),
	CREATEDATE("7"),
	CREATETIME("8"),
	COMMENTNAME("9"),
	PROCESSINGSTATUS("10"),
	PROCESSUSER("11"),
	UPDATEDATE("12");
	    
    private String value;
    
    private ExportProductConsultExportEnum(String value){
        this.value = value;
    }
    
    public String toString (){
        return value;
    }
}
