/*
 * Created on 2019-01-18 ( Date ISO 2019-01-18 - Time 16:13:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package vn.com.unit.cms.admin.all.enumdef;
public enum ExportInvestorExportEnum {

    //----------------------------------------------------------------------
    //  DATA FIELDS 
    //----------------------------------------------------------------------    

	STT("0"),
	INVESTORCATEGORYNAMELEVEL1("1"),
	INVESTORCATEGORYNAMELEVEL2("2"),
	INVESTORCATEGORYNAMELEVEL3("3"),
	INVESTORCATEGORYNAMELEVEL4("4"),
	KINDNAMEATTR("5"),
	CODE("6"),
	TITLE("7"),
	STATUSNAME("8"),
	ENABLED("9"),
	CREATEBY("10"),
	CREATEDATE("11");
	    
    private String value;
    
    private ExportInvestorExportEnum(String value){
        this.value = value;
    }
    
    public String toString (){
        return value;
    }
}
