/*
 * Created on 2019-01-18 ( Date ISO 2019-01-18 - Time 14:05:10 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package vn.com.unit.cms.admin.all.enumdef;
public enum ExportProductCategorySubExportEnum {

    //----------------------------------------------------------------------
    //  DATA FIELDS 
    //----------------------------------------------------------------------    

	STT("0"),
	CATEGORYTITLE("1"),
	CODE("2"),
	TITLE("3"),
	STATUSNAME("4"),
	ENABLED("5"),
	PRIORITY("6"),
	CREATEBY("7"),
	CREATEDATE("8");
	    
    private String value;
    
    private ExportProductCategorySubExportEnum(String value){
        this.value = value;
    }
    
    public String toString (){
        return value;
    }
}
