/*
 * Created on 2019-03-05 ( Date ISO 2019-03-05 - Time 16:34:51 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package vn.com.unit.cms.admin.all.enumdef;
public enum ExportNewsTypeExportEnum {

    //----------------------------------------------------------------------
    //  DATA FIELDS 
    //----------------------------------------------------------------------    
    STT("0"),
	CODE("1"),
	LABEL("2"),
	TYPEOFLIBRARY("3"),
	TYPEOFNEW("4"),
	ENABLED("5"),
	STATUSNAME("6"),
	CREATEBY("7"),
	CREATEDATE("8");
	    
    private String value;
    
    private ExportNewsTypeExportEnum(String value){
        this.value = value;
    }
    
    public String toString (){
        return value;
    }
}
