/*
 * Created on 2019-01-18 ( Date ISO 2019-01-18 - Time 16:13:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package vn.com.unit.cms.admin.all.enumdef;
public enum ExportProductExportEnum {

    //----------------------------------------------------------------------
    //  DATA FIELDS 
    //----------------------------------------------------------------------    

	STT("0"),
	CATEGORYNAME("1"),
	CATEGORYSUBNAME("2"),
	CODE("3"),
	TITLE("4"),
	MICROSITE("5"),
	ENABLED("6"),
	HIGHLIGHTS("7"),
	HIGHLIGHTSMATHEXPRESS("8"),
	PRIORITY("9"),
	SHOWFORM("10"),
	STATUSNAME("11"),
	CREATEBY("12"),
	CREATEDATE("13");
	    
    private String value;
    
    private ExportProductExportEnum(String value){
        this.value = value;
    }
    
    public String toString (){
        return value;
    }
}
