/*
 * Created on 2019-01-18 ( Date ISO 2019-01-18 - Time 10:52:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package vn.com.unit.cms.admin.all.enumdef;
public enum ExportIntroductionCategoryExportEnum {

    //----------------------------------------------------------------------
    //  DATA FIELDS 
    //----------------------------------------------------------------------    

	STT("0"),
	CODE("1"),
	TITLE("2"),
	PICTUREINTRODUCTION("3"),
	TYPEOFMAIN("4"),
	ENABLED("5"),
	STATUSNAME("6"),
	CREATEBY("7"),
	CREATEDATE("8");
	    
    private String value;
    
    private ExportIntroductionCategoryExportEnum(String value){
        this.value = value;
    }
    
    public String toString (){
        return value;
    }
}
