/*
 * Created on 2019-01-18 ( Date ISO 2019-01-18 - Time 16:13:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package vn.com.unit.cms.admin.all.enumdef;
public enum ExportIntroductionExportEnum {

    //----------------------------------------------------------------------
    //  DATA FIELDS 
    //----------------------------------------------------------------------    

	STT("0"),
	CATEGORYNAME("1"),
	CODE("2"),
	TITLE("3"),
	ENABLED("4"),
	STATUSNAME("5"),
	CREATEBY("6"),
	CREATEDATE("7");
	    
    private String value;
    
    private ExportIntroductionExportEnum(String value){
        this.value = value;
    }
    
    public String toString (){
        return value;
    }
}
