/*
 * Created on 2019-01-18 ( Date ISO 2019-01-18 - Time 10:52:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package vn.com.unit.cms.admin.all.enumdef;
public enum ExportProductCategoryExportEnum {

    //----------------------------------------------------------------------
    //  DATA FIELDS 
    //----------------------------------------------------------------------    

	STT("0"),
	CODE("1"),
	TITLE("2"),
	STATUSNAME("3"),
	ENABLED("4"),
	CREATEBY("5"),
	CREATEDATE("6");
	    
    private String value;
    
    private ExportProductCategoryExportEnum(String value){
        this.value = value;
    }
    
    public String toString (){
        return value;
    }
}
