INSERT INTO SLA_ALERT_HISTORY (REFERENCE_ID,STEP_ID,SLA_SETTING_ID,ALERT_DATE,TYPE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE,DELETED_BY,DELETED_DATE,DEADLINE,SUBMIT_DATE,REFERENCE,LINK,SUMMARY,STATUS,SUBMIT_BY,SEND_MAIL_TYPE,EMAIL_TEMPLATE_ID,EMAIL_TO,EMAIL_CC,TASK_ID,SUBMIT_BY_ID,COMPANY_ID,COUNT_SENDING_ERROR)
SELECT REFERENCE_ID,STEP_ID,SLA_SETTING_ID,ALERT_DATE,TYPE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE,DELETED_BY,DELETED_DATE,DEADLINE,SUBMIT_DATE,REFERENCE,LINK,SUMMARY,STATUS,SUBMIT_BY,SEND_MAIL_TYPE,EMAIL_TEMPLATE_ID,EMAIL_TO,EMAIL_CC,TASK_ID,SUBMIT_BY_ID,COMPANY_ID,COUNT_SENDING_ERROR FROM  SLA_ALERT alert 
WHERE  
	/*IF slaAlerts != null*/
	alert.ID IN /*slaAlerts*/()
	/*END*/