select
	VH.VIETNAMESEHOLIDAYDATE VIETNAMESE_HOLIDAY_DATE,
    VH.DESCRIPTION,
    VH.CREATED_BY CREATED_BY,
    VH.CREATED_DATE CREATE_DATE, 
	VH.UPDATED_BY UPDATED_BY,
    VH.UPDATED_DATE UPDATED_DATE
FROM
	SLA_DAY_OFF VH
WHERE 
	1=1 
	/*IF companyId != null*/
	AND VH.COMPANY_ID = /*companyId*/1
	/*END*/ 
	/*IF companyId == null*/
	AND VH.COMPANY_ID IS NULL
	/*END*/ 
	/*IF calendarType != null*/
	AND VH.CALENDAR_TYPE_ID = /*calendarType*/19
	/*END*/
	AND VH.VIETNAMESEHOLIDAYDATE between /*startDate*/SYSDATE AND /*endDate*/SYSDATE 
	ORDER BY VH.VIETNAMESEHOLIDAYDATE ASC;
	