SELECT 
a.AGENT_CODE 							AS agent_code
, a.agent_name 							AS agent_name
, STG_DMS.DMS_AGENT_TYPE.DESCRIPTION 	AS position_name
FROM STG_DMS.DMS_AGENT_DETAIL a
JOIN STG_DMS.DMS_AGENT_TYPE
ON a.AGENT_TYPE = STG_DMS.DMS_AGENT_TYPE.AGENT_TYPE
where STG_DMS.DMS_AGENT_TYPE.CHANNEL = 'AG'
AND a.AGENT_CODE=/*agentCode*/