
SELECT
	a.ID AS ACTIVITY_ID
	, a.PARTNER AS PARTNER
	, l.ID AS ORG_LOCATION_ID
	, l.ZONE AS ZONE
	, l.AREA AS AREA
	, l.REGIONAL AS REGIONAL
	, l.BU AS BU
	, l.BU_CODE AS BU_CODE
	, c.CATEGORY AS CATEGORY
	, a.SUBJECT AS SUBJECT
	, a.CONTENT AS CONTENT
	, a.TYPE AS TYPE
	, a.FORM AS FORM
	, a.ACT_CODE AS ACT_CODE
	, p1.ID AS PLAN_ID
	, FORMAT(p1.PLAN_DATE, 'dd/MM/yyyy') AS PLAN_DATE
	, p1.PERSON_NUMBER AS PERSON_NUMBER_PLAN
	, p1.COST_AMT AS COST_AMT_PLAN
	, p1.SALES_AMT AS SALES_AMT_PLAN
	, FORMAT(p2.ACTUAL_DATE, 'dd/MM/yyyy') AS ACTUAL_DATE
	, p2.PERSON_NUMBER AS PERSON_NUMBER_ACTUAL
	, p2.COST_AMT AS COST_AMT_ACTUAL
	, p2.SALES_AMT AS SALES_AMT_ACTUAL
	, a.PARTICIPANTS AS PARTICIPANTS
	, a.STATUS_ID AS STATUS_ID
	, s.STATUS AS STATUS
	, FORMAT(a.APPROVED_DATE, 'dd/MM/yyyy') AS APPROVED_DATE
	, FORMAT(a.REPORTED_DATE, 'dd/MM/yyyy') AS REPORTED_DATE
	, ROW_NUMBER() OVER (ORDER BY a.ID DESC) AS NO
FROM SAM_ACTIVITY a
	INNER JOIN SAM_ORGANIZATION_LOCATION l ON a.ID = l.ACTIVITY_ID
	INNER JOIN SAM_M_CATEGORY c ON a.CATEGORY_ID = c.ID AND c.IS_DELETED = 0
	INNER JOIN SAM_M_ACTIVITY_STATUS s ON s.ID = a.STATUS_ID AND s.IS_DELETED = 0
	LEFT JOIN (SELECT ID, PLAN_DATE, PERSON_NUMBER, COST_AMT, SALES_AMT, ACTIVITY_ID FROM SAM_PLAN p WHERE p.PLAN_DATE IS NOT NULL AND p.ACTUAL_DATE IS NULL) AS p1 ON p1.ACTIVITY_ID = a.ID
	LEFT JOIN (SELECT  ID, ACTUAL_DATE, PERSON_NUMBER, COST_AMT, SALES_AMT, ACTIVITY_ID FROM SAM_PLAN p WHERE p.PLAN_DATE IS NULL AND p.ACTUAL_DATE IS NOT NULL) AS p2 ON p2.ACTIVITY_ID = a.ID
WHERE 1 = 1
	AND p1.PLAN_DATE BETWEEN /*fromDate*/'2023-10-20 10:37:17.693' AND /*toDate*/'2023-11-10 10:10:10.000'
