
SELECT
	a.ID AS ACTIVITY_ID
	, a.PARTNER AS PARTNER
	, l.ID AS ORG_LOCATION_ID
	, l.ZONE_CODE
	, l.ZONE AS ZONE
	, l.AREA AS AREA
	, l.REGIONAL AS REGIONAL
	, l.BU AS BU
	, l.BU_CODE AS BU_CODE
	, l.BU_COUNT AS BU_COUNT
	, c.NAME AS CATEGORY
	, a.CATEGORY_ID AS CATEGORY_ID
	, a.SUBJECT AS SUBJECT
	, a.CONTENT AS CONTENT
	, a.TYPE AS TYPE
	, a.FORM AS FORM
	, a.ACT_CODE AS ACT_CODE
	, p1.ID AS PLAN_ID
	, FORMAT(p1.PLAN_DATE, 'dd/MM/yyyy') AS PLAN_DATE
	, p1.PERSON_NUMBER AS PERSON_NUMBER_PLAN
	, p1.COST_AMT AS COST_AMT_PLAN
	, p1.SALES_AMT AS SALES_AMT_PLAN
	, FORMAT(p2.ACTUAL_DATE, 'dd/MM/yyyy') AS ACTUAL_DATE
	, p2.PERSON_NUMBER AS PERSON_NUMBER_ACTUAL
	, p2.COST_AMT AS COST_AMT_ACTUAL
	, p2.SALES_AMT AS SALES_AMT_ACTUAL
	, a.PARTICIPANTS AS PARTICIPANTS
	, a.STATUS_ID AS STATUS_ID
	, s.STATUS AS STATUS
	, FORMAT(a.APPROVED_DATE, 'dd/MM/yyyy') AS APPROVED_DATE
	, FORMAT(case a.STATUS_ID when 6 then a.CANCEL_DATE else a.REPORTED_DATE end, 'dd/MM/yyyy') AS REPORTED_DATE
	, att2.ATTACHMENT			AS REPORT_ATTACHMENT
	, att2.ATTACHMENT_PHYSICAL	AS REPORT_ATTACHMENT_PHYSICAL
	, a.CANCEL_REASON
	, p2.ACTUAL_RESULT
	, a.CREATED_BY
FROM SAM_ACTIVITY a
	INNER JOIN SAM_ORGANIZATION_LOCATION l ON a.ID = l.ACTIVITY_ID
	INNER JOIN SAM_M_ACTIVITY_STATUS s ON s.ID = a.STATUS_ID AND s.IS_DELETED = 0
	LEFT JOIN M_EVENTS_MASTERDATA c ON cast(a.CATEGORY_ID as varchar) = c.CODE AND c.TYPE = 'ACTIVITY_CATEGORY'
	LEFT JOIN SAM_ATTACHMENT att2 ON a.ID = att2.ACT_ID AND att2.TYPE = 'REPORT'
	LEFT JOIN SAM_PLAN p1 ON p1.ACTIVITY_ID = a.ID and p1.PLAN_DATE IS NOT NULL AND p1.ACTUAL_DATE IS NULL
	LEFT JOIN SAM_PLAN p2 ON p2.ACTIVITY_ID = a.ID and p2.PLAN_DATE IS NULL AND p2.ACTUAL_DATE IS NOT NULL
WHERE 1 = 1
	AND a.ACT_CODE = /*actCode*/'A000000001'
	/*IF agentCode != null && agentCode != ''*/
	AND a.CREATED_BY = /*agentCode*/'1000124'
	/*END*/
	/*IF zones != null && zones.size() > 0*/ 
	AND l.ZONE_CODE IN /*zones*/()
	/*END*/
