/*
 * Created on 2019-01-18 ( Date ISO 2019-01-18 - Time 16:13:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package vn.com.unit.cms.admin.all.dto;

import java.util.Date;

/**
 * Domain class for dto "ExportProduct"
 *
 * @author phatvt
 *
 */
public class ExportIntroductionReportDto {


    //----------------------------------------------------------------------
    //  DATA FIELDS 
    //----------------------------------------------------------------------    
    private Integer    stt          ;
    private String     categoryName ;
    private String     code         ;
    private String     title        ;
    private String     enabled      ;
    private String     statusName   ;
    private String     createBy     ;
    private Date       createDate   ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ExportIntroductionReportDto() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR "DATA FIELDS"
    //----------------------------------------------------------------------
    public void setStt( Integer stt ) {
        this.stt = stt ;
    }
    public Integer getStt() {
        return this.stt;
    }

    public void setCategoryName( String categoryName ) {
        this.categoryName = categoryName ;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCode( String code ) {
        this.code = code ;
    }
    public String getCode() {
        return this.code;
    }

    public void setTitle( String title ) {
        this.title = title ;
    }
    public String getTitle() {
        return this.title;
    }

    public void setEnabled( String enabled ) {
        this.enabled = enabled ;
    }
    public String getEnabled() {
        return this.enabled;
    }

    public void setStatusName( String statusName ) {
        this.statusName = statusName ;
    }
    public String getStatusName() {
        return this.statusName;
    }

    public void setCreateBy( String createBy ) {
        this.createBy = createBy ;
    }
    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate ;
    }
    public Date getCreateDate() {
        return this.createDate;
    }


}
