/*
 * Created on 2019-01-15 ( Date ISO 2019-01-15 - Time 10:40:09 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package vn.com.unit.cms.admin.all.dto;

import java.util.Date;

//import vn.com.unit.cms.admin.all.enumdef.ProductConsultingStatusEnum;

/**
 * Domain class for dto "ExportProductConsult"
 *
 * @author phatvt
 *
 */
public class ExportProductConsultReportDto {

	// ----------------------------------------------------------------------
	// DATA FIELDS
	// ----------------------------------------------------------------------
	private Long stt;
	private String fullname;
	private String address;
	private String phoneNumber;
	private String productName;
	private String province;
	private String district;
	private Date createDate;
	private String createTime;
	private String commentName;
	private String processingStatus;
	private String processUser;
	private String updateDate;
	
	

	/**
	 * @return the province
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * @param province
	 *            the province to set
	 */
	public void setProvince(String province) {
		this.province = province;
	}

	/**
	 * @return the district
	 */
	public String getDistrict() {
		return district;
	}

	/**
	 * @param district
	 *            the district to set
	 */
	public void setDistrict(String district) {
		this.district = district;
	}

	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public ExportProductConsultReportDto() {
		super();
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR "DATA FIELDS"
	// ----------------------------------------------------------------------
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public String getFullname() {
		return this.fullname;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * @return the stt
	 * @author taitm
	 */
	public Long getStt() {
		return stt;
	}

	/**
	 * @param stt
	 *            the stt to set
	 * @author taitm
	 */
	public void setStt(Long stt) {
		this.stt = stt;
	}

	/**
	 * @return the productName
	 * @author taitm
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * @param productName
	 *            the productName to set
	 * @author taitm
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * @return the createTime
	 * @author taitm
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * @param createTime
	 *            the createTime to set
	 * @author taitm
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the address
	 * @author taitm
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * @param address
	 *            the address to set
	 * @author taitm
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * @return the commentName
	 */
	public String getCommentName() {
		return commentName;
	}

	/**
	 * @return the processingStatus
	 */
	public String getProcessingStatus() {
		return processingStatus;
	}

	/**
	 * @return the processUser
	 */
	public String getProcessUser() {
		return processUser;
	}

	/**
	 * @return the updateDate
	 */
	public String getUpdateDate() {
		return updateDate;
	}

	/**
	 * @param commentName the commentName to set
	 */
	public void setCommentName(String commentName) {
		this.commentName = commentName;
	}

	/**
	 * @param processingStatus the processingStatus to set
	 */
	public void setProcessingStatus(String processingStatus) {
		this.processingStatus = processingStatus;
	}

	/**
	 * @param processUser the processUser to set
	 */
	public void setProcessUser(String processUser) {
		this.processUser = processUser;
	}

	/**
	 * @param updateDate the updateDate to set
	 */
	public void setUpdateDate(String updateDate) {
		this.updateDate = updateDate;
	}

}
