/*
 * Created on 2019-01-18 ( Date ISO 2019-01-18 - Time 16:13:03 ) Generated by Telosys ( http://www.telosys.org/ )
 * version 3.0.0
 */
package vn.com.unit.cms.admin.all.dto;

import java.util.Date;

/**
 * Domain class for dto "ExportProduct"
 *
 * @author phatvt
 */
public class ExportInvestorReportDto {

	// ----------------------------------------------------------------------
	// DATA FIELDS
	// ----------------------------------------------------------------------
	private Integer stt;
	private String investorCategoryNameLevel1;
	private String investorCategoryNameLevel2;
	private String investorCategoryNameLevel3;
	private String investorCategoryNameLevel4;
	private String kind;
	private String kindNameAttr;
	private String kindName;
	private String code;
	private String title;
	private String statusName;
	private String enabled;
	private String createBy;
	private Date createDate;

	private Long categoryId;

	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public ExportInvestorReportDto() {
		super();
	}

	/**
	 * @return the stt
	 * @author taitm
	 */
	public Integer getStt() {
		return stt;
	}

	/**
	 * @param stt
	 *            the stt to set
	 * @author taitm
	 */
	public void setStt(Integer stt) {
		this.stt = stt;
	}

	/**
	 * @return the investorCategoryNameLevel1
	 * @author taitm
	 */
	public String getInvestorCategoryNameLevel1() {
		return investorCategoryNameLevel1;
	}

	/**
	 * @param investorCategoryNameLevel1
	 *            the investorCategoryNameLevel1 to set
	 * @author taitm
	 */
	public void setInvestorCategoryNameLevel1(String investorCategoryNameLevel1) {
		this.investorCategoryNameLevel1 = investorCategoryNameLevel1;
	}

	/**
	 * @return the investorCategoryNameLevel2
	 * @author taitm
	 */
	public String getInvestorCategoryNameLevel2() {
		return investorCategoryNameLevel2;
	}

	/**
	 * @param investorCategoryNameLevel2
	 *            the investorCategoryNameLevel2 to set
	 * @author taitm
	 */
	public void setInvestorCategoryNameLevel2(String investorCategoryNameLevel2) {
		this.investorCategoryNameLevel2 = investorCategoryNameLevel2;
	}

	/**
	 * @return the investorCategoryNameLevel3
	 * @author taitm
	 */
	public String getInvestorCategoryNameLevel3() {
		return investorCategoryNameLevel3;
	}

	/**
	 * @param investorCategoryNameLevel3
	 *            the investorCategoryNameLevel3 to set
	 * @author taitm
	 */
	public void setInvestorCategoryNameLevel3(String investorCategoryNameLevel3) {
		this.investorCategoryNameLevel3 = investorCategoryNameLevel3;
	}

	/**
	 * @return the investorCategoryNameLevel4
	 * @author taitm
	 */
	public String getInvestorCategoryNameLevel4() {
		return investorCategoryNameLevel4;
	}

	/**
	 * @param investorCategoryNameLevel4
	 *            the investorCategoryNameLevel4 to set
	 * @author taitm
	 */
	public void setInvestorCategoryNameLevel4(String investorCategoryNameLevel4) {
		this.investorCategoryNameLevel4 = investorCategoryNameLevel4;
	}

	/**
	 * @return the kind
	 * @author taitm
	 */
	public String getKind() {
		return kind;
	}

	/**
	 * @param kind
	 *            the kind to set
	 * @author taitm
	 */
	public void setKind(String kind) {
		this.kind = kind;
	}

	/**
	 * @return the code
	 * @author taitm
	 */
	public String getCode() {
		return code;
	}

	/**
	 * @param code
	 *            the code to set
	 * @author taitm
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * @return the title
	 * @author taitm
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * @param title
	 *            the title to set
	 * @author taitm
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * @return the enabled
	 * @author taitm
	 */
	public String getEnabled() {
		return enabled;
	}

	/**
	 * @param enabled
	 *            the enabled to set
	 * @author taitm
	 */
	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	/**
	 * @return the statusName
	 * @author taitm
	 */
	public String getStatusName() {
		return statusName;
	}

	/**
	 * @param statusName
	 *            the statusName to set
	 * @author taitm
	 */
	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	/**
	 * @return the createBy
	 * @author taitm
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * @param createBy
	 *            the createBy to set
	 * @author taitm
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * @return the createDate
	 * @author taitm
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * @param createDate
	 *            the createDate to set
	 * @author taitm
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * @return the categoryId
	 * @author taitm
	 */
	public Long getCategoryId() {
		return categoryId;
	}

	/**
	 * @param categoryId
	 *            the categoryId to set
	 * @author taitm
	 */
	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * @return the kindNameAttr
	 * @author taitm
	 */
	public String getKindNameAttr() {
		return kindNameAttr;
	}

	/**
	 * @param kindNameAttr
	 *            the kindNameAttr to set
	 * @author taitm
	 */
	public void setKindNameAttr(String kindNameAttr) {
		this.kindNameAttr = kindNameAttr;
	}

	/**
	 * @return the kindName
	 * @author taitm
	 */
	public String getKindName() {
		return kindName;
	}

	/**
	 * @param kindName
	 *            the kindName to set
	 * @author taitm
	 */
	public void setKindName(String kindName) {
		this.kindName = kindName;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR "DATA FIELDS"
	// ----------------------------------------------------------------------

}
