/*
 * Created on 2019-03-05 ( Date ISO 2019-03-05 - Time 16:34:51 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package vn.com.unit.cms.admin.all.dto;

import java.util.Date;

/**
 * Domain class for dto "ExportNewsType"
 *
 * @author phatvt
 *
 */
public class ExportNewsTypeReportDto {


    //----------------------------------------------------------------------
    //  DATA FIELDS 
    //----------------------------------------------------------------------    
    private Integer    stt          ;
    private String     code         ;
    private String     label        ;
    private String     typeOfLibrary ;
    private String     typeOfNew    ;
    private String     enabled      ;
    private String     statusName       ;
    private String     createBy     ;
    private Date       createDate   ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ExportNewsTypeReportDto() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR "DATA FIELDS"
    //----------------------------------------------------------------------

    public void setCode(String code) {
        this.code = code;
    }

    /**
     * @return the stt
     * @author taitm
     */
    public Integer getStt() {
        return stt;
    }

    /**
     * @param stt the stt to set
     * @author taitm
     */
    public void setStt(Integer stt) {
        this.stt = stt;
    }

    public String getCode() {
        return this.code;
    }

    public void setLabel( String label ) {
        this.label = label ;
    }
    public String getLabel() {
        return this.label;
    }

    public void setTypeOfLibrary( String typeOfLibrary ) {
        this.typeOfLibrary = typeOfLibrary ;
    }
    public String getTypeOfLibrary() {
        return this.typeOfLibrary;
    }
    
    /**
     * @return the typeOfNew
     * @author taitm
     */
    public String getTypeOfNew() {
        return typeOfNew;
    }

    /**
     * @param typeOfNew
     *            the typeOfNew to set
     * @author taitm
     */
    public void setTypeOfNew(String typeOfNew) {
        this.typeOfNew = typeOfNew;
    }

    public void setEnabled( String enabled ) {
        this.enabled = enabled ;
    }
    public String getEnabled() {
        return this.enabled;
    }

    public void setCreateBy( String createBy ) {
        this.createBy = createBy ;
    }
    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate ;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    /**
     * @return the statusName
     * @author taitm
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * @param statusName
     *            the statusName to set
     * @author taitm
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }

}
