/*
 * Created on 2019-01-18 ( Date ISO 2019-01-18 - Time 16:13:03 ) Generated by Telosys ( http://www.telosys.org/ )
 * version 3.0.0
 */
package vn.com.unit.cms.core.module.news.dto;

import java.util.Date;

/**
 * Domain class for dto "ExportProduct"
 *
 * @author phatvt
 */
public class ExportNewsReportDto {

	// ----------------------------------------------------------------------
	// DATA FIELDS
	// ----------------------------------------------------------------------
	private Integer stt;
	private String code;
	private String typeName;
	private String title;
	private String headlines;
	private String enabled;
	private String latestNews;
	private String pressRelease;
	private String promotion;
	private String statusName;
	private String createBy;
	private Date createDate;

	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public ExportNewsReportDto() {
		super();
	}

	/**
	 * @return the stt
	 * @author taitm
	 */
	public Integer getStt() {
		return stt;
	}

	/**
	 * @param stt
	 *            the stt to set
	 * @author taitm
	 */
	public void setStt(Integer stt) {
		this.stt = stt;
	}

	/**
	 * @return the code
	 * @author taitm
	 */
	public String getCode() {
		return code;
	}

	/**
	 * @param code
	 *            the code to set
	 * @author taitm
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * @return the typeName
	 * @author taitm
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * @param typeName
	 *            the typeName to set
	 * @author taitm
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
	 * @return the title
	 * @author taitm
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * @param title
	 *            the title to set
	 * @author taitm
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * @return the headlines
	 * @author taitm
	 */
	public String getHeadlines() {
		return headlines;
	}

	/**
	 * @param headlines
	 *            the headlines to set
	 * @author taitm
	 */
	public void setHeadlines(String headlines) {
		this.headlines = headlines;
	}

	/**
	 * @return the enabled
	 * @author taitm
	 */
	public String getEnabled() {
		return enabled;
	}

	/**
	 * @param enabled
	 *            the enabled to set
	 * @author taitm
	 */
	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	/**
	 * @return the latestNews
	 * @author taitm
	 */
	public String getLatestNews() {
		return latestNews;
	}

	/**
	 * @param latestNews
	 *            the latestNews to set
	 * @author taitm
	 */
	public void setLatestNews(String latestNews) {
		this.latestNews = latestNews;
	}

	/**
	 * @return the pressRelease
	 * @author taitm
	 */
	public String getPressRelease() {
		return pressRelease;
	}

	/**
	 * @param pressRelease
	 *            the pressRelease to set
	 * @author taitm
	 */
	public void setPressRelease(String pressRelease) {
		this.pressRelease = pressRelease;
	}

	/**
	 * @return the promotion
	 * @author taitm
	 */
	public String getPromotion() {
		return promotion;
	}

	/**
	 * @param promotion
	 *            the promotion to set
	 * @author taitm
	 */
	public void setPromotion(String promotion) {
		this.promotion = promotion;
	}

	/**
	 * @return the statusName
	 * @author taitm
	 */
	public String getStatusName() {
		return statusName;
	}

	/**
	 * @param statusName
	 *            the statusName to set
	 * @author taitm
	 */
	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	/**
	 * @return the createBy
	 * @author taitm
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * @param createBy
	 *            the createBy to set
	 * @author taitm
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * @return the createDate
	 * @author taitm
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * @param createDate
	 *            the createDate to set
	 * @author taitm
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR "DATA FIELDS"
	// ----------------------------------------------------------------------

}
