	SELECT  VW.GROUP_CODE

	FROM VW_AUTHORITY_DETAIL vw
	INNER JOIN JCA_ACCOUNT acc
		ON ACC.USERNAME = vw.username
		and ACC.USERNAME = /*userNameLogin*/'linhmtt_moderator'
	inner join JCA_ROLE role
		ON role.ID = VW.ROLE_ID
	WHERE
		VW.ACTIVED = 1
		AND ROLE_ACTIVED = 1
	GROUP BY ACC.id, vw.USERNAME, VW.GROUP_CODE, role.NAME;