package vn.com.unit.ep2p.enumdef;

public enum ReportGroupPremiumDetailOHEnum {
		OFFICE("	0	")
	,	LEADER("	1	")
	,	SUBMITTOTALFILE("	2	")
	,	SUBMITTOTALFYP("	3	")
	,	RELEASETOTALACTIVE("	4	")
	,	RELEASETOTALFYP("	5	")
	,	CANCELTOTALFILE("	6	")
	,	CANCELFYP("	7	")
	,	FYPEDIT("	8	")
	,	FYP ("	9	")
	,	RYP	("	10	")
	,	K2	("	11	")
	,	K2PLUS("	12	")
	,	LASTYEARSUBMITTOTALFILE	("	13	")
	,	LASTYEARSUBMITTOTALFYP	("	14	")
	,	LASTYEARRELEASETOTALFILE("	15	")
	,	LASTYEARRELEASETOTALFYP	("	16	")
	,	LASTYEARACTIONTOTALFILE	("	17	")
	,	LASTYEARACTIONTOTALFYP	("	18	")
	,	LASTYEARTOTALRYP("	19	")
	,	LASTYEARTOTALGRAND("	20	")
	,	QUANTILYBM	("	21	")
	,	QUANTILYUM	("	22	")
	,	QUANTILYPUM	("	23	")
	,	QUANTILYFC	("	24	")
	,	QUANTILYSA	("	25	")
	,	RECRUITMENT	("	26	")
	,	RECOVERYCODE	("	27	")
	,	QUANTILYFCACTION	("	28	")
	,	QUANTILYFCACTIONNEW	("	29	")
	,	QUANTILYFCACTIONNEWSCHEME	("	30	")
	,	QUANTILYFCPFC	("	31	")
	,	LASTYEARRECRUITMENT	("	32	")
	,	LASTYEARRECOVERYCODE	("	33	")
	,	LASTYEARQUANTILYACTIONNEW	("	34	")
	,	LASTYEARQUANTILYACTION	("	35	");

	private String value;

	private ReportGroupPremiumDetailOHEnum(String value) {
		this.value = value;
	}

	public String toString() {
		return value;
	}
}
