package vn.com.unit.ep2p.enumdef;

import lombok.AllArgsConstructor;

@AllArgsConstructor
public enum ReportBusinessResultGaBmEnum {
    MANAGERALL("0")//QUAN LY
    , AGENTALL("1")//TVTC
    , PROFILETOTALSUBMIT("2")//NOP VAO
    , FYPTOTALSUBMIT("3")
    , CONTRACTTOTALRELEASE("4")//PHAT HANH
    , FYPTOTALRELEASE("5")
    , CONTRACTTOTALRELEASEPURE("6")//PHAT HANH THUAN
    , FYPTOTALRELEASEPURE("7")
    , CONTRACTTOTALCANCEL("8")//HUY
    , FYPTOTALCANCEL("9")
    
    , FYPRESUME("10")//ĐC/TÁI TỤC FYP
    , RYPTOTAL("11")//RYP
    , K2("12")//%K2
    , K2PLUS("13")//%K2+
    
    //cung ky nam trc
    , PROFILETOTALSUBMITLASTYEAR("14")//TỔNG HỒ SƠ NOP VAO
    , FYPTOTALSUBMITLASTYEAR("15")//TỔNG FYP
    , CONTRACTTOTALRELEASELASTYEAR("16")////TỔNG HỢP ĐỒNG PHAT HANH
    , FYPTOTALRELEASELASTYEAR("17")//TỔNG FYP
    , CONTRACTTOTALRELEASEPURELASTYEAR("18")//TỔNG HỢP ĐỒNG PHAT HANH THUAN
    , FYPTOTALRELEASEPURELASTYEAR("19")//TỔNG FYP
    , RYPTOTALLASTYEAR("20")//TỔNG RYP
    
    , BMQUANTITY("21")
    , UMQUANTITY("22")
    , PUMQUANTITY("23")
    , FCQUANTITY("24")
    , SAQUANTITY("25")
    , RECRUITMENTQUANTITY("26")
    , RECOVERYCODEQUANTITY("27")
    , ACTIVEFCQUANTITY("28")
    //, NEWACTIVEFCQUANTITY("12")
    , ACTIVEFCBYSCHEMAQUANTITY("29")
    , DYNAMICFCQUANTITY("30")
    //cung ky nam ngoai
    , RECRUITMENTQUANTITYLASTYEAR("31")
    , RECOVERYCODEQUANTITYLASTYEAR("32")
    , NEWACTIVEMEMBERLASTYEAR("33")
    , ACTIVEQUANTITYLASTYEAR("34"); 
    
    private String value;

    public String toString() {
        return value;
    }
}
