package vn.com.unit.ep2p.enumdef;

public enum ResultPromotionSBMEnum {
	BDTH("0")
	,BDAH("1")
	,BDRH("2")
	,BDOH("3")
	,LEADER("4")
	,OFFICE("5")
	,DATEREVIEWPROMOORDEMO("6")
	,MONTHSBM("7")
	,ACTIVITYRETENTIONRATEK2("8")
	,FYP6ALLMONTHS("9")
	,AFC6MONTHS("10")
	,RECRUITMENT6MONTHS("11")
	,SUBGROUPDEVELOPUMORSUM("12")
	,SUBGROUPDEVELOPPUM("13")
	,SUBGROUPDEVELOPBM("14")
	,EVALUATEPROMOTION("15")
	,FLACTIVITYRETENTIONRATEK2("16")
	,FLFYP6ALLMONTHS("17")
	,FLAFC6MONTHS("18")
	,FLRECRUITMENT6MONTHS("19")
	,FLSUBGROUPDEVELOPUMORSUM("20")
	,FLSUBGROUPDEVELOPPUM("21")
	,FLSUBGROUPDEVELOPBM("22")
;

	private String value;
	
	private ResultPromotionSBMEnum(String value) {
		this.value = value;
	}

	public String toString() {
		return value;
	}
}
