SELECT count(*)
FROM M_CONTEST_SUMMARY tb
INNER JOIN M_CONTEST_DETAIL detail
on tb.MEMO_NO=detail.MEMO_NO
WHERE
	tb.DELETED_DATE is null
	AND CONVERT(DATE, tb.START_DATE) <= CONVERT(DATE, GETDATE())
	AND CONVERT(DATE, ISNULL(tb.END_DATE, GETDATE())) >= CONVERT(DATE, GETDATE())
	AND CONVERT(DATE, tb.EFFECTIVE_DATE) <= CONVERT(DATE, GETDATE())
	AND CONVERT(DATE, ISNULL(tb.EXPIRED_DATE, GETDATE())) >= CONVERT(DATE, GETDATE())
	AND tb.ENABLED = 1
	/*IF searchDto.agentCode != null && searchDto.agentCode != ''*/
	AND detail.AGENT_CODE=/*searchDto.agentCode*/
	/*END*/
