SELECT 
	M_PRODUCT.CODE   AS PRODUCT_CODE
	,M_PRODUCT.PRODUCT_NAME  
	,M_PRODUCT.PRODUCT_TYPE   
	,M_PRODUCT.UNIT_PRICE   
	,M_PRODUCT.PRODUCT_IMG   
	,M_PRODUCT.PRODUCT_PHYSICAL_IMG 
	,COALESCE(M_ORDER_DETAIL.QUANTITY,0)  AS QUANTITY
	,CASE WHEN M_ORDER_DETAIL.PRODUCT_CODE IS NOT NULL THEN 1 else 0 END AS FLAG 

FROM M_PRODUCT
LEFT JOIN M_ORDER_DETAIL 
ON M_PRODUCT.CODE = M_ORDER_DETAIL.PRODUCT_CODE and M_ORDER_DETAIL.ORDER_ID = /*orderId*/
where GETDATE() between M_PRODUCT.EFFECTIVE_DATE and M_PRODUCT.EXPIRED_DATE
ORDER BY M_PRODUCT.CODE
