SELECT 
	M_ORDER.ID
	,M_ORDER.CODE
	,M_ORDER.AGENT_CODE
	,M_ORDER.AGENT_NAME
	,M_ORDER.MANAGER_CODE
	,M_ORDER.MANAGER_NAME
	,M_ORDER.OFFICE_CODE
	,M_ORDER.OFFICE_NAME
	,M_ORDER.PHONE							
	,M_ORDER.DELIVERY_AGENT_CODE				
	,M_ORDER.DELIVERY_AGENT_NAME
	,M_ORDER.DELIVERY_OFFICE_CODE
	,M_ORDER.DELIVERY_PROVINCE
	,M_ORDER.INVOICE_OFFICE_CODE		
	,M_ORDER.INVOICE_COMPANY_NAME
	,M_ORDER.INVOICE_TAX_CODE
	,M_ORDER.INVOICE_COMPANY_ADDRESS
	,M_ORDER.TOTAL_AMOUNT
	,M_ORDER.STATUS	   AS STATUS_ORDER
	,JCA_CONSTANT.NAME AS STATUS_NAME
	
FROM M_ORDER 
INNER JOIN JCA_CONSTANT 
ON GROUP_CODE = 'M_ORDER' and JCA_CONSTANT.CODE = M_ORDER.STATUS and KIND = 'STATUS'
WHERE M_ORDER.ID = /*orderId*/
/*IF userName != null*/
AND M_ORDER.AGENT_CODE = /*userName*/
/*END*/
