SELECT CASE WHEN taskMapp.ACCOUNT_ID IS NOT NULL THEN taskMapp.ACCOUNT_ID
	WHEN res.OWNER_ IS NOT NULL THEN TO_NUMBER(res.OWNER_)
	WHEN res.ASSIGNEE_ IS NOT NULL THEN TO_NUMBER(res.ASSIGNEE_)
    WHEN iLink.USER_ID_ IS NOT NULL THEN TO_NUMBER(iLink.USER_ID_)
    ELSE TO_NUMBER(membership.USER_ID_) END AS ASSIGNEE_ID
FROM
    EFO_OZ_DOC_TASK_MAPPING taskMapp
    LEFT JOIN ACT_RU_TASK res ON (taskMapp.TASK_TYPE = 1 AND taskMapp.ACT_TASK_ID = res.ID_)
    LEFT JOIN ACT_RU_IDENTITYLINK iLink ON (iLink.TASK_ID_ = res.ID_ AND iLink.TYPE_ = 'candidate')
    LEFT JOIN ACT_ID_MEMBERSHIP membership ON (iLink.GROUP_ID_ = membership.GROUP_ID_)
WHERE
     taskMapp.TASK_TYPE = 1 
     AND DOC_ID = /*docId*/0
     AND taskMapp.TASK_ID = /*taskId*/0