select
	VH.VIETNAMESEHOLIDAYDATE VIETNAMESE_HOLIDAY_DATE,
    VH.DESCRIPTION,
    VH.CREATED_BY CREATED_BY,
    VH.CREATED_DATE CREATE_DATE, 
	VH.UPDATED_BY UPDATED_BY,
    VH.UPDATED_DATE UPDATED_DATE
FROM
	SLA_DAY_OFF VH
WHERE
	ROWNUM = 1  	
	AND VH.VIETNAMESEHOLIDAYDATE = /*vietnameseHolidayDate*/''
	/*IF companyId != null*/
	AND VH.COMPANY_ID = /*companyId*/
	/*END*/
	/*IF companyId == null*/
	AND VH.COMPANY_ID IS NULL
	/*END*/
	AND VH.CALENDAR_TYPE_ID = /*calendarType*/
	;