SELECT 
	 FAVORITE.ID 			AS ID
	,FAVORITE.TYPE			AS TYPE
	,FAVORITE.TITLE			AS TITLE
	,FAVORITE.LINK			AS LINK
	,FAVORITE.NAMED			AS NAMED
	,FAVORITE.ICON			AS ICON
	,FAVORITE.DEFAULT_FLAG			AS DEFAULT_FLAG
FROM
	M_MENU_FAVORITE FAVORITE
WHERE
	FAVORITE.AGENT_CODE = /*agentCode*/
	OR ISNULL(FAVORITE.DEFAULT_FLAG, 0) = 1
