export const HEALTH_CONSULTING = [
    {
        "forCandidate": 0,
        "code": "QA_DOCTOR",
        "enabled": 0,
        "isVideo": 0,
        "isVideoYoutube": 0,
        "no": 0,
        "countUsed": 0,
        "homepage": 0,
        "event": 0,
        "label": "Đặt câu hỏi cho Bác sĩ",
        "linkAlias": "hoi-dap",
        "sort": 0,
        "robotIndexTag": false,
        "robotFollowTag": false,
        "hasEvent": false
    },
    {
        "forCandidate": 0,
        "code": "CHAT_TO_DOCTOR",
        "enabled": 0,
        "isVideo": 0,
        "isVideoYoutube": 0,
        "no": 0,
        "countUsed": 0,
        "homepage": 0,
        "event": 0,
        "label": "Nhắn tin với Bác sĩ",
        "linkAlias": "gioi-thieu-tu-van?hinh-thuc=chat",
        "sort": 0,
        "robotIndexTag": false,
        "robotFollowTag": false,
        "hasEvent": false
    },
    {
        "forCandidate": 0,
        "code": "VIDEO_TO_DOCTOR",
        "enabled": 0,
        "isVideo": 0,
        "isVideoYoutube": 0,
        "no": 0,
        "countUsed": 0,
        "homepage": 0,
        "event": 0,
        "label": "Tư vấn video với Bác sĩ",
        "linkAlias": "gioi-thieu-tu-van?hinh-thuc=video",
        "sort": 0,
        "robotIndexTag": false,
        "robotFollowTag": false,
        "hasEvent": false
    },
    {
        "forCandidate": 0,
        "code": "FAMILY_PROFILE",
        "enabled": 0,
        "isVideo": 0,
        "isVideoYoutube": 0,
        "no": 0,
        "countUsed": 0,
        "homepage": 0,
        "event": 0,
        "label": "Hồ sơ gia đình",
        "linkAlias": "ho-so-gia-dinh",
        "sort": 0,
        "robotIndexTag": false,
        "robotFollowTag": false,
        "hasEvent": false
    },
    {
        "forCandidate": 0,
        "code": "CONSULTINGROOM",
        "enabled": 0,
        "isVideo": 0,
        "isVideoYoutube": 0,
        "no": 0,
        "countUsed": 0,
        "homepage": 0,
        "event": 0,
        "label": "Phòng tư vấn",
        "linkAlias": "phong-tu-van",
        "sort": 0,
        "robotIndexTag": false,
        "robotFollowTag": false,
        "hasEvent": false
    },
    {
        "forCandidate": 0,
        "code": "NOTEBOOK",
        "enabled": 0,
        "isVideo": 0,
        "isVideoYoutube": 0,
        "no": 0,
        "countUsed": 0,
        "homepage": 0,
        "event": 0,
        "label": "Sổ tay hỏi đáp",
        "linkAlias": "so-tay",
        "sort": 0,
        "robotIndexTag": false,
        "robotFollowTag": false,
        "hasEvent": false
    },
];
