UPDATE
    M_TRAINING_COURSES_DETAIL
SET
    ATTENDANCE_TIME = GETDATE()
FROM M_TRAINING_COURSES_DETAIL T1
INNER JOIN M_TRAINING_COURSES T2
ON T1.COURSE_ID = T2.ID and FORMAT(T2.END_DATE, 'ddMMyyyy') = FORMAT(GETDATE(), 'ddMMyyyy')
where T2.COURSE_CODE = /*courseCode*/'HL2504.0009'
/*IF agentCode.length() > 8*/
and T1.ID_NUMBER = /*agentCode*/'641025'
-- ELSE and T1.AGENT_CODE = /*agentCode*/
/*END*/
and T1.ATTENDANCE_TIME is null
