SELECT 
	acc.FULLNAME										AS	CREATED_BY
	, att.*
FROM JCA_ATTACHED_FILE att
LEFT JOIN JCA_M_ACCOUNT	acc
	ON (acc.username = att.CREATED_BY
		AND acc.DELETED_BY IS NULL
		AND acc.ACTIVED = 1
	)
WHERE att.REFERENCE = /*ref*/;