select ROW_NUMBER() OVER (ORDER BY T1.ID desc) AS no
, T1.ID
, T1.AGENT_CODE
, T2.FULLNAME as AGENT_NAME
, T1.ID_NUMBER
, T1.EMAIL
, T1.BANK_ACCOUNT_NUMBER
, T1.BANK_ACCOUNT_NAME
, T1.BANK_NAME
, T1.BANK_BRANCH_NAME
, T1.IMG1_PHYSICAL
, T1.IMG2_PHYSICAL
, T1.SUBMIT_TIME
from [dbo].[M_AGENT_BANK_UPDATE_HISTORY] T1
inner join [dbo].[JCA_ACCOUNT] T2
on T1.AGENT_CODE = T2.USERNAME
where T1.AGENT_CODE = /*agentCode*/'119720'