SELECT
    A.ID,
    A.CLIENT_ID,
	A.CLIENT_NAME,
    A.PURPOSE_CODE,
	M.NAME as PURPOSE_NAME,
    A.APPOINTMENT_TIME,
    A.LOCATION,
    A.NOTES,
    A.CREATED_BY,
    A.CREATED_DATE,
    ROW_NUMBER() OVER (ORDER BY APPOINTMENT_TIME ASC) as NO
FROM M_APPOINTMENT A
INNER JOIN M_EVENTS_MASTERDATA M on A.PURPOSE_CODE = M.CODE and M.TYPE = 'APPOINTMENT_PURPOSE'
WHERE 1 = 1
/*IF appointmentDate != null*/
  AND CONVERT(DATE, A.APPOINTMENT_TIME) = CONVERT(DATE, /*appointmentDate*/'2025-05-13')
/*END*/
/*IF agentCode != null && agentCode != ''*/
  AND A.CREATED_BY = /*agentCode*/'131597'
/*END*/
ORDER BY A.APPOINTMENT_TIME ASC
/*IF page != null && pageSize != null*/
OFFSET /*page*/0 ROWS FETCH NEXT /*pageSize*/10 ROWS ONLY
/*END*/