/*
 * Created on 2021-04-10 ( Date ISO 2021-04-10 - Time 14:03:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */
package vn.com.unit.ep2p.dto.req;

import java.util.Date;

//import jp.sf.amateras.mirage.annotation.Column;

/**
 * Domain class for entity "ErsCandidate"
 *
 * @author telosys
 *
 */
public class ErsCandidate {

    private Long id;

    /** Column: channel VARCHAR(10) */
    private String channel;

    /** Column: applyForPosition VARCHAR(255) */
    private String applyForPosition;

    /** Column: positionName VARCHAR(255) */
    private String positionName;

    /** Column: optionSupport TINYINT(3) */
    private Byte optionSupport;

    /** Column: regionName VARCHAR(10) */
    private String regionName;

    /** Column: provinceName NVARCHAR(255) */
    private String provinceName;

    /** Column: agentCode VARCHAR(10) */
    private String agentCode;

    /** Column: bpCode VARCHAR(10) */
    private String bpCode;

    /** Column: dateAppointed DATE(10) */
    private Date dateAppointed;

    /** Column: dateTerminate DATE(10) */
    private Date dateTerminate;

    /** Column: agentStatus NVARCHAR(10) */
    private String agentStatus;

    /** Column: reinsFlag TINYINT(3) */
    private Byte reinsFlag;

    /** Column: partnerMic NVARCHAR(200) */
    private String partnerMic;

    /** Column: idType VARCHAR(10) */
    private String idType;

    /** Column: idNo VARCHAR(50) */
    private String idNo;

    /** Column: idDateOfIssue DATE(10) */
    private Date idDateOfIssue;

    /** Column: idPlaceOfIssue VARCHAR(10) */
    private String idPlaceOfIssue;

    /** Column: idPlaceOfIssueName NVARCHAR(255) */
    private String idPlaceOfIssueName;

    /** Column: otherIdNo VARCHAR(10) */
    private String otherIdNo;

    /** Column: otherIdDateOfIssue DATE(10) */
    private Date otherIdDateOfIssue;

    /** Column: otherIdPlaceOfIssue VARCHAR(10) */
    private String otherIdPlaceOfIssue;

    /** Column: otherIdPlaceName NVARCHAR(255) */
    private String otherIdPlaceName;

    /** Column: candidateName NVARCHAR(255) */
    private String candidateName;

    /** Column: gender VARCHAR(2) */
    private String gender;

    /** Column: genderName VARCHAR(50) */
    private String genderName;

    /** Column: dob DATE(10) */
    private Date dob;

    /** Column: pob VARCHAR(10) */
    private String pob;

    /** Column: pobName NVARCHAR(255) */
    private String pobName;

    /** Column: email VARCHAR(255) */
    private String email;

    /** Column: mobile VARCHAR(20) */
    private String mobile;

    /** Column: nationality NVARCHAR(255) */
    private String nationality;

    /** Column: nation NVARCHAR(255) */
    private String nation;

    /** Column: educational VARCHAR(255) */
    private String educational;

    /** Column: carrerCurrent VARCHAR(255) */
    private String carrerCurrent;

    /** Column: maritalStatus VARCHAR(10) */
    private String maritalStatus;

    /** Column: taxCode VARCHAR(50) */
    private String taxCode;

    /** Column: permanentAddress NVARCHAR(255) */
    private String permanentAddress;

    /** Column: permanentNest NVARCHAR(255) */
    private String permanentNest;

    /** Column: permanentProvince VARCHAR(10) */
    private String permanentProvince;

    /** Column: permanentProvinceName NVARCHAR(255) */
    private String permanentProvinceName;

    /** Column: permanentDistrict VARCHAR(10) */
    private String permanentDistrict;

    /** Column: permanentDistrictName NVARCHAR(255) */
    private String permanentDistrictName;

    /** Column: permanentWard VARCHAR(10) */
    private String permanentWard;

    /** Column: permanentWardName NVARCHAR(255) */
    private String permanentWardName;

    /** Column: sameAddress TINYINT(3) */
    private Byte sameAddress;

    /** Column: currentAddress NVARCHAR(255) */
    private String currentAddress;

    /** Column: currentNest NVARCHAR(255) */
    private String currentNest;

    /** Column: currentProvince VARCHAR(10) */
    private String currentProvince;

    /** Column: currentProvinceName NVARCHAR(255) */
    private String currentProvinceName;

    /** Column: currentDistrict VARCHAR(10) */
    private String currentDistrict;

    /** Column: currentDistrictName NVARCHAR(255) */
    private String currentDistrictName;

    /** Column: currentWard VARCHAR(10) */
    private String currentWard;

    /** Column: currentWardName NVARCHAR(255) */
    private String currentWardName;

    /** Column: contactFullName NVARCHAR(255) */
    private String contactFullName;

    /** Column: contactPhone VARCHAR(10) */
    private String contactPhone;

    /** Column: contactRelationship VARCHAR(10) */
    private String contactRelationship;

    /** Column: accountName NVARCHAR(255) */
    private String accountName;

    /** Column: accountNumber VARCHAR(50) */
    private String accountNumber;

    /** Column: bankName NVARCHAR(255) */
    private String bankName;

    /** Column: bankProvince NVARCHAR(255) */
    private String bankProvince;

    /** Column: bankBranch VARCHAR(255) */
    private String bankBranch;

    /** Column: bankBranchName NVARCHAR(255) */
    private String bankBranchName;

    /** Column: classType VARCHAR(255) */
    private String classType;

    /** Column: onlineOffline VARCHAR(10) */
    private String onlineOffline;

    /** Column: classProvince VARCHAR(10) */
    private String classProvince;

    /** Column: classProvinceName NVARCHAR(255) */
    private String classProvinceName;

    /** Column: classCode NVARCHAR(100) */
    private String classCode;

    /** Column: classPlace NVARCHAR(255) */
    private String classPlace;

    /** Column: beginningDate DATE(10) */
    private Date beginningDate;

    /** Column: completedDate DATE(10) */
    private Date completedDate;

    /** Column: examPlace NVARCHAR(255) */
    private String examPlace;

    /** Column: examDate DATE(10) */
    private Date examDate;

    /** Column: firstClassDate DATE(10) */
    private Date firstClassDate;

    /** Column: classNote NVARCHAR(255) */
    private String classNote;

    /** Column: recruiterType TINYINT(3) */
    private Byte recruiterType;

    /** Column: recruiterCode BIGINT(19) */
    private Long recruiterCode;

    /** Column: recruiterIdNo VARCHAR(255) */
    private String recruiterIdNo;

    /** Column: recruiterName NVARCHAR(255) */
    private String recruiterName;

    /** Column: recruiterAdCode BIGINT(19) */
    private Long recruiterAdCode;

    /** Column: recruiterAdName NVARCHAR(255) */
    private String recruiterAdName;

    /** Column: recruiterPosition NVARCHAR(255) */
    private String recruiterPosition;

    /** Column: managerType TINYINT(3) */
    private Byte managerType;

    /** Column: managerCode BIGINT(19) */
    private Long managerCode;

    /** Column: managerIdNo VARCHAR(255) */
    private String managerIdNo;

    /** Column: managerName NVARCHAR(255) */
    private String managerName;

    /** Column: managerAdCode BIGINT(19) */
    private Long managerAdCode;

    /** Column: managerAdName NVARCHAR(255) */
    private String managerAdName;

    /** Column: managerPosition NVARCHAR(255) */
    private String managerPosition;

    /** Column: managerIndirectType TINYINT(3) */
    private Byte managerIndirectType;

    /** Column: managerIndirectCode BIGINT(19) */
    private Long managerIndirectCode;

    /** Column: managerIndirectIdNo VARCHAR(255) */
    private String managerIndirectIdNo;

    /** Column: managerIndirectName NVARCHAR(255) */
    private String managerIndirectName;

    /** Column: managerIndirectAdCode BIGINT(19) */
    private Long managerIndirectAdCode;

    /** Column: managerIndirectAdName NVARCHAR(255) */
    private String managerIndirectAdName;

    /** Column: managerIndirectPosition NVARCHAR(255) */
    private String managerIndirectPosition;

    /** Column: checkEkycStatus TINYINT(3) */
    private Byte checkEkycStatus;

    /** Column: ekycOption TINYINT(3) */
    private Byte ekycOption;

    /** Column: ekycSendMailTime DATETIME(23) */
    private Date ekycSendMailTime;

    /** Column: ekycResult TINYINT(3) */
    private Byte ekycResult;

    /** Column: ekycStatus VARCHAR(10) */
    private String ekycStatus;

    /** Column: checkInterviewStatus TINYINT(3) */
    private Byte checkInterviewStatus;

    /** Column: interviewSendMailTime DATETIME(23) */
    private Date interviewSendMailTime;

    /** Column: interviewComment TINYINT(3) */
    private Byte interviewComment;

    /** Column: interviewPoint VARCHAR(10) */
    private String interviewPoint;

    /** Column: interviewStatus VARCHAR(10) */
    private String interviewStatus;

    /** Column: avicadStatus VARCHAR(10) */
    private String avicadStatus;

    /** Column: checkAvicadStatus TINYINT(3) */
    private Byte checkAvicadStatus;

    /** Column: refAttachement VARCHAR(255) */
    private String refAttachement;

    /** Column: companyId BIGINT(19) */
    private Long companyId;

    /** Column: formId BIGINT(19) */
    private Long formId;

    /** Column: docUuid VARCHAR(100) */
    private String docUuid;

    /** Column: formStatus NVARCHAR(255) */
    private String formStatus;

    /** Column: versionData TIMESTAMP(8) */
    private byte[] versionData;

    /** Column: fieldUser1 NVARCHAR(2147483647) */
    private String fieldUser1;

    /** Column: fieldUser2 NVARCHAR(2147483647) */
    private String fieldUser2;

    /** Column: fieldUser3 NVARCHAR(2147483647) */
    private String fieldUser3;

    /** Column: fieldUser4 NVARCHAR(2147483647) */
    private String fieldUser4;

    /** Column: fieldUser5 NVARCHAR(2147483647) */
    private String fieldUser5;

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId() {
        return this.id;
    }

    public void setChannel(String channel) {
        this.channel = channel;
    }

    public String getChannel() {
        return this.channel;
    }

    public void setApplyForPosition(String applyForPosition) {
        this.applyForPosition = applyForPosition;
    }

    public String getApplyForPosition() {
        return this.applyForPosition;
    }

    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    public String getPositionName() {
        return this.positionName;
    }

    public void setOptionSupport(Byte optionSupport) {
        this.optionSupport = optionSupport;
    }

    public Byte getOptionSupport() {
        return this.optionSupport;
    }

    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    public String getRegionName() {
        return this.regionName;
    }

    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    public String getProvinceName() {
        return this.provinceName;
    }

    public void setAgentCode(String agentCode) {
        this.agentCode = agentCode;
    }

    public String getAgentCode() {
        return this.agentCode;
    }

    public void setBpCode(String bpCode) {
        this.bpCode = bpCode;
    }

    public String getBpCode() {
        return this.bpCode;
    }

    public void setDateAppointed(Date dateAppointed) {
        this.dateAppointed = dateAppointed;
    }

    public Date getDateAppointed() {
        return this.dateAppointed;
    }

    public void setDateTerminate(Date dateTerminate) {
        this.dateTerminate = dateTerminate;
    }

    public Date getDateTerminate() {
        return this.dateTerminate;
    }

    public void setAgentStatus(String agentStatus) {
        this.agentStatus = agentStatus;
    }

    public String getAgentStatus() {
        return this.agentStatus;
    }

    public void setReinsFlag(Byte reinsFlag) {
        this.reinsFlag = reinsFlag;
    }

    public Byte getReinsFlag() {
        return this.reinsFlag;
    }

    public void setPartnerMic(String partnerMic) {
        this.partnerMic = partnerMic;
    }

    public String getPartnerMic() {
        return this.partnerMic;
    }

    public void setIdType(String idType) {
        this.idType = idType;
    }

    public String getIdType() {
        return this.idType;
    }

    public void setIdNo(String idNo) {
        this.idNo = idNo;
    }

    public String getIdNo() {
        return this.idNo;
    }

    public void setIdDateOfIssue(Date idDateOfIssue) {
        this.idDateOfIssue = idDateOfIssue;
    }

    public Date getIdDateOfIssue() {
        return this.idDateOfIssue;
    }

    public void setIdPlaceOfIssue(String idPlaceOfIssue) {
        this.idPlaceOfIssue = idPlaceOfIssue;
    }

    public String getIdPlaceOfIssue() {
        return this.idPlaceOfIssue;
    }

    public void setIdPlaceOfIssueName(String idPlaceOfIssueName) {
        this.idPlaceOfIssueName = idPlaceOfIssueName;
    }

    public String getIdPlaceOfIssueName() {
        return this.idPlaceOfIssueName;
    }

    public void setOtherIdNo(String otherIdNo) {
        this.otherIdNo = otherIdNo;
    }

    public String getOtherIdNo() {
        return this.otherIdNo;
    }

    public void setOtherIdDateOfIssue(Date otherIdDateOfIssue) {
        this.otherIdDateOfIssue = otherIdDateOfIssue;
    }

    public Date getOtherIdDateOfIssue() {
        return this.otherIdDateOfIssue;
    }

    public void setOtherIdPlaceOfIssue(String otherIdPlaceOfIssue) {
        this.otherIdPlaceOfIssue = otherIdPlaceOfIssue;
    }

    public String getOtherIdPlaceOfIssue() {
        return this.otherIdPlaceOfIssue;
    }

    public void setOtherIdPlaceName(String otherIdPlaceName) {
        this.otherIdPlaceName = otherIdPlaceName;
    }

    public String getOtherIdPlaceName() {
        return this.otherIdPlaceName;
    }

    public void setCandidateName(String candidateName) {
        this.candidateName = candidateName;
    }

    public String getCandidateName() {
        return this.candidateName;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getGender() {
        return this.gender;
    }

    public void setGenderName(String genderName) {
        this.genderName = genderName;
    }

    public String getGenderName() {
        return this.genderName;
    }

    public void setDob(Date dob) {
        this.dob = dob;
    }

    public Date getDob() {
        return this.dob;
    }

    public void setPob(String pob) {
        this.pob = pob;
    }

    public String getPob() {
        return this.pob;
    }

    public void setPobName(String pobName) {
        this.pobName = pobName;
    }

    public String getPobName() {
        return this.pobName;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmail() {
        return this.email;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    public String getNationality() {
        return this.nationality;
    }

    public void setNation(String nation) {
        this.nation = nation;
    }

    public String getNation() {
        return this.nation;
    }

    public void setEducational(String educational) {
        this.educational = educational;
    }

    public String getEducational() {
        return this.educational;
    }

    public void setCarrerCurrent(String carrerCurrent) {
        this.carrerCurrent = carrerCurrent;
    }

    public String getCarrerCurrent() {
        return this.carrerCurrent;
    }

    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    public String getMaritalStatus() {
        return this.maritalStatus;
    }

    public void setTaxCode(String taxCode) {
        this.taxCode = taxCode;
    }

    public String getTaxCode() {
        return this.taxCode;
    }

    public void setPermanentAddress(String permanentAddress) {
        this.permanentAddress = permanentAddress;
    }

    public String getPermanentAddress() {
        return this.permanentAddress;
    }

    public void setPermanentNest(String permanentNest) {
        this.permanentNest = permanentNest;
    }

    public String getPermanentNest() {
        return this.permanentNest;
    }

    public void setPermanentProvince(String permanentProvince) {
        this.permanentProvince = permanentProvince;
    }

    public String getPermanentProvince() {
        return this.permanentProvince;
    }

    public void setPermanentProvinceName(String permanentProvinceName) {
        this.permanentProvinceName = permanentProvinceName;
    }

    public String getPermanentProvinceName() {
        return this.permanentProvinceName;
    }

    public void setPermanentDistrict(String permanentDistrict) {
        this.permanentDistrict = permanentDistrict;
    }

    public String getPermanentDistrict() {
        return this.permanentDistrict;
    }

    public void setPermanentDistrictName(String permanentDistrictName) {
        this.permanentDistrictName = permanentDistrictName;
    }

    public String getPermanentDistrictName() {
        return this.permanentDistrictName;
    }

    public void setPermanentWard(String permanentWard) {
        this.permanentWard = permanentWard;
    }

    public String getPermanentWard() {
        return this.permanentWard;
    }

    public void setPermanentWardName(String permanentWardName) {
        this.permanentWardName = permanentWardName;
    }

    public String getPermanentWardName() {
        return this.permanentWardName;
    }

    public void setSameAddress(Byte sameAddress) {
        this.sameAddress = sameAddress;
    }

    public Byte getSameAddress() {
        return this.sameAddress;
    }

    public void setCurrentAddress(String currentAddress) {
        this.currentAddress = currentAddress;
    }

    public String getCurrentAddress() {
        return this.currentAddress;
    }

    public void setCurrentNest(String currentNest) {
        this.currentNest = currentNest;
    }

    public String getCurrentNest() {
        return this.currentNest;
    }

    public void setCurrentProvince(String currentProvince) {
        this.currentProvince = currentProvince;
    }

    public String getCurrentProvince() {
        return this.currentProvince;
    }

    public void setCurrentProvinceName(String currentProvinceName) {
        this.currentProvinceName = currentProvinceName;
    }

    public String getCurrentProvinceName() {
        return this.currentProvinceName;
    }

    public void setCurrentDistrict(String currentDistrict) {
        this.currentDistrict = currentDistrict;
    }

    public String getCurrentDistrict() {
        return this.currentDistrict;
    }

    public void setCurrentDistrictName(String currentDistrictName) {
        this.currentDistrictName = currentDistrictName;
    }

    public String getCurrentDistrictName() {
        return this.currentDistrictName;
    }

    public void setCurrentWard(String currentWard) {
        this.currentWard = currentWard;
    }

    public String getCurrentWard() {
        return this.currentWard;
    }

    public void setCurrentWardName(String currentWardName) {
        this.currentWardName = currentWardName;
    }

    public String getCurrentWardName() {
        return this.currentWardName;
    }

    public void setContactFullName(String contactFullName) {
        this.contactFullName = contactFullName;
    }

    public String getContactFullName() {
        return this.contactFullName;
    }

    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    public String getContactPhone() {
        return this.contactPhone;
    }

    public void setContactRelationship(String contactRelationship) {
        this.contactRelationship = contactRelationship;
    }

    public String getContactRelationship() {
        return this.contactRelationship;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    public String getAccountName() {
        return this.accountName;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    public String getAccountNumber() {
        return this.accountNumber;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    public String getBankName() {
        return this.bankName;
    }

    public void setBankProvince(String bankProvince) {
        this.bankProvince = bankProvince;
    }

    public String getBankProvince() {
        return this.bankProvince;
    }

    public void setBankBranch(String bankBranch) {
        this.bankBranch = bankBranch;
    }

    public String getBankBranch() {
        return this.bankBranch;
    }

    public void setBankBranchName(String bankBranchName) {
        this.bankBranchName = bankBranchName;
    }

    public String getBankBranchName() {
        return this.bankBranchName;
    }

    public void setClassType(String classType) {
        this.classType = classType;
    }

    public String getClassType() {
        return this.classType;
    }

    public void setOnlineOffline(String onlineOffline) {
        this.onlineOffline = onlineOffline;
    }

    public String getOnlineOffline() {
        return this.onlineOffline;
    }

    public void setClassProvince(String classProvince) {
        this.classProvince = classProvince;
    }

    public String getClassProvince() {
        return this.classProvince;
    }

    public void setClassProvinceName(String classProvinceName) {
        this.classProvinceName = classProvinceName;
    }

    public String getClassProvinceName() {
        return this.classProvinceName;
    }

    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }

    public String getClassCode() {
        return this.classCode;
    }

    public void setClassPlace(String classPlace) {
        this.classPlace = classPlace;
    }

    public String getClassPlace() {
        return this.classPlace;
    }

    public void setBeginningDate(Date beginningDate) {
        this.beginningDate = beginningDate;
    }

    public Date getBeginningDate() {
        return this.beginningDate;
    }

    public void setCompletedDate(Date completedDate) {
        this.completedDate = completedDate;
    }

    public Date getCompletedDate() {
        return this.completedDate;
    }

    public void setExamPlace(String examPlace) {
        this.examPlace = examPlace;
    }

    public String getExamPlace() {
        return this.examPlace;
    }

    public void setExamDate(Date examDate) {
        this.examDate = examDate;
    }

    public Date getExamDate() {
        return this.examDate;
    }

    public void setFirstClassDate(Date firstClassDate) {
        this.firstClassDate = firstClassDate;
    }

    public Date getFirstClassDate() {
        return this.firstClassDate;
    }

    public void setClassNote(String classNote) {
        this.classNote = classNote;
    }

    public String getClassNote() {
        return this.classNote;
    }

    public void setRecruiterType(Byte recruiterType) {
        this.recruiterType = recruiterType;
    }

    public Byte getRecruiterType() {
        return this.recruiterType;
    }

    public void setRecruiterCode(Long recruiterCode) {
        this.recruiterCode = recruiterCode;
    }

    public Long getRecruiterCode() {
        return this.recruiterCode;
    }

    public void setRecruiterIdNo(String recruiterIdNo) {
        this.recruiterIdNo = recruiterIdNo;
    }

    public String getRecruiterIdNo() {
        return this.recruiterIdNo;
    }

    public void setRecruiterName(String recruiterName) {
        this.recruiterName = recruiterName;
    }

    public String getRecruiterName() {
        return this.recruiterName;
    }

    public void setRecruiterAdCode(Long recruiterAdCode) {
        this.recruiterAdCode = recruiterAdCode;
    }

    public Long getRecruiterAdCode() {
        return this.recruiterAdCode;
    }

    public void setRecruiterAdName(String recruiterAdName) {
        this.recruiterAdName = recruiterAdName;
    }

    public String getRecruiterAdName() {
        return this.recruiterAdName;
    }

    public void setRecruiterPosition(String recruiterPosition) {
        this.recruiterPosition = recruiterPosition;
    }

    public String getRecruiterPosition() {
        return this.recruiterPosition;
    }

    public void setManagerType(Byte managerType) {
        this.managerType = managerType;
    }

    public Byte getManagerType() {
        return this.managerType;
    }

    public void setManagerCode(Long managerCode) {
        this.managerCode = managerCode;
    }

    public Long getManagerCode() {
        return this.managerCode;
    }

    public void setManagerIdNo(String managerIdNo) {
        this.managerIdNo = managerIdNo;
    }

    public String getManagerIdNo() {
        return this.managerIdNo;
    }

    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }

    public String getManagerName() {
        return this.managerName;
    }

    public void setManagerAdCode(Long managerAdCode) {
        this.managerAdCode = managerAdCode;
    }

    public Long getManagerAdCode() {
        return this.managerAdCode;
    }

    public void setManagerAdName(String managerAdName) {
        this.managerAdName = managerAdName;
    }

    public String getManagerAdName() {
        return this.managerAdName;
    }

    public void setManagerPosition(String managerPosition) {
        this.managerPosition = managerPosition;
    }

    public String getManagerPosition() {
        return this.managerPosition;
    }

    public void setManagerIndirectType(Byte managerIndirectType) {
        this.managerIndirectType = managerIndirectType;
    }

    public Byte getManagerIndirectType() {
        return this.managerIndirectType;
    }

    public void setManagerIndirectCode(Long managerIndirectCode) {
        this.managerIndirectCode = managerIndirectCode;
    }

    public Long getManagerIndirectCode() {
        return this.managerIndirectCode;
    }

    public void setManagerIndirectIdNo(String managerIndirectIdNo) {
        this.managerIndirectIdNo = managerIndirectIdNo;
    }

    public String getManagerIndirectIdNo() {
        return this.managerIndirectIdNo;
    }

    public void setManagerIndirectName(String managerIndirectName) {
        this.managerIndirectName = managerIndirectName;
    }

    public String getManagerIndirectName() {
        return this.managerIndirectName;
    }

    public void setManagerIndirectAdCode(Long managerIndirectAdCode) {
        this.managerIndirectAdCode = managerIndirectAdCode;
    }

    public Long getManagerIndirectAdCode() {
        return this.managerIndirectAdCode;
    }

    public void setManagerIndirectAdName(String managerIndirectAdName) {
        this.managerIndirectAdName = managerIndirectAdName;
    }

    public String getManagerIndirectAdName() {
        return this.managerIndirectAdName;
    }

    public void setManagerIndirectPosition(String managerIndirectPosition) {
        this.managerIndirectPosition = managerIndirectPosition;
    }

    public String getManagerIndirectPosition() {
        return this.managerIndirectPosition;
    }

    public void setCheckEkycStatus(Byte checkEkycStatus) {
        this.checkEkycStatus = checkEkycStatus;
    }

    public Byte getCheckEkycStatus() {
        return this.checkEkycStatus;
    }

    public void setEkycOption(Byte ekycOption) {
        this.ekycOption = ekycOption;
    }

    public Byte getEkycOption() {
        return this.ekycOption;
    }

    public void setEkycSendMailTime(Date ekycSendMailTime) {
        this.ekycSendMailTime = ekycSendMailTime;
    }

    public Date getEkycSendMailTime() {
        return this.ekycSendMailTime;
    }

    public void setEkycResult(Byte ekycResult) {
        this.ekycResult = ekycResult;
    }

    public Byte getEkycResult() {
        return this.ekycResult;
    }

    public void setEkycStatus(String ekycStatus) {
        this.ekycStatus = ekycStatus;
    }

    public String getEkycStatus() {
        return this.ekycStatus;
    }

    public void setCheckInterviewStatus(Byte checkInterviewStatus) {
        this.checkInterviewStatus = checkInterviewStatus;
    }

    public Byte getCheckInterviewStatus() {
        return this.checkInterviewStatus;
    }

    public void setInterviewSendMailTime(Date interviewSendMailTime) {
        this.interviewSendMailTime = interviewSendMailTime;
    }

    public Date getInterviewSendMailTime() {
        return this.interviewSendMailTime;
    }

    public void setInterviewComment(Byte interviewComment) {
        this.interviewComment = interviewComment;
    }

    public Byte getInterviewComment() {
        return this.interviewComment;
    }

    public void setInterviewPoint(String interviewPoint) {
        this.interviewPoint = interviewPoint;
    }

    public String getInterviewPoint() {
        return this.interviewPoint;
    }

    public void setInterviewStatus(String interviewStatus) {
        this.interviewStatus = interviewStatus;
    }

    public String getInterviewStatus() {
        return this.interviewStatus;
    }

    public void setAvicadStatus(String avicadStatus) {
        this.avicadStatus = avicadStatus;
    }

    public String getAvicadStatus() {
        return this.avicadStatus;
    }

    public void setCheckAvicadStatus(Byte checkAvicadStatus) {
        this.checkAvicadStatus = checkAvicadStatus;
    }

    public Byte getCheckAvicadStatus() {
        return this.checkAvicadStatus;
    }

    public void setRefAttachement(String refAttachement) {
        this.refAttachement = refAttachement;
    }

    public String getRefAttachement() {
        return this.refAttachement;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Long getCompanyId() {
        return this.companyId;
    }

    public void setFormId(Long formId) {
        this.formId = formId;
    }

    public Long getFormId() {
        return this.formId;
    }

    public void setDocUuid(String docUuid) {
        this.docUuid = docUuid;
    }

    public String getDocUuid() {
        return this.docUuid;
    }

    public void setFormStatus(String formStatus) {
        this.formStatus = formStatus;
    }

    public String getFormStatus() {
        return this.formStatus;
    }

    public void setVersionData(byte[] versionData) {
        this.versionData = versionData;
    }

    public byte[] getVersionData() {
        return this.versionData;
    }

    public void setFieldUser1(String fieldUser1) {
        this.fieldUser1 = fieldUser1;
    }

    public String getFieldUser1() {
        return this.fieldUser1;
    }

    public void setFieldUser2(String fieldUser2) {
        this.fieldUser2 = fieldUser2;
    }

    public String getFieldUser2() {
        return this.fieldUser2;
    }

    public void setFieldUser3(String fieldUser3) {
        this.fieldUser3 = fieldUser3;
    }

    public String getFieldUser3() {
        return this.fieldUser3;
    }

    public void setFieldUser4(String fieldUser4) {
        this.fieldUser4 = fieldUser4;
    }

    public String getFieldUser4() {
        return this.fieldUser4;
    }

    public void setFieldUser5(String fieldUser5) {
        this.fieldUser5 = fieldUser5;
    }

    public String getFieldUser5() {
        return this.fieldUser5;
    }

}
