select CATE.ID AS ID
, CATE.CODE AS CODE
, LANG.TITLE AS LABEL
from M_FAQS_CATEGORY CATE
INNER JOIN M_FAQS_CATEGORY_LANGUAGE LANG
ON(CATE.ID = LANG.M_FAQS_CATEGORY_ID)
WHERE CATE.DELETE_DATE IS NULL
AND LANG.M_LANGUAGE_CODE = UPPER(/*language*/'VI')
AND CATE.M_FAQS_CATEROTY_PARENT_ID = 1
/*IF modeView == 0*/
AND CATE.ENABLED = 1
/*END*/
ORDER BY CATE.SORT ASC 
