# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
logging:
  level:
    ROOT: ERROR
    vn.com.unit: ERROR
    vn.com.unit.cms: ERROR
    jp.sf.amateras.mirage: DEBUG
  file:
    clean-history-on-start: false
    total-size-cap: 20GB
    max-size: 100MB
    max-history: 30
    path: ${jboss.server.log.dir}
    name: dsuccess-admin.log

spring:
  profiles:
    active: dev
  jackson:
    serialization:
      indent-output: true
  datasource:
    jndi-name: java:/datasources/MSSQLDS
  datasource-db2:
    jndi-name: java:/datasources/DB2DS
  datasource-dblog:
    jndi-name: java:/datasources/MSSQLLOG
  thymeleaf:
    cache: false
    
  # activiti default configuration
  activiti:
    database-schema-update: true
    check-process-definitions: false
# process-definition-location-prefix: classpath:/processes/
# process-definition-location-suffixes:
# - **.bpmn
# - **.bpmn20.xml
    history-level: audit
    async-executor-activate: false
    
jcanary:
  # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
#    allow-credentials: true
    max-age: 1800
    
#   FIX CORS
    allow-credentials: false
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: NzRlNWU5Y2VkNTRhMmVmZDAwMjNlMjE5Mjk0NjFkZjA0MDdlZjU5MGJkYzU5ZTRmZmJmMzIwYWIyOTEwZjNhOThhOGQ1OWY3YTkwN2MyNGVjMThkNGJiMDQ5Y2I0NjM1ZWMxNWNhZThmODExMzRiMTY4Nzk1YzY0OWFkNjJiMTk=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000

server:
  port: 8081
  
app:
  firebase-configuration-file: daiichi-success-firebase-adminsdk.json
  
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: "*"
      cors:
        allowed-methods: "GET,POST"
    jmx:
      exposure:
        include: "*"
  
  health:
    db:
      enabled: true
    jms:
      enabled: true
    
  metrics:
    export:
      # Prometheus is the default metrics backend
      prometheus:
        enabled: true
        step: 60
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    web:
      server:
        request:
          autotime:
            enabled: true

            

            #jca-quartz
jca-quartz:
  config:
    overwrite-existing-jobs: true
    scheduler-name: DSUCCESS_WEBAPP
    wait-for-jobs-to-complete-on-shutdown: true
    auto-startup: true