SELECT
		tb.id				AS ID
   	 , tb.MEMO_NO         AS MEMO_NO
	 , tb.AGENT_CODE		AS AGENT_CODE
	 , tb.REPORTINGTO_NAME	AS REPORTINGTO_NAME
	 , tb.BM_CODE					AS BM_CODE
	 , tb.GA_CODE					AS GA_CODE
	 , tb.GAD_CODE				AS GAD_CODE
	 , tb.BDOH_CODE				AS BDOH_CODE
	 , tb.BDRH_CODE				AS BDRH_CODE
	 , tb.BDAH_CODE				AS BDAH_CODE
	 , tb.BDTH_CDE				AS BDTH_CDE
	 , tb.POLICY_NO				AS POLICY_NO
	 , tb.APPLIED_DATE		AS APPLIED_DATE
	 , tb.ISSUED_DATE			AS ISSUED_DATE
	 , tb.RESULT					AS RESULT
	 , tb.BONUS						AS BONUS
	 , tb.CLAWBACK				AS CLAWBACK
	 , tb.NOTE						AS NOTE
   , tbl.CREATED_DATE AS CREATED_DATE
   , tbl.CREATED_BY	 AS CREATED_BY
FROM M_CONTEST_DETAIL tb
LEFT JOIN M_CONTEST_SUMMARY tbl
ON tb.MEMO_NO = tbl.MEMO_NO
WHERE 
		tb.DELETED_BY is null
AND      tbl.DELETED_BY is null

AND tb.MEMO_NO = /*memo*/'CONT2111.0035'
