SELECT 
	ROW_NUMBER ()  OVER ( ORDER BY DEM.ID ASC )   as no
  ,	DEM.ID									AS ID
 , DEM.CODE 				AS CODE
 , DEM.MEMO_NO 				AS MEMO_NO
 , DEM.CONTEST_NAME 			AS CONTEST_NAME
 , DEM.KEYWORDS_SEO				AS KEYWORDS_SEO
 , DEM.KEYWORDS						AS KEYWORDS
 , DEM.KEYWORDS_DESC			AS KEYWORDS_DESC
 , DEM.DESCRIPTION				AS DESCRIPTION
 , DEM.CONTEST_TYPE				AS CONTEST_TYPE
 , DEM.CONTEST_PHYSICAL_IMT	 AS CONTEST_PHYSICAL_IMT
 , DEM.CONTEST_PHYSICAL_FILE AS CONTEST_PHYSICAL_FILE
 , DEM.IS_HOT							AS IS_HOT
 , DEM.IS_CHALLENGE				AS IS_CHALLENGE
 , DEM.ENABLED					AS ENABLED
 , DEM.IS_ODS							AS IS_ODS
 , DEM.START_DATE					AS START_DATE
 , DEM.END_DATE						AS END_DATE
 , DEM.EFFECTIVE_DATE			AS EFFECTIVE_DATE
 , DEM.EXPIRED_DATE				AS EXPIRED_DATE
 , DEM.APPLICABLE_OBJECT	AS APPLICABLE_OBJECT
 , DEM.AGENT_NAME					AS AGENT_NAME
 , DEM.AREA								AS AREA
 , DEM.TERRITORY					AS TERRITORY
 , DEM.REGION							AS REGION
 , DEM.OFFICE							AS OFFICE
 , DEM.[POSITION]				  AS [POSITION]
 , DEM.IS_PERSON					AS IS_PERSON
 , DEM.REPORTINGTO_NAME		AS REPORTINGTO_NAME
 , DEM.NOTE								AS NOTE
 , dem.MESSAGE_ERROR			AS MESSAGE_ERROR
 , dem.IS_ERROR								AS IS_ERROR
FROM M_CONTEST_SUMMARY_IMPORT DEM
WHERE
        1 = 1
  AND DEM.SESSION_KEY = /*sessionKey*/'20213910053912522'
ORDER BY DEM.IS_ERROR DESC, DEM.ID ASC
