
SELECT 
 DEM.* 
FROM M_CONTEST_DETAIL_IMPORT DEM
WHERE
    1 = 1
    AND DEM.SESSION_KEY = /*sessionKey*/'20214704054756140'
ORDER BY DEM.IS_ERROR DESC, DEM.ID ASC
OFFSET /*offset*/0 ROWS FETCH NEXT /*sizeOfPage*/20 ROWS ONLY