SELECT COUNT(1)
FROM M_INVESTOR_CATEGORY cate
WHERE cate.DELETE_DATE IS NULL
	AND cate.ID = /*id*/100120
	AND (
		EXISTS (
			SELECT 1
			FROM M_INVESTOR_CATEGORY cateChild
			WHERE cateChild.DELETE_DATE IS NULL
			  AND cateChild.STATUS <> 1
			  AND cateChild.STATUS <> 100
			  AND cateChild.INVESTOR_CATEGORY_PARENT_ID = cate.ID
		)
		OR EXISTS (
			SELECT 1 
			FROM M_INVESTOR
			WHERE DELETE_DATE IS NULL
			  AND STATUS <> 1
			  AND STATUS <> 100
			  AND M_INVESTOR_CATEGORY_ID = cate.ID
		)
	)
;