SELECT 
    DEM.* 
FROM M_AGENT_NOTIFY_IMPORT DEM
WHERE
    1 = 1
    AND DEM.SESSION_KEY = /*sessionKey*/'20201919041906624'
ORDER BY DEM.IS_ERROR DESC, DEM.ID ASC
OFFSET /*offset*/0 ROWS FETCH NEXT /*sizeOfPage*/20 ROWS ONLY