SELECT
    DEM.*, ROW_NUMBER() OVER(ORDER BY DEM.IS_ERROR DESC, DEM.ID asc)												AS	NO
FROM M_AGENT_NOTIFY_IMPORT DEM
WHERE
    1 = 1
    AND DEM.SESSION_KEY = /*sessionKey*/
ORDER BY DEM.IS_ERROR DESC, DEM.ID ASC