SELECT  (TBL_MAIN.ID || '@' || TBL_MAIN.SORT) AS ID,
		TBL_LANG.TITLE AS NAME,
		TBL_LANG.TITLE AS TEXT

FROM M_PRODUCT_CATEGORY TBL_MAIN

JOIN 	M_PRODUCT_CATEGORY_LANGUAGE TBL_LANG

ON 		TBL_MAIN.ID = TBL_LANG.M_PRODUCT_CATEGORY_ID

WHERE 
	TBL_MAIN.DELETE_DATE IS NULL
	
	AND TBL_MAIN.ENABLED = 1
	
	AND TBL_MAIN.M_CUSTOMER_ID = /*customerId*/9
	
	AND TBL_LANG.M_LANGUAGE_CODE = /*languageCode*/'VI'
	
	AND (TBL_LANG.TITLE LIKE ('%'|| UPPER(/*term*/'') || '%') 

ORDER BY TBL_MAIN.SORT 
OFFSET 0 ROWS FETCH NEXT 20 ROWS ONLY;