SELECT 	TBL_MAIN.*
       
FROM 	M_PRODUCT_CATEGORY_SUB TBL_MAIN

JOIN 	M_PRODUCT_CATEGORY_SUB_LANGUAGE TBL_LANG

ON 		TBL_MAIN.ID = TBL_LANG.M_PRODUCT_CATEGORY_SUB_ID

WHERE   TBL_MAIN.DELETE_DATE IS NULL

		AND TBL_MAIN.ENABLED = 1

        AND TBL_LANG.M_LANGUAGE_CODE = UPPER(/*languageCode*/'VI')
        
        AND TBL_MAIN.M_CUSTOMER_TYPE_ID = /*customerTypeId*/9
        
        /*IF productTypeId != null*/
		AND TBL_MAIN.M_PRODUCT_CATEGORY_ID = /*productTypeId*/
		/*END*/
		        
        /*IF id != null*/
        AND TBL_MAIN.ID != /*id*/
        /*END*/
ORDER BY TBL_MAIN.SORT ASC