SELECT 	TBL_MAIN.ID,
       	TBL_LANG.TITLE AS name,
       	TBL_MAIN.SORT
       
FROM 	M_PRODUCT_CATEGORY TBL_MAIN

JOIN 	M_PRODUCT_CATEGORY_LANGUAGE TBL_LANG

ON 		TBL_MAIN.ID = TBL_LANG.M_PRODUCT_CATEGORY_ID

WHERE   TBL_MAIN.DELETE_DATE IS NULL

		AND TBL_MAIN.ENABLED = 1

        AND TBL_LANG.M_LANGUAGE_CODE = UPPER(/*languageCode*/'')
        
        AND TBL_MAIN.M_CUSTOMER_TYPE_ID = /*categoryEdit.customerTypeId*/
        
        /*IF categoryEdit.id != null*/
        AND TBL_MAIN.ID != /*categoryEdit.id*/
        /*END*/
ORDER BY TBL_LANG.TITLE ASC, TBL_MAIN.SORT ASC