INSERT INTO dbo.M_NOTIFYS_APPLICABLE_DETAIL (NOTIFY_ID
	, TERRITORRY
	, AREA
	, REGION
	, OFFICE
	, POSITION
	, AGENT_CODE
	, IS_READ_ALREADY
	, AGENT_NAME
	, CREATE_DATE)
SELECT /*notifyId*/2871
	, TERRITORRY
	, AREA
	, REGION
	, OFFICE
	, POSITION
	, AGENT_CODE
	, 0
	, NAME
	, GETDATE()
FROM M_EVENTS_APPLICABLE_DETAIL
WHERE EVENT_ID = /*eventId*/182
and AGENT_CODE is not null