INSERT INTO dbo.M_NOTIFYS_APPLICABLE_DETAIL (NOTIFY_ID
	, TERRITORRY
	, AREA
	, REGION
	, OFFICE
	, POSITION
	, AGENT_CODE
	, IS_READ_ALREADY
	, AGENT_NAME
	, CREATE_DATE)
SELECT /*notifyId*/2871
	, TERRITORRY
	, AREA
	, REGION
	, OFFICE
	, POSITION
	, case when GUEST_TYPE = '1' then AGENT_CODE else ID_NUMBER end
	, 0
	, NAME
	, GETDATE()
FROM M_EVENTS_APPLICABLE_DETAIL
WHERE EVENT_ID = /*eventId*/182
and ((GUEST_TYPE = '1' and AGENT_CODE in /*agentCodes*/())
	or (GUEST_TYPE = '3' and ID_NUMBER in /*agentCodes*/()))