SELECT  ID                  		AS ID
		,ALERT_TYPE				AS ALERT_TYPE
		,ALERT_DATE				AS ALERT_DATE
		,NOTI_TITLE				AS NOTI_TITLE
		,NOTI_DESCRIPTION			AS NOTI_DESCRIPTION
		,EMAIL_CONTENT			AS EMAIL_CONTENT
		,EMAIL_SUBJECT			AS EMAIL_SUBJECT
		,JSON_DATA				AS JSON_DATA
		,EMAIL_TO					AS EMAIL_TO
		,EMAIL_CC					AS EMAIL_CC
		,EMAIL_BCC				AS EMAIL_BCC
		,USER_NOTI				AS USER_NOTI
		,STATUS					AS STATUS
		,COUNT_SENDING_ERROR		AS COUNT_SENDING_ERROR
FROM SLA_ALERT ALERT
WHERE ID = /*id*/