SELECT  ID                  				AS ID
		,CALENDAR_TYPE_ID					AS CALENDAR_TYPE_ID
		,ALERT_TYPE							AS ALERT_TYPE
		,ALERT_TIME							AS ALERT_TIME
		,UNIT_TIME							AS UNIT_TIME
FROM SLA_CONFIG
WHERE ID = /*id*/