SELECT  ID                  			AS ID
		,CODE							AS ALERT_TYPE
		,NAME							AS NAME
		,DESCRIPTION					AS DESCRIPTION
		,START_MORNING_TIME				AS START_MORNING_TIME
		,END_MORNING_TIME				AS END_MORNING_TIME
		,START_AFTERNOON_TIME			AS START_AFTERNOON_TIME
		,END_AFTERNOON_TIME				AS END_AFTERNOON_TIME
FROM SLA_CALENDAR_TYPE
WHERE ID = /*id*/