SELECT  ID                  					AS ID
		,DAYOFFDATE								AS DAYOFFDATE
		,CALENDAR_TYPE_ID						AS CALENDAR_TYPE_ID
		,DESCRIPTION							AS DESCRIPTION
		,DAYOFF_TYPE							AS DAYOFF_TYPE
FROM SLA_DAY_OFF
WHERE ID = /*id*/