/*
 * Created on 2020-07-02 ( Date ISO 2020-07-02 - Time 08:55:53 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package vn.com.unit.cms.admin.all.enumdef.imports;

public enum EmulateResultImportEnum {
	  NO("0")
	, MEMONO("1")
	, AGENTCODE("2")
	, REPORTINGTOCODE("3")
	, BMCODE("4")
	, GADCODE("5")
	, GACODE("6")
	, BDOHCODE("7")
	, BDRHCODE("8")
	, BDAHCODE("9")
	, BDTHCDE("10")
	, POLICYNO("11")
	, APPLIEDDATE("12")
	, ISSUEDDATE("13")
	, RESULT("14")
	, ADVANCE("15")
	, BONUS("16")
	, CLAWBACK("17")
	, NOTE("18")
	, MESSAGEERROR("19");
    private String value;
    
    private EmulateResultImportEnum(String value){
        this.value = value;
    }
    
    public String toString (){
        return value;
    }
}
