/*
 * Created on 2020-07-02 ( Date ISO 2020-07-02 - Time 08:55:53 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package vn.com.unit.cms.admin.all.enumdef.imports;

public enum NotifyImportEnum {
	no("0"),
   AGENTCODE("1"),
   TITLE("2"),
   CONTENT("3"),
   messageerror("4"),
;
    private String value;

    private NotifyImportEnum(String value){
        this.value = value;
    }
    
    public String toString (){
        return value;
    }
}
