SELECT DISTINCT 
    REGION_MANAGER_CODE                                     AS  ID
    , REGION_MANAGER_NAME                                   AS  NAME
    , CONCAT(REGION_MANAGER_CODE, ' - ', REGION_MANAGER_NAME  )     AS  TEXT
FROM ERS_BANCAS_STRUCTURE
GROUP BY REGION_MANAGER_CODE, REGION_MANAGER_NAME
UNION ALL 
SELECT DISTINCT 
    AREA_MANAGER_CODE                               AS  ID
    , AREA_MANAGER_NAME                             AS  NAME
    , CONCAT(AREA_MANAGER_CODE , ' - ', AREA_MANAGER_NAME  )     AS  TEXT
FROM ERS_BANCAS_STRUCTURE
GROUP BY AREA_MANAGER_CODE, AREA_MANAGER_NAME