SELECT DISTINCT 
    REGION_MANAGER_CODE                                     AS  ID
    , REGION_MANAGER_NAME                                   AS  NAME
    , CONCAT(REGION_NAME, ' - ', REGION_MANAGER_NAME  )     AS  TEXT
FROM ERS_BANCAS_STRUCTURE
GROUP BY REGION_NAME, REGION_MANAGER_CODE, REGION_MANAGER_NAME