SELECT 
	cat.ID 				as CATEGORY_ID
	,cat.COMPANY_ID 	as COMPANY_ID
	,cat.NAME 			as CATEGORY_NAME
	,cat.DESCRIPTION 	as DESCRIPTION
	,cat.DISPLAY_ORDER 	as DISPLAY_ORDER
	,cat.ACTIVED 	as ACTIVED
FROM
  	EFO_CATEGORY cat
WHERE
  	cat.DELETED_ID IS  NULL
	AND cat.ID = /*id*/
