SELECT
	doc.*
	, mainFile.ID					AS MAIN_FILE_ID
	, mainFile.MAJOR_VERSION		AS MAIN_FILE_MAJOR_VERSION
	, mainFile.MINOR_VERSION		AS MAIN_FILE_MINOR_VERSION
FROM
	EFO_DOC doc
LEFT JOIN
	EFO_OZ_DOC_MAIN_FILE mainFile
ON 
	mainFile.DOC_ID = doc.ID AND mainFile.DELETED_ID = 0
WHERE 
	doc.ID = /*id*/0
	AND doc.DELETED_ID = 0