SELECT  
	 form.ID            	AS   FORM_ID
	,form.COMPANY_ID    	AS   COMPANY_ID
	,form.CATEGORY_ID   	AS   CATEGORY_ID
	,bus.BUSINESS_CODE 	    AS   BUSINESS_CODE
	,form.NAME          	AS   FORM_NAME
	,form.DESCRIPTION   	AS   DESCRIPTION
	,form.ICON_FILE_PATH    AS   ICON_FILE_PATH
	,form.ICON_REPO_ID 	    AS   ICON_REPO_ID
	,form.DISPLAY_ORDER 	AS   DISPLAY_ORDER
	,form.DEVICE_TYPE   	AS   DEVICE_TYPE
	,form.ACTIVED   		AS   ACTIVED
	,form.BUSINESS_ID		AS	 BUSINESS_ID
	,form.FORM_TYPE			AS   FORM_TYPE
	,form.OZ_FILE_PATH		AS	 OZ_FILE_PATH
	,form.OZ_FILE_PATH		AS	 FILE_NAME
	,form.CREATED_DATE      AS   CREATED_DATE
	,catel.NAME				AS   CATEGORY_NAME
	,bus.BUSINESS_NAME		AS   BUSINESS_NAME
	,acc.FULLNAME			AS   CREATED_NAME

FROM
	EFO_FORM form
LEFT JOIN
	EFO_CATEGORY cate
ON
	form.CATEGORY_ID = cate.ID
LEFT JOIN
	EFO_CATEGORY_LANG catel
ON
	cate.ID = catel.category_id
    AND Upper(catel.lang_code) = Upper('en')
LEFT JOIN
	JPM_BUSINESS bus
ON
	form.BUSINESS_ID = bus.ID
LEFT JOIN
	JCA_ACCOUNT acc
ON
	form.CREATED_ID = acc.ID
WHERE 
	form.DELETED_ID = 0
	AND form.ID  = /*id*/1