SELECT 
		ID
		,DOC_ID
		,FORM_FILE_NAME
		,FILE_NAME
		,FILE_NAME_PDF
		,FILE_NAME_VIEW
		,REPOSITORY_ID
		,DOC_INPUT_JSON
		,MAJOR_VERSION
		,MINOR_VERSION
		,FORM_ID
		,PDF_MAJOR_VERSION
		,PDF_MINOR_VERSION
		,SIGN_STATUS
		,SIGN_BY_ACCOUNT_ID
		,TOTAL_FAIL
		,VALID_JSON
		,PDF_TYPE_SIZE
		,HISTORY_FILE_NAME
		,LATEST_UPLOAD_DATE
		,CREATED_DATE
		,CREATED_ID
		,UPDATED_DATE
		,UPDATED_ID
		,DELETED_DATE
		,DELETED_ID
		,PDF_REPOSITORY_ID
FROM EFO_OZ_DOC_MAIN_FILE
WHERE DELETED_ID = 0
AND DOC_ID = /*docId*/1
