SELECT 
	mainFile.ID 					AS ID
	, mainFile.DOC_ID   			AS DOC_ID
	, mainFile.FORM_ID				AS FORM_ID
	, hiMainFile.DOC_INPUT_JSON		AS DOC_INPUT_JSON
	, hiMainFile.REPOSITORY_ID 		AS REPOSITORY_ID
	, hiMainFile.FORM_FILE_NAME 	AS FORM_FILE_NAME
	, hiMainFile.MAJOR_VERSION		AS MAJOR_VERSION
	, hiMainFile.MINOR_VERSION		AS MINOR_VERSION
	, hiMainFile.FILE_NAME_PDF 		AS FILE_NAME_PDF
	, hiMainFile.FILE_NAME 			AS FILE_NAME
	, hiMainFile.FILE_NAME_VIEW		AS FILE_NAME_VIEW
	, hiMainFile.ID					AS HISTORY_ID
	, hiMainFile.PDF_MAJOR_VERSION	AS PDF_MAJOR_VERSION
	, hiMainFile.PDF_MINOR_VERSION	AS PDF_MINOR_VERSION
	, doc.COMPANY_ID				AS COMPANY_ID
	, mainFile.PDF_REPOSITORY_ID    AS PDF_REPOSITORY_ID
FROM
	EFO_OZ_DOC_MAIN_FILE_VERSION hiMainFile
LEFT JOIN
	EFO_OZ_DOC_MAIN_FILE mainFile
ON
	hiMainFile.MAIN_FILE_ID = mainFile.ID AND mainFile.DELETED_ID = 0
LEFT JOIN
	EFO_OZ_DOC doc
ON
	doc.ID = mainFile.DOC_ID AND doc.DELETED_ID = 0
WHERE
	hiMainFile.ID = /*docMainFileVersionId*/1664
	AND hiMainFile.DELETED_ID = 0