 SELECT 
	 account.FULLNAME			AS CREATED_BY
	, hiMainFile.* 
	, hiMainFile.MAJOR_VERSION,CONCAT('.',hiMainFile.MINOR_VERSION) AS VERSION_FILE_HIS 
FROM EFO_OZ_DOC_MAIN_FILE_VERSION hiMainFile 

LEFT JOIN
	JCA_ACCOUNT account
ON 
	account.ID = hiMainFile.CREATED_ID
LEFT JOIN
	EFO_DOC doc
ON 
	doc.ID = hiMainFile.DOC_ID
WHERE 
	hiMainFile.DELETED_ID = 0
	AND hiMainFile.DOC_ID = /*docId*/4
ORDER BY hiMainFile.CREATED_DATE DESC 