SELECT
	step.ID		          				AS ID
	, step.STEP_NO        				AS STEP_NO
	, stepLang.STEP_NAME   				AS NAME
	, statusLang.STATUS_NAME  			AS STATUS_NAME
	, buttonLang.BUTTON_NAME			AS BUTTON_NAME
	, button.BUTTON_CLASS				AS BUTTON_CLASS
	, buttonStep.OPTION_SAVE_FORM 				AS IS_SAVE
	, buttonStep.OPTION_SAVE_EFORM 				AS IS_SAVE_EFORM
	, buttonStep.OPTION_AUTHENTICATE 	   		AS IS_AUTHENTICATE 
	, buttonStep.OPTION_SHOW_HISTORY 	   		AS DISPLAY_HISTORY_APPROVE
	, buttonStep.OPTION_SIGNED    				AS IS_SIGN 
	, buttonStep.OPTION_FILL_TO_EFORM    		AS FIELD_SIGN 
	, buttonStep.OPTION_EXPORT_PDF		    	AS IS_EXPORT_PDF
    , jFunction.PERMISSION_NAME			AS FUNCTION_NAME
    , step.STATUS_DEPLOY_ID 	  		AS STATUS_ID
    , step.STEP_CODE 		  			AS CODE	
    , step.STEP_TYPE 					AS STEP_TYPE
    , step.COMMON_STATUS_CODE			AS COMMON_STATUS_CODE
    , statusCommonLang.STATUS_NAME		AS COMMON_STATUS_NAME
    , step.STEP_KIND					AS STEP_KIND
    --, step.AUTHORITY_COMMENT		  	AS AUTHORITY_COMMENT
FROM
	JPM_STEP_DEPLOY step
LEFT JOIN
	JPM_STEP_LANG_DEPLOY stepLang
ON
	step.ID = stepLang.STEP_DEPLOY_ID
	AND UPPER(stepLang.LANG_CODE) = UPPER(/*lang*/'VI')
LEFT JOIN
	JPM_STATUS_LANG_DEPLOY statusLang
ON
	statusLang.STATUS_DEPLOY_ID = step.STATUS_DEPLOY_ID
	AND UPPER(statusLang.LANG_CODE) = UPPER(/*lang*/'VI')
LEFT JOIN
	JPM_BUTTON_FOR_STEP_DEPLOY buttonStep
ON
	buttonStep.STEP_DEPLOY_ID = step.ID
LEFT JOIN
	JPM_BUTTON_DEPLOY button
ON
	button.ID = buttonStep.BUTTON_DEPLOY_ID
	AND button.DELETED_ID = 0
LEFT JOIN 
	JPM_BUTTON_LANG_DEPLOY buttonLang
ON
	button.ID = buttonLang.BUTTON_DEPLOY_ID
	AND UPPER(buttonLang.LANG_CODE) = UPPER(/*lang*/'VI')
LEFT JOIN
	JPM_PERMISSION_DEPLOY jFunction
ON
	jFunction.ID = buttonStep.PERMISSION_DEPLOY_ID
LEFT JOIN
	JPM_STATUS_COMMON statusCommon
ON 
	statusCommon.STATUS_CODE = step.COMMON_STATUS_CODE	
LEFT JOIN 
	JPM_STATUS_COMMON_LANG statusCommonLang
ON 
	statusCommon.ID = statusCommonLang.STATUS_COMMON_ID
	AND UPPER(statusCommonLang.LANG_CODE) = UPPER(/*lang*/)
WHERE 
	step.PROCESS_DEPLOY_ID = /*processId*/0
	AND step.DELETED_ID = 0
ORDER BY
	step.STEP_NO
	, button.DISPLAY_ORDER