
SELECT MAIN.ID AS ID
, MAIN.CODE AS CODE
, LANG.NAME AS NAME
FROM JCA_M_REGION_LANGUAGE LANG
INNER JOIN JCA_M_REGION MAIN
ON(MAIN.ID = LANG.M_REGION_ID)
WHERE MAIN.ACTIVE_FLAG = 1
AND MAIN.DELETE_DATE IS NULL
AND LANG.M_LANGUAGE_CODE = UPPER(/*language*/'vi')
AND MAIN.M_COUNTRY_ID = /*counttryId*/''
ORDER BY LANG.NAME ASC
