SELECT DISTRICT.ID AS ID
	, DISTRICT.CODE AS CODE
	, LANG.NAME AS NAME
FROM JCA_M_DISTRICT_LANGUAGE LANG
INNER JOIN JCA_M_DISTRICT DISTRICT
ON(LANG.M_DISTRICT_ID = DISTRICT.ID)
WHERE DISTRICT.ACTIVE_FLAG = 1
AND DISTRICT.DELETE_DATE IS NULL
AND DISTRICT.M_COUNTRY_ID = /*counttryId*/''
AND DISTRICT.M_CITY_ID = /*city*/''
AND LANG.M_LANGUAGE_CODE = UPPER(/*language*/'vi')
ORDER BY LANG.NAME ASC