
SELECT CITY.ID AS ID
	, CITY.CODE AS CODE
	, LANG.NAME AS NAME
FROM JCA_M_CITY_LANGUAGE LANG
INNER JOIN JCA_M_CITY CITY
ON(LANG.M_CITY_ID = CITY.ID)
INNER JOIN JCA_M_REGION REGION
ON(CITY.M_REGION_ID = REGION.ID)
WHERE REGION.ACTIVE_FLAG = 1
AND REGION.DELETE_DATE IS NULL
AND REGION.M_COUNTRY_ID = /*counttryId*/''
AND CITY.M_REGION_ID = /*regionId*/''
AND LANG.M_LANGUAGE_CODE = UPPER(/*language*/'vi')
ORDER BY LANG.NAME ASC