SELECT
	CATEGORY_LANG.LABEL, CATEGORY.ID
FROM M_NEWS_CATEGORY CATEGORY
	INNER JOIN M_NEWS_TYPE M_TYPE
	ON(CATEGORY.M_NEWS_TYPE_ID = M_TYPE.ID)
	JOIN M_NEWS_CATEGORY_LANGUAGE CATEGORY_LANG ON (CATEGORY.ID = CATEGORY_LANG.M_NEWS_CATEGORY_ID AND CATEGORY_LANG.DELETE_DATE IS NULL)
	LEFT JOIN M_CUSTOMER_TYPE_LANGUAGE CUSTOMERTYPE ON (CUSTOMERTYPE.M_CUSTOMER_TYPE_ID = CATEGORY.M_CUSTOMER_TYPE_ID 
											AND CUSTOMERTYPE.M_LANGUAGE_CODE = CATEGORY_LANG.M_LANGUAGE_CODE
											AND CUSTOMERTYPE.DELETE_DATE IS NULL)
WHERE
	CATEGORY.DELETE_DATE IS NULL	
	AND UPPER(CATEGORY_LANG.M_LANGUAGE_CODE) = UPPER('VI')
	AND M_TYPE.CODE = /*pageType*/'NEWS'
	/*IF channel != null && channel != ''*/
	AND isnull(CATEGORY.CHANNEL,'AG') like UPPER('%' + /*channel*/ + '%')
	/*END*/
	/*IF modeView == 0*/
	AND CATEGORY.ENABLED = 1
	/*END*/
	
ORDER BY CATEGORY.SORT ASC