SET NOCOUNT ON;

DROP TABLE IF EXISTS #CATEGORY_NEWS;
SELECT 
 COUNT(news_lang.ID)		AS TOTAL
 , lang_type.M_NEWS_TYPE_ID	AS NEWS_TYPE_ID
 , lang_type.LABEL			AS LABEL
 INTO #CATEGORY_NEWS
FROM M_NEWS_TYPE_LANGUAGE lang_type
INNER JOIN M_NEWS_TYPE TYPE_
ON(lang_type.M_NEWS_TYPE_ID = TYPE_.ID)
LEFT JOIN M_NEWS_CATEGORY cate
ON (cate.M_NEWS_TYPE_ID = lang_type.M_NEWS_TYPE_ID 
	AND lang_type.M_LANGUAGE_CODE = UPPER(/*language*/'VI'))
LEFT JOIN M_NEWS news
ON (cate.ID = news.M_NEWS_CATEGORY_ID 
/*IF modeView == 0*/
	AND news.ENABLED = 1
/*END*/
)
LEFT JOIN M_NEWS_LANGUAGE news_lang
ON (news_lang.M_NEWS_ID = news.ID AND news_lang.M_LANGUAGE_CODE = UPPER(/*language*/'VI')
AND (news_lang.TITLE LIKE CONCAT( '%', CONCAT(/*key*/'dai', '%' ))
	OR news_lang.SHORT_CONTENT LIKE CONCAT( '%', CONCAT(/*key*/'dai', '%' ))
)
AND CONVERT(DATE, news.POSTED_DATE) <= CONVERT(DATE, GETDATE())
	AND CONVERT(DATE, ISNULL(news.EXPIRATION_DATE, GETDATE())) >= CONVERT(DATE, GETDATE()))
WHERE 1 = 1
AND	news.DELETE_BY is null
AND TYPE_.CODE IN ('NEWS','ACTIVITY')
GROUP BY lang_type.M_NEWS_TYPE_ID, lang_type.LABEL;

SELECT * 
FROM #CATEGORY_NEWS
