/*
 * Created on 2021-04-10 ( Date ISO 2021-04-10 - Time 14:11:46 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */
package vn.com.unit.ep2p.core.ers.entity;

import java.util.Date;

import org.springframework.data.annotation.Id;

import jp.sf.amateras.mirage.annotation.Column;
import jp.sf.amateras.mirage.annotation.PrimaryKey;
import jp.sf.amateras.mirage.annotation.PrimaryKey.GenerationType;
import jp.sf.amateras.mirage.annotation.Table;
import jp.sf.amateras.mirage.annotation.Transient;
import lombok.Getter;
import lombok.Setter;

/**
 * Domain class for entity "ErsCandidate"
 *
 * @author TaiTM
 *
 */
@Table(name = "ERS_CANDIDATE")
@Getter
@Setter
public class ErsCandidate {

    @Id
    @PrimaryKey(generationType = GenerationType.SEQUENCE, generator = "SEQ_ERS_CANDIDATE")
    @Column(name = "ID")
    private Long id;

    /** Column: channel VARCHAR(10) */
    @Column(name = "CHANNEL")
    private String channel;

    /** Column: applyForPosition VARCHAR(255) */
    @Column(name = "APPLY_FOR_POSITION")
    private String applyForPosition;

    /** Column: positionName VARCHAR(255) */
    @Column(name = "POSITION_NAME")
    private String positionName;

    /** Column: optionSupport TINYINT(3) */
    @Column(name = "OPTION_SUPPORT")
    private int optionSupport;

    /** Column: regionName VARCHAR(10) */
    @Column(name = "REGION_NAME")
    private String regionName;

    /** Column: provinceName NVARCHAR(255) */
    @Column(name = "PROVINCE_NAME")
    private String provinceName;

    /** Column: agentCode VARCHAR(10) */
    @Column(name = "AGENT_CODE")
    private String agentCode;

    /** Column: bpCode VARCHAR(10) */
    @Column(name = "BP_CODE")
    private String bpCode;

    /** Column: dateAppointed DATE(10) */
    @Column(name = "DATE_APPOINTED")
    private Date dateAppointed;

    /** Column: dateTerminate DATE(10) */
    @Column(name = "DATE_TERMINATE")
    private Date dateTerminate;

    /** Column: agentStatus NVARCHAR(10) */
    @Column(name = "AGENT_STATUS")
    private String agentStatus;

    /** Column: reinsFlag TINYINT(3) */
    @Column(name = "REINS_FLAG")
    private int reinsFlag;

    /** Column: partnerMic NVARCHAR(200) */
    @Column(name = "PARTNER_MIC")
    private String partnerMic;

    /** Column: idType VARCHAR(10) */
    @Column(name = "ID_TYPE")
    private String idType;

    /** Column: idNo VARCHAR(50) */
    @Column(name = "ID_NO")
    private String idNo;

    /** Column: idDateOfIssue DATE(10) */
    @Column(name = "ID_DATE_OF_ISSUE")
    private Date idDateOfIssue;

    /** Column: idPlaceOfIssue VARCHAR(10) */
    @Column(name = "ID_PLACE_OF_ISSUE")
    private String idPlaceOfIssue;

    /** Column: idPlaceOfIssueName NVARCHAR(255) */
    @Column(name = "ID_PLACE_OF_ISSUE_NAME")
    private String idPlaceOfIssueName;

    /** Column: otherIdNo VARCHAR(10) */
    @Column(name = "OTHER_ID_NO")
    private String otherIdNo;

    /** Column: otherIdDateOfIssue DATE(10) */
    @Column(name = "OTHER_ID_DATE_OF_ISSUE")
    private Date otherIdDateOfIssue;

    /** Column: otherIdPlaceOfIssue VARCHAR(10) */
    @Column(name = "OTHER_ID_PLACE_OF_ISSUE")
    private String otherIdPlaceOfIssue;

    /** Column: otherIdPlaceName NVARCHAR(255) */
    @Column(name = "OTHER_ID_PLACE_NAME")
    private String otherIdPlaceName;

    /** Column: candidateName NVARCHAR(255) */
    @Column(name = "CANDIDATE_NAME")
    private String candidateName;

    /** Column: gender VARCHAR(2) */
    @Column(name = "GENDER")
    private String gender;

    /** Column: genderName VARCHAR(50) */
    @Column(name = "GENDER_NAME")
    private String genderName;

    /** Column: dob DATE(10) */
    @Column(name = "DOB")
    private Date dob;

    /** Column: pob VARCHAR(10) */
    @Column(name = "POB")
    private String pob;

    /** Column: pobName NVARCHAR(255) */
    @Column(name = "POB_NAME")
    private String pobName;

    /** Column: email VARCHAR(255) */
    @Column(name = "EMAIL")
    private String email;

    /** Column: mobile VARCHAR(20) */
    @Column(name = "MOBILE")
    private String mobile;

    /** Column: nationality NVARCHAR(255) */
    @Column(name = "NATIONALITY")
    private String nationality;

    /** Column: nation NVARCHAR(255) */
    @Column(name = "NATION")
    private String nation;

    /** Column: educational VARCHAR(255) */
    @Column(name = "EDUCATIONAL")
    private String educational;

    /** Column: carrerCurrent VARCHAR(255) */
    @Column(name = "CARRER_CURRENT")
    private String carrerCurrent;

    /** Column: maritalStatus VARCHAR(10) */
    @Column(name = "MARITAL_STATUS")
    private String maritalStatus;

    /** Column: taxCode VARCHAR(50) */
    @Column(name = "TAX_CODE")
    private String taxCode;

    /** Column: permanentAddress NVARCHAR(255) */
    @Column(name = "PERMANENT_ADDRESS")
    private String permanentAddress;

    /** Column: permanentNest NVARCHAR(255) */
    @Column(name = "PERMANENT_NEST")
    private String permanentNest;

    /** Column: permanentProvince VARCHAR(10) */
    @Column(name = "PERMANENT_PROVINCE")
    private String permanentProvince;

    /** Column: permanentProvinceName NVARCHAR(255) */
    @Column(name = "PERMANENT_PROVINCE_NAME")
    private String permanentProvinceName;

    /** Column: permanentDistrict VARCHAR(10) */
    @Column(name = "PERMANENT_DISTRICT")
    private String permanentDistrict;

    /** Column: permanentDistrictName NVARCHAR(255) */
    @Column(name = "PERMANENT_DISTRICT_NAME")
    private String permanentDistrictName;

    /** Column: permanentWard VARCHAR(10) */
    @Column(name = "PERMANENT_WARD")
    private String permanentWard;

    /** Column: permanentWardName NVARCHAR(255) */
    @Column(name = "PERMANENT_WARD_NAME")
    private String permanentWardName;

    /** Column: sameAddress TINYINT(3) */
    @Column(name = "SAME_ADDRESS")
    private int sameAddress;

    /** Column: currentAddress NVARCHAR(255) */
    @Column(name = "CURRENT_ADDRESS")
    private String currentAddress;

    /** Column: currentNest NVARCHAR(255) */
    @Column(name = "CURRENT_NEST")
    private String currentNest;

    /** Column: currentProvince VARCHAR(10) */
    @Column(name = "CURRENT_PROVINCE")
    private String currentProvince;

    /** Column: currentProvinceName NVARCHAR(255) */
    @Column(name = "CURRENT_PROVINCE_NAME")
    private String currentProvinceName;

    /** Column: currentDistrict VARCHAR(10) */
    @Column(name = "CURRENT_DISTRICT")
    private String currentDistrict;

    /** Column: currentDistrictName NVARCHAR(255) */
    @Column(name = "CURRENT_DISTRICT_NAME")
    private String currentDistrictName;

    /** Column: currentWard VARCHAR(10) */
    @Column(name = "CURRENT_WARD")
    private String currentWard;

    /** Column: currentWardName NVARCHAR(255) */
    @Column(name = "CURRENT_WARD_NAME")
    private String currentWardName;

    /** Column: contactFullName NVARCHAR(255) */
    @Column(name = "CONTACT_FULL_NAME")
    private String contactFullName;

    /** Column: contactPhone VARCHAR(10) */
    @Column(name = "CONTACT_PHONE")
    private String contactPhone;

    /** Column: contactRelationship VARCHAR(10) */
    @Column(name = "CONTACT_RELATIONSHIP")
    private String contactRelationship;

    /** Column: accountName NVARCHAR(255) */
    @Column(name = "ACCOUNT_NAME")
    private String accountName;

    /** Column: accountNumber VARCHAR(50) */
    @Column(name = "ACCOUNT_NUMBER")
    private String accountNumber;

    /** Column: bankName NVARCHAR(255) */
    @Column(name = "BANK_NAME")
    private String bankName;

    /** Column: bankProvince NVARCHAR(255) */
    @Column(name = "BANK_PROVINCE")
    private String bankProvince;

    /** Column: bankBranch VARCHAR(255) */
    @Column(name = "BANK_BRANCH")
    private String bankBranch;

    /** Column: bankBranchName NVARCHAR(255) */
    @Column(name = "BANK_BRANCH_NAME")
    private String bankBranchName;

    /** Column: classType VARCHAR(255) */
    @Column(name = "CLASS_TYPE")
    private String classType;

    /** Column: onlineOffline VARCHAR(10) */
    @Column(name = "ONLINE_OFFLINE")
    private String onlineOffline;

    /** Column: classProvince VARCHAR(10) */
    @Column(name = "CLASS_PROVINCE")
    private String classProvince;

    /** Column: classProvinceName NVARCHAR(255) */
    @Column(name = "CLASS_PROVINCE_NAME")
    private String classProvinceName;

    /** Column: classCode NVARCHAR(100) */
    @Column(name = "CLASS_CODE")
    private String classCode;

    /** Column: classPlace NVARCHAR(255) */
    @Column(name = "CLASS_PLACE")
    private String classPlace;

    /** Column: beginningDate DATE(10) */
    @Column(name = "BEGINNING_DATE")
    private Date beginningDate;

    /** Column: completedDate DATE(10) */
    @Column(name = "COMPLETED_DATE")
    private Date completedDate;

    /** Column: examPlace NVARCHAR(255) */
    @Column(name = "EXAM_PLACE")
    private String examPlace;

    /** Column: examDate DATE(10) */
    @Column(name = "EXAM_DATE")
    private Date examDate;

    /** Column: firstClassDate DATE(10) */
    @Column(name = "FIRST_CLASS_DATE")
    private Date firstClassDate;

    /** Column: classNote NVARCHAR(255) */
    @Column(name = "CLASS_NOTE")
    private String classNote;

    /** Column: recruiterType TINYINT(3) */
    @Column(name = "RECRUITER_TYPE")
    private int recruiterType;
    
    @Transient
    private String recruiterTypeName;

    /** Column: recruiterCode BIGINT(19) */
    @Column(name = "RECRUITER_CODE")
    private String recruiterCode;

    /** Column: recruiterIdNo VARCHAR(255) */
    @Column(name = "RECRUITER_ID_NO")
    private String recruiterIdNo;

    /** Column: recruiterName NVARCHAR(255) */
    @Column(name = "RECRUITER_NAME")
    private String recruiterName;

    /** Column: recruiterAdCode BIGINT(19) */
    @Column(name = "RECRUITER_AD_CODE")
    private Long recruiterAdCode;

    /** Column: recruiterAdName NVARCHAR(255) */
    @Column(name = "RECRUITER_AD_NAME")
    private String recruiterAdName;
    
    @Column(name = "RECRUITER_AD_POSITION")
    private String recruiterAdPosition;

    /** Column: recruiterPosition NVARCHAR(255) */
    @Column(name = "RECRUITER_POSITION")
    private String recruiterPosition;

    /** Column: managerType TINYINT(3) */
    @Column(name = "MANAGER_TYPE")
    private int managerType;

    @Transient
    private String managerTypeName;
    
    /** Column: managerCode BIGINT(19) */
    @Column(name = "MANAGER_CODE")
    private String managerCode;

    /** Column: managerIdNo VARCHAR(255) */
    @Column(name = "MANAGER_ID_NO")
    private String managerIdNo;

    /** Column: managerName NVARCHAR(255) */
    @Column(name = "MANAGER_NAME")
    private String managerName;

    /** Column: managerAdCode BIGINT(19) */
    @Column(name = "MANAGER_AD_CODE")
    private Long managerAdCode;

    /** Column: managerAdName NVARCHAR(255) */
    @Column(name = "MANAGER_AD_NAME")
    private String managerAdName;
    
    @Column(name = "MANAGER_AD_POSITION")
    private String managerAdPosition;

    /** Column: managerPosition NVARCHAR(255) */
    @Column(name = "MANAGER_POSITION")
    private String managerPosition;

    /** Column: managerIndirectType TINYINT(3) */
    @Column(name = "MANAGER_INDIRECT_TYPE")
    private int managerIndirectType;
    
    @Transient
    private String managerIndirectTypeName;

    /** Column: managerIndirectCode BIGINT(19) */
    @Column(name = "MANAGER_INDIRECT_CODE")
    private String managerIndirectCode;

    /** Column: managerIndirectIdNo VARCHAR(255) */
    @Column(name = "MANAGER_INDIRECT_ID_NO")
    private String managerIndirectIdNo;

    /** Column: managerIndirectName NVARCHAR(255) */
    @Column(name = "MANAGER_INDIRECT_NAME")
    private String managerIndirectName;

    /** Column: managerIndirectAdCode BIGINT(19) */
    @Column(name = "MANAGER_INDIRECT_AD_CODE")
    private Long managerIndirectAdCode;

    /** Column: managerIndirectAdName NVARCHAR(255) */
    @Column(name = "MANAGER_INDIRECT_AD_NAME")
    private String managerIndirectAdName;
    
    @Column(name = "MANAGER_INDIRECT_AD_POSITION")
    private String managerIndirectAdPosition;

    /** Column: managerIndirectPosition NVARCHAR(255) */
    @Column(name = "MANAGER_INDIRECT_POSITION")
    private String managerIndirectPosition;

    /** Column: checkEkycStatus TINYINT(3) */
    @Column(name = "CHECK_EKYC_STATUS")
    private int checkEkycStatus;

    /** Column: ekycOption TINYINT(3) */
    @Column(name = "EKYC_OPTION")
    private int ekycOption;

    /** Column: ekycSendMailTime DATETIME(23) */
    @Column(name = "EKYC_SEND_MAIL_TIME")
    private Date ekycSendMailTime;

    /** Column: ekycResult TINYINT(3) */
    @Column(name = "EKYC_RESULT")
    private int ekycResult;

    /** Column: ekycStatus VARCHAR(10) */
    @Column(name = "EKYC_STATUS")
    private String ekycStatus;

    /** Column: checkInterviewStatus TINYINT(3) */
    @Column(name = "CHECK_INTERVIEW_STATUS")
    private int checkInterviewStatus;

    /** Column: interviewSendMailTime DATETIME(23) */
    @Column(name = "INTERVIEW_SEND_MAIL_TIME")
    private Date interviewSendMailTime;

    /** Column: interviewComment TINYINT(3) */
    @Column(name = "INTERVIEW_COMMENT")
    private String interviewComment;
    
    @Column(name = "INTERVIEW_2_COMMENT")
    private String interview2Comment;

    /** Column: interviewPoint VARCHAR(10) */
    @Column(name = "INTERVIEW_POINT")
    private String interviewPoint;
    
    @Column(name = "INTERVIEW_2_POINT")
    private String interview2Point;

    /** Column: interviewStatus VARCHAR(10) */
    @Column(name = "INTERVIEW_STATUS")
    private String interviewStatus;
    
    @Column(name = "INTERVIEW_2_STATUS")
    private String interview2Status;

    /** Column: avicadStatus VARCHAR(10) */
    @Column(name = "AVICAD_STATUS")
    private String avicadStatus;

    /** Column: checkAvicadStatus TINYINT(3) */
    @Column(name = "CHECK_AVICAD_STATUS")
    private int checkAvicadStatus;

    /** Column: refAttachement VARCHAR(255) */
    @Column(name = "REF_ATTACHEMENT")
    private String refAttachement;

    /** Column: companyId BIGINT(19) */
    @Column(name = "COMPANY_ID")
    private Long companyId;

    /** Column: formId BIGINT(19) */
    @Column(name = "FORM_ID")
    private Long formId;

    /** Column: docUuid VARCHAR(100) */
    @Column(name = "DOC_UUID")
    private String docUuid;

    /** Column: formStatus NVARCHAR(255) */
    @Column(name = "FORM_STATUS")
    private String formStatus;

    /** Column: versionData TIMESTAMP(8) */
    @Transient
    private byte[] versionData;

    /** Column: fieldUser1 NVARCHAR(2147483647) */
    @Column(name = "FIELD_USER_1")
    private String fieldUser1;

    /** Column: fieldUser2 NVARCHAR(2147483647) */
    @Column(name = "FIELD_USER_2")
    private String fieldUser2;

    /** Column: fieldUser3 NVARCHAR(2147483647) */
    @Column(name = "FIELD_USER_3")
    private String fieldUser3;

    /** Column: fieldUser4 NVARCHAR(2147483647) */
    @Column(name = "FIELD_USER_4")
    private String fieldUser4;

    /** Column: fieldUser5 NVARCHAR(2147483647) */
    @Column(name = "FIELD_USER_5")
    private String fieldUser5;

    @Column(name = "CREATED_BY")
    private String createdBy;

    @Column(name = "CREATED_DATE")
    private Date createdDate;

    @Column(name = "UPDATED_BY")
    private String updatedBy;

    @Column(name = "UPDATED_DATE")
    private Date updatedDate;
    
    @Column(name = "DELETED_BY")
    private String deletedBy;

    @Column(name = "DELETED_DATE")
    private Date deletedDate;

    @Column(name = "DELETED_FLAG")
    private int deletedFlag;
    
    @Column(name = "OTHER_POSITION")
    private String otherPosition;
    
    @Column(name = "FORM_STATUS_CODE")
    private String formStatusCode;
    
    @Column(name = "SUBMIT_INFOR_DATE")
    private Date submitInforDate;
    
    @Column(name="SECRET_KEY")
    private String secretKey;
    
    @Column(name="SECRET_DATE")
    private Date secretDate;
    
    @Column(name="OTP")
    private String otp;

	//  + INTERVIEW_AGENT_COD : Agent code của người PV1
    @Column(name="INTERVIEW_AGENT_CODE")
	private String interViewAgentCode; 
	//  + INTERVIEW_NAME: Fullname người PV1
    @Column(name="INTERVIEW_NAME")
	private String interviewName;
	//
	//  + INTERVIEW_2_AGENT_CODE: Agent code của người PV2
    @Column(name="INTERVIEW_2_AGENT_CODE")
	private String interView2AgentCode; 
	//  + INTERVIEW_2_NAME Fullname người PV2 
    @Column(name="INTERVIEW_2_NAME")
	private String interview2Name;
    
    @Column(name="USER_INPUT_FLAG")
    private Integer userInputFlag;
    
    @Column(name="USER_SUBMIT_DATE")
    private Date userSubmitDate;
    
    @Column(name="SLA_FLAG")
    private Integer slaFlag;
}
