SELECT
    AAC.ID                  COMPANY_ID
    ,AAC.ACCOUNT_ID         ACCOUNT_ID
    ,AAC.IS_ADMIN           IS_ADMIN
    ,AAC.IS_DISPLAY_EMAIL   IS_DISPLAY_EMAIL    
    ,AAC.ORG_ID             ORG_ID
FROM VW_GET_AUTHORITY_ACCT_COMPANY AAC
WHERE 
	AAC.ACCOUNT_ID = /*accountId*/1
	AND AAC.ID <> /*currentCompanyId*/1
ORDER BY COMPANY_ID, ACCOUNT_ID, ORG_ID