SELECT 
	accOrg.ACCOUNT_ID 			AS USER_ID,
	accOrg.ORG_ID				AS ORG_ID,
	org.CODE					AS ORG_CODE,
	org.NAME					AS ORG_NAME,
	accOrg.POSITION_ID 			AS POSITION_ID,
	pos.NAME					AS POSITION_NAME,
	accOrg.ACTIVED				AS ACTIVED,
	accOrg.MAIN_FLAG			AS MAIN_FLAG
FROM JCA_POSITION pos
LEFT JOIN JCA_ACCOUNT_ORG accOrg 
ON pos.ID = accOrg.POSITION_ID
LEFT JOIN JCA_ORGANIZATION org 
ON accOrg.ORG_ID = org.ID
WHERE accOrg.ACCOUNT_ID = /*accountId*/
	AND accOrg.ORG_ID = /*orgId*/
	AND accOrg.POSITION_ID = /*positionId*/ 
