SELECT JROLE.ID AS ROLE_ID
,JROLE.CODE AS ROLE_CODE
,JROLE.NAME AS ROLE_NAME
,DROLE.MENU_ID  AS MENU_ID
,DROLE.DISPLAY_ORDER AS DISPLAY_ORDER
,JROLE.ACTIVED AS ACTIVE
FROM JCA_ROLE JROLE LEFT JOIN JCA_ROLE_FOR_LANDING_PAGE DROLE ON DROLE.ROLE_ID = JROLE.ID 
WHERE JROLE.DELETED_ID = 0 
AND JROLE.ID=/*roleId*/