SELECT 
	JROLE.ID              AS ROLE_ID
	, JROLE.CODE          AS ROLE_CODE
    , JROLE.NAME          AS ROLE_NAME
    , DROLE.MENU_ID       AS MENU_ID
    , DROLE.DISPLAY_ORDER AS DISPLAY_ORDER
	, JROLE.ACTIVED        AS ACTIVED
    , JROLE.COMPANY_ID    AS COMPANY_ID
    , COM.NAME            AS COMPANY_NAME
    , CASE WHEN COM.NAME IS NULL THEN N'ZZZ' ELSE COM.NAME END ORDER_NAME
FROM 
	JCA_ROLE JROLE 
LEFT JOIN 
	JCA_ROLE_FOR_LANDING_PAGE DROLE 
	ON DROLE.ROLE_ID = JROLE.ID
LEFT JOIN
	JCA_COMPANY COM 
	ON JROLE.COMPANY_ID = COM.ID
	AND COM.DELETED_ID = 0
WHERE 
	JROLE.DELETED_ID = 0
ORDER BY 
	
	 DROLE.DISPLAY_ORDER ASC,
	 ORDER_NAME,
	 JROLE.ID ASC;