SELECT M.* FROM (
    SELECT ROLE_ID
    FROM JCA_ROLE_FOR_ACCOUNT RFA
    INNER JOIN JCA_ROLE ROLE ON ROLE.ID = RFA.ROLE_ID
    WHERE  RFA.ACCOUNT_ID = /*accountId*/1
    UNION
    SELECT ROLETM.ROLE_ID
    FROM JCA_ROLE_FOR_TEAM ROLETM
    INNER JOIN JCA_ACCOUNT_TEAM ACCTM ON ACCTM.TEAM_ID = ROLETM.TEAM_ID
    INNER JOIN JCA_ROLE ROLE ON ROLE.ID = ROLETM.ROLE_ID
    WHERE  ACCTM.ACCOUNT_ID = /*accountId*/1
) ROLE 
INNER JOIN JCA_ROLE_FOR_LANDING_PAGE RM ON ROLE.ROLE_ID = RM.ROLE_ID
INNER JOIN JCA_MENU M ON M.ID = RM.MENU_ID
ORDER BY RM.DISPLAY_ORDER ASC
OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY