SELECT  ORG.ORG_CODE, ORG.ORG_NAME
        , CONNECT_BY_ROOT ORG.ORG_CODE AS PARENT_ROOT_CODE
        FROM JCA_ORGANIZATION ORG
        WHERE ORG.DELETED_ID = 0 AND ORG.ORG_CODE = /*code*/''
        AND LEVEL = 4
      
        START WITH ORG.ID IN (SELECT JCA_M_ORG.ID
FROM JCA_ORGANIZATION 
WHERE JCA_M_ORG.COMPANY_ID = /*companyId*/0  AND JCA_M_ORG.ORG_LEVEL = 3 AND JCA_M_ORG.DELETED_ID = 0
)
        CONNECT BY PRIOR ORG.ID = ORG.PARENT_ORG_ID