/********************************************************************************
* Class        : AppApiExceptionCodeConstant
* Created date : 2020/11/08
* Lasted date  : 2020/11/08
* Author       : TaiTT
* Change log   : 2020/11/08 : 01-00 TaiTT create a new
* Change log   : 22/03/2024	nt.tinh SR16136 - Fix lỗi phát hiện trong quá trình Pentest - 2023
******************************************************************************/

package vn.com.unit.ep2p.core.constant;

import vn.com.unit.common.constant.CommonExceptionCodeConstant;
/**
* <p> AppApiExceptionCodeConstant </p>
* 
* <pre> 
* The First character is for the description level module: 1
* The next two characters are for the module descriptive name: 01
* The next three characters continue are for the module description error code: 600
* </pre> 
* 
* <pre> 
* JCOMMON is module code required, next characters is message error: INTERNAL_ERROR
* </pre> 
* @version : 01-00
* @since 01-00
* @author : TaiTT
 */
public class AppApiExceptionCodeConstant extends CommonExceptionCodeConstant {

   // ERROR DEFAULT (600-700)
   /** APPAPI_INTERNAL_ERROR */ 
  public static final String E402600_APPAPI_INTERNAL_ERROR = "402600_APPAPI_INTERNAL_ERROR";

   // API FORM REST (700-799)
   /** APPAPI_FORM_REST_TEMPLATE */ 
  public static final String E402700_APPAPI_FORM_REST_TEMPLATE = "402700_APPAPI_FORM_REST_TEMPLATE";

   // API ACCOUNT REST (800-899)
   /** APPAPI_ACCOUNT_LIST_ERROR */ 
  public static final String E402801_APPAPI_ACCOUNT_LIST_ERROR = "402801_APPAPI_ACCOUNT_LIST_ERROR";
   /** APPAPI_ACCOUNT_ADD_ERROR */ 
  public static final String E402802_APPAPI_ACCOUNT_ADD_ERROR = "402802_APPAPI_ACCOUNT_ADD_ERROR";
   /** APPAPI_ACCOUNT_UPDATE_INFO_ERROR */ 
  public static final String E402803_APPAPI_ACCOUNT_UPDATE_INFO_ERROR = "402803_APPAPI_ACCOUNT_UPDATE_INFO_ERROR";
   /** APPAPI_ACCOUNT_DELETE_ERROR */ 
  public static final String E402804_APPAPI_ACCOUNT_DELETE_ERROR = "402804_APPAPI_ACCOUNT_DELETE_ERROR";
   /** APPAPI_ACCOUNT_INFO_ERROR */ 
  public static final String E402805_APPAPI_ACCOUNT_INFO_ERROR = "402805_APPAPI_ACCOUNT_INFO_ERROR";
   /** APPAPI_ACCOUNT_NOT_FOUND */ 
  public static final String E402806_APPAPI_ACCOUNT_NOT_FOUND = "402806_APPAPI_ACCOUNT_NOT_FOUND";
   /** APPAPI_ACCOUNT_CHANGE_PASSWORD_ERROR */ 
  public static final String E402807_APPAPI_ACCOUNT_CHANGE_PASSWORD_ERROR = "402807_APPAPI_ACCOUNT_CHANGE_PASSWORD_ERROR";
   /** APPAPI_ACCOUNT_PASSWORD_OLD_INCORRECT */ 
  public static final String E402808_APPAPI_ACCOUNT_PASSWORD_OLD_INCORRECT = "402808_APPAPI_ACCOUNT_PASSWORD_OLD_INCORRECT";
  
  public static final String E402808_APPAPI_ACCOUNT_PASSWORD_GAD_OLD_INCORRECT = "402808_APPAPI_ACCOUNT_PASSWORD_GAD_OLD_INCORRECT";
   /** APPAPI_ACCOUNT_CONFIRM_PASSWORD_NEW_INCORRECT */ 
  public static final String E402809_APPAPI_ACCOUNT_CONFIRM_PASSWORD_NEW_INCORRECT = "402809_APPAPI_ACCOUNT_CONFIRM_PASSWORD_NEW_INCORRECT";
   /** APPAPI_ACCOUNT_USERNAME_DUPLICATED */ 
  public static final String E402810_APPAPI_ACCOUNT_USERNAME_DUPLICATED = "402810_APPAPI_ACCOUNT_USERNAME_DUPLICATED";
   /** APPAPI_ACCOUNT_EMAIL_DUPLICATED */ 
  public static final String E402811_APPAPI_ACCOUNT_EMAIL_DUPLICATED = "402811_APPAPI_ACCOUNT_EMAIL_DUPLICATED";
   /** APPAPI_ACCOUNT_PHONE_FORMAT */
  public static final String E402812_APPAPI_ACCOUNT_PHONE_FORMAT = "402812_APPAPI_ACCOUNT_PHONE_FORMAT";
   /** APPAPI_ACCOUNT_EMAIL_FORMAT */ 
  public static final String E402813_APPAPI_ACCOUNT_EMAIL_FORMAT = "402813_APPAPI_ACCOUNT_EMAIL_FORMAT";
   /** APPAPI_ACCOUNT_CODE_DUPLICATED */ 
  public static final String E402814_APPAPI_ACCOUNT_CODE_DUPLICATED = "402814_APPAPI_ACCOUNT_CODE_DUPLICATED";
  public static final String E402815_APPAPI_INVALID_INFO = "402815_APPAPI_INVALID_INFO";

   // API POSITION REST (900-999)
   /** APPAPI_POSITION_LIST_ERROR */ 
  public static final String E402901_APPAPI_POSITION_LIST_ERROR = "402901_APPAPI_POSITION_LIST_ERROR";
   /** APPAPI_POSITION_ADD_ERROR */ 
  public static final String E402902_APPAPI_POSITION_ADD_ERROR = "402902_APPAPI_POSITION_ADD_ERROR";
   /** APPAPI_POSITION_UPDATE_INFO_ERROR */ 
  public static final String E402903_APPAPI_POSITION_UPDATE_INFO_ERROR = "402903_APPAPI_POSITION_UPDATE_INFO_ERROR";
   /** APPAPI_POSITION_DELETE_ERROR */ 
  public static final String E402904_APPAPI_POSITION_DELETE_ERROR = "402904_APPAPI_POSITION_DELETE_ERROR";
   /** APPAPI_POSITION_INFO_ERROR */ 
  public static final String E402905_APPAPI_POSITION_INFO_ERROR = "402905_APPAPI_POSITION_INFO_ERROR";
   /** APPAPI_POSITION_NOT_FOUND */ 
  public static final String E402906_APPAPI_POSITION_NOT_FOUND = "402906_APPAPI_POSITION_NOT_FOUND";
   /** APPAPI_POSITION_PARENT_NOT_FOUND */ 
  public static final String E402907_APPAPI_POSITION_PARENT_NOT_FOUND = "402907_APPAPI_POSITION_PARENT_NOT_FOUND";
   /** APPAPI_POSITION_CODE_DUPLICATED */ 
  public static final String E402908_APPAPI_POSITION_CODE_DUPLICATED = "402908_APPAPI_POSITION_CODE_DUPLICATED";

   // API ROLE REST (1000-1099)
   /** APPAPI_ROLE_LIST_ERROR */ 
  public static final String E4021000_APPAPI_ROLE_LIST_ERROR = "4021000_APPAPI_ROLE_LIST_ERROR";
   /** APPAPI_ROLE_ADD_ERROR */ 
  public static final String E4021001_APPAPI_ROLE_ADD_ERROR = "4021001_APPAPI_ROLE_ADD_ERROR";
   /** APPAPI_ROLE_DELETE_ERROR */ 
  public static final String E4021002_APPAPI_ROLE_DELETE_ERROR = "4021002_APPAPI_ROLE_DELETE_ERROR";
   /** APPAPI_ROLE_NOT_FOUND */ 
  public static final String E4021003_APPAPI_ROLE_NOT_FOUND = "4021003_APPAPI_ROLE_NOT_FOUND";
   /** APPAPI_ROLE_UPDATE_INFO_ERROR */ 
  public static final String E4021004_APPAPI_ROLE_UPDATE_INFO_ERROR = "4021004_APPAPI_ROLE_UPDATE_INFO_ERROR";
   /** APPAPI_ROLE_INFO_ERROR */ 
  public static final String E4021005_APPAPI_ROLE_INFO_ERROR = "4021005_APPAPI_ROLE_INFO_ERROR";
   /** APPAPI_ROLE_CODE_DUPLICATED */ 
  public static final String E4021006_APPAPI_ROLE_CODE_DUPLICATED = "4021006_APPAPI_ROLE_CODE_DUPLICATED";
   /** APPAPI_ROLE_NAME_DUPLICATED */ 
  public static final String E4021007_APPAPI_ROLE_NAME_DUPLICATED = "4021007_APPAPI_ROLE_NAME_DUPLICATED";

   // API ITEM REST (1100-1199)
   /** APPAPI_ITEM_LIST_ERROR */ 
  public static final String E4021100_APPAPI_ITEM_LIST_ERROR = "4021100_APPAPI_ITEM_LIST_ERROR";
   /** APPAPI_ITEM_ADD_ERROR */ 
  public static final String E4021101_APPAPI_ITEM_ADD_ERROR = "4021101_APPAPI_ITEM_ADD_ERROR";
   /** APPAPI_ITEM_UPDATE_INFO_ERROR */ 
  public static final String E4021102_APPAPI_ITEM_UPDATE_INFO_ERROR = "4021102_APPAPI_ITEM_UPDATE_INFO_ERROR";
   /** APPAPI_ITEM_DELETE_ERROR */ 
  public static final String E4021103_APPAPI_ITEM_DELETE_ERROR = "4021103_APPAPI_ITEM_DELETE_ERROR";
   /** APPAPI_ITEM_INFO_ERROR */ 
  public static final String E4021104_APPAPI_ITEM_INFO_ERROR = "4021104_APPAPI_ITEM_INFO_ERROR";
   /** APPAPI_ITEM_NOT_FOUND */ 
  public static final String E4021105_APPAPI_ITEM_NOT_FOUND = "4021105_APPAPI_ITEM_NOT_FOUND";
   /** APPAPI_ITEM_FUNCTION_CODE_DUPLICATED */ 
  public static final String E4021106_APPAPI_ITEM_FUNCTION_CODE_DUPLICATED = "4021106_APPAPI_ITEM_FUNCTION_CODE_DUPLICATED";

   // API COMPANY REST (1200-1299)
   /** APPAPI_COMPANY_LIST_ERROR */ 
  public static final String E4021200_APPAPI_COMPANY_LIST_ERROR = "4021200_APPAPI_COMPANY_LIST_ERROR";
   /** APPAPI_COMPANY_ADD_ERROR */ 
  public static final String E4021201_APPAPI_COMPANY_ADD_ERROR = "4021201_APPAPI_COMPANY_ADD_ERROR";
   /** APPAPI_COMPANY_DELETE_ERROR */ 
  public static final String E4021202_APPAPI_COMPANY_DELETE_ERROR = "4021202_APPAPI_COMPANY_DELETE_ERROR";
   /** APPAPI_COMPANY_NOT_FOUND */ 
  public static final String E4021203_APPAPI_COMPANY_NOT_FOUND = "4021203_APPAPI_COMPANY_NOT_FOUND";
   /** APPAPI_COMPANY_UPDATE_INFO_ERROR */ 
  public static final String E4021204_APPAPI_COMPANY_UPDATE_INFO_ERROR = "4021204_APPAPI_COMPANY_UPDATE_INFO_ERROR";
   /** APPAPI_COMPANY_SYSTEM_CODE_DUPLICATED */ 
  public static final String E4021205_APPAPI_COMPANY_SYSTEM_CODE_DUPLICATED = "4021205_APPAPI_COMPANY_SYSTEM_CODE_DUPLICATED";
   /** APPAPI_COMPANY_SYSTEM_NAME_DUPLICATED */ 
  public static final String E4021207_APPAPI_COMPANY_SYSTEM_NAME_DUPLICATED = "4021207_APPAPI_COMPANY_SYSTEM_NAME_DUPLICATED";

   // API BUSINESS REST (1300-1399)
   /** APPAPI_BUSINESS_LIST_ERROR */ 
  public static final String E4021300_APPAPI_BUSINESS_LIST_ERROR = "4021300_APPAPI_BUSINESS_LIST_ERROR";
   /** APPAPI_BUSINESS_ADD_ERROR */ 
  public static final String E4021301_APPAPI_BUSINESS_ADD_ERROR = "4021301_APPAPI_BUSINESS_ADD_ERROR";
   /** APPAPI_BUSINESS_UPDATE_INFO_ERROR */ 
  public static final String E4021302_APPAPI_BUSINESS_UPDATE_INFO_ERROR = "4021302_APPAPI_BUSINESS_UPDATE_INFO_ERROR";
   /** APPAPI_BUSINESS_DELETE_ERROR */ 
  public static final String E4021303_APPAPI_BUSINESS_DELETE_ERROR = "4021303_APPAPI_BUSINESS_DELETE_ERROR";
   /** APPAPI_BUSINESS_INFO_ERROR */ 
  public static final String E4021304_APPAPI_BUSINESS_INFO_ERROR = "4021304_APPAPI_BUSINESS_INFO_ERROR";
   /** APPAPI_BUSINESS_NOT_FOUND */ 
  public static final String E4021305_APPAPI_BUSINESS_NOT_FOUND = "4021305_APPAPI_BUSINESS_NOT_FOUND";
   /** APPAPI_BUSINESS_CODE_DUPLICATED */ 
  public static final String E4021306_APPAPI_BUSINESS_CODE_DUPLICATED = "4021306_APPAPI_BUSINESS_CODE_DUPLICATED";

   // API PROCESS REST (1400-1499)
   /** APPAPI_PROCESS_LIST_ERROR */ 
  public static final String E4021400_APPAPI_PROCESS_LIST_ERROR = "4021400_APPAPI_PROCESS_LIST_ERROR";
   /** APPAPI_PROCESS_ADD_ERROR */ 
  public static final String E4021401_APPAPI_PROCESS_ADD_ERROR = "4021401_APPAPI_PROCESS_ADD_ERROR";
   /** APPAPI_PROCESS_UPDATE_INFO_ERROR */ 
  public static final String E4021402_APPAPI_PROCESS_UPDATE_INFO_ERROR = "4021402_APPAPI_PROCESS_UPDATE_INFO_ERROR";
   /** APPAPI_PROCESS_DELETE_ERROR */ 
  public static final String E4021403_APPAPI_PROCESS_DELETE_ERROR = "4021403_APPAPI_PROCESS_DELETE_ERROR";
   /** APPAPI_PROCESS_INFO_ERROR */ 
  public static final String E4021404_APPAPI_PROCESS_INFO_ERROR = "4021404_APPAPI_PROCESS_INFO_ERROR";
   /** APPAPI_PROCESS_NOT_FOUND */ 
  public static final String E4021405_APPAPI_PROCESS_NOT_FOUND = "4021405_APPAPI_PROCESS_NOT_FOUND";

   // API TEAM REST (1500-1599)
   /** APPAPI_TEAM_LIST_ERROR */ 
  public static final String E4021501_APPAPI_TEAM_LIST_ERROR = "4021501_APPAPI_TEAM_LIST_ERROR";
   /** APPAPI_TEAM_ADD_ERROR */ 
  public static final String E4021502_APPAPI_TEAM_ADD_ERROR = "4021502_APPAPI_TEAM_ADD_ERROR";
   /** APPAPI_TEAM_UPDATE_INFO_ERROR */ 
  public static final String E4021503_APPAPI_TEAM_UPDATE_INFO_ERROR = "4021503_APPAPI_TEAM_UPDATE_INFO_ERROR";
   /** APPAPI_TEAM_DELETE_ERROR */ 
  public static final String E4021504_APPAPI_TEAM_DELETE_ERROR = "4021504_APPAPI_TEAM_DELETE_ERROR";
   /** APPAPI_TEAM_INFO_ERROR */ 
  public static final String E4021505_APPAPI_TEAM_INFO_ERROR = "4021505_APPAPI_TEAM_INFO_ERROR";
   /** APPAPI_TEAM_NOT_FOUND */ 
  public static final String E4021506_APPAPI_TEAM_NOT_FOUND = "4021506_APPAPI_TEAM_NOT_FOUND";
   /** APPAPI_TEAM_CODE_DUPLICATED */ 
  public static final String E4021507_APPAPI_TEAM_CODE_DUPLICATED = "4021507_APPAPI_TEAM_CODE_DUPLICATED";
   /** APPAPI_TEAM_NAME_DUPLICATED */ 
  public static final String E4021508_APPAPI_TEAM_NAME_DUPLICATED = "4021508_APPAPI_TEAM_NAME_DUPLICATED";

   // API MENU REST (1600-1699)
   /** APPAPI_MENU_ERROR */ 
  public static final String E4021600_APPAPI_MENU_ERROR = "4021600_APPAPI_MENU_ERROR";
   /** APPAPI_MENU_BUILD_TREE_ERROR */ 
  public static final String E4021601_APPAPI_MENU_BUILD_TREE_ERROR = "4021601_APPAPI_MENU_BUILD_TREE_ERROR";
   /** APPAPI_MENU_NOT_FOUND */ 
  public static final String E4021602_APPAPI_MENU_NOT_FOUND = "4021602_APPAPI_MENU_NOT_FOUND";
   /** APPAPI_MENU_PATH_NOT_FOUND */ 
  public static final String E4021603_APPAPI_MENU_PATH_NOT_FOUND = "4021603_APPAPI_MENU_PATH_NOT_FOUND";
   /** APPAPI_MENU_LIST_ERROR */ 
  public static final String E4021604_APPAPI_MENU_LIST_ERROR = "4021604_APPAPI_MENU_LIST_ERROR";
   /** APPAPI_MENU_ADD_ERROR */ 
  public static final String E4021605_APPAPI_MENU_ADD_ERROR = "4021605_APPAPI_MENU_ADD_ERROR";
   /** APPAPI_MENU_UPDATE */ 
  public static final String E4021606_APPAPI_MENU_UPDATE = "4021606_APPAPI_MENU_UPDATE";
   /** APPAPI_MENU_INFO_ERROR */ 
  public static final String E4021607_APPAPI_MENU_INFO_ERROR = "4021607_APPAPI_MENU_INFO_ERROR";
   /** APPAPI_MENU_DELETE_ERROR */ 
  public static final String E4021608_APPAPI_MENU_DELETE_ERROR = "4021608_APPAPI_MENU_DELETE_ERROR";
   /** APPAPI_MENU_PATH_SAVE_ERROR */ 
  public static final String E4021609_APPAPI_MENU_PATH_SAVE_ERROR = "4021609_APPAPI_MENU_PATH_SAVE_ERROR";
   /** APPAPI_MENU_PARENT_NOT_FOUND */ 
  public static final String E4021610_APPAPI_MENU_PARENT_NOT_FOUND = "4021610_APPAPI_MENU_PARENT_NOT_FOUND";

   // API CALENDAR TYPE REST (1700-1799)
   /** APPAPI_CALENDAR_TYPE_LIST_ERROR */ 
  public static final String E4021701_APPAPI_CALENDAR_TYPE_LIST_ERROR = "4021701_APPAPI_CALENDAR_TYPE_LIST_ERROR";
   /** APPAPI_CALENDAR_TYPE_ADD_ERROR */ 
  public static final String E4021702_APPAPI_CALENDAR_TYPE_ADD_ERROR = "4021702_APPAPI_CALENDAR_TYPE_ADD_ERROR";
   /** APPAPI_CALENDAR_TYPE_UPDATE_ERROR */ 
  public static final String E4021703_APPAPI_CALENDAR_TYPE_UPDATE_ERROR = "4021703_APPAPI_CALENDAR_TYPE_UPDATE_ERROR";
   /** APPAPI_CALENDAR_TYPE_DETAIL_ERROR */ 
  public static final String E4021704_APPAPI_CALENDAR_TYPE_DETAIL_ERROR = "4021704_APPAPI_CALENDAR_TYPE_DETAIL_ERROR";
   /** APPAPI_CALENDAR_TYPE_DELETE_ERROR */ 
  public static final String E4021705_APPAPI_CALENDAR_TYPE_DELETE_ERROR = "4021705_APPAPI_CALENDAR_TYPE_DELETE_ERROR";

   // API ORGANIZATION REST (1800-1899)
   /** APPAPI_ORGANIZATION_ERROR */ 
  public static final String E4021800_APPAPI_ORGANIZATION_ERROR = "4021800_APPAPI_ORGANIZATION_ERROR";
   /** APPAPI_ORGANIZATION_BUILD_TREE_ERROR */ 
  public static final String E4021801_APPAPI_ORGANIZATION_BUILD_TREE_ERROR = "4021801_APPAPI_ORGANIZATION_BUILD_TREE_ERROR";
   /** APPAPI_ORGANIZATION_NOT_FOUND */ 
  public static final String E4021802_APPAPI_ORGANIZATION_NOT_FOUND = "4021802_APPAPI_ORGANIZATION_NOT_FOUND";
   /** APPAPI_ORGANIZATION_LIST_ERROR */ 
  public static final String E4021803_APPAPI_ORGANIZATION_LIST_ERROR = "4021803_APPAPI_ORGANIZATION_LIST_ERROR";
   /** APPAPI_ORGANIZATION_ADD_ERROR */ 
  public static final String E4021804_APPAPI_ORGANIZATION_ADD_ERROR = "4021804_APPAPI_ORGANIZATION_ADD_ERROR";
   /** APPAPI_ORGANIZATION_UPDATE_INFO_ERROR */ 
  public static final String E4021805_APPAPI_ORGANIZATION_UPDATE_INFO_ERROR = "4021805_APPAPI_ORGANIZATION_UPDATE_INFO_ERROR";
   /** APPAPI_ORGANIZATION_INFO_ERROR */ 
  public static final String E4021806_APPAPI_ORGANIZATION_INFO_ERROR = "4021806_APPAPI_ORGANIZATION_INFO_ERROR";
   /** APPAPI_ORGANIZATION_DELETE_ERROR */ 
  public static final String E4021807_APPAPI_ORGANIZATION_DELETE_ERROR = "4021807_APPAPI_ORGANIZATION_DELETE_ERROR";
   /** APPAPI_ORGANIZATION_PATH_NOT_FOUND */ 
  public static final String E4021808_APPAPI_ORGANIZATION_PATH_NOT_FOUND = "4021808_APPAPI_ORGANIZATION_PATH_NOT_FOUND";
   /** APPAPI_ORGANIZATION_PATH_SAVE_ERROR */ 
  public static final String E4021809_APPAPI_ORGANIZATION_PATH_SAVE_ERROR = "4021809_APPAPI_ORGANIZATION_PATH_SAVE_ERROR";
   /** APPAPI_ORGANIZATION_PARENT_NOT_FOUND */ 
  public static final String E4021810_APPAPI_ORGANIZATION_PARENT_NOT_FOUND = "4021810_APPAPI_ORGANIZATION_PARENT_NOT_FOUND";
   /** APPAPI_ORGANIZATION_CODE_DUPLICATED */ 
  public static final String E4021811_APPAPI_ORGANIZATION_CODE_DUPLICATED = "4021811_APPAPI_ORGANIZATION_CODE_DUPLICATED";
  
  public static final String E4021812_APPAPI_ORGANIZATION_GET_NODE_CHILD_ERROR= "4021812_APPAPI_ORGANIZATION_GET_NODE_CHILD_ERROR";

   // API PROCESS DEPLOY REST (1900-1999)
   /** APPAPI_PROCESS_DEPLOY_LIST_ERROR */ 
  public static final String E4021901_APPAPI_PROCESS_DEPLOY_LIST_ERROR = "4021901_APPAPI_PROCESS_DEPLOY_LIST_ERROR";
   /** APPAPI_PROCESS_DELETE_DEPLOY_ERROR */ 
  public static final String E4021904_APPAPI_PROCESS_DEPLOY_DELETE_ERROR = "4021904_APPAPI_PROCESS_DEPLOY_DELETE_ERROR";
   /** APPAPI_PROCESS_DEPLOY_INFO_ERROR */ 
  public static final String E4021905_APPAPI_PROCESS_DEPLOY_INFO_ERROR = "4021905_APPAPI_PROCESS_DEPLOY_INFO_ERROR";
   /** APPAPI_PROCESS_DEPLOY_NOT_FOUND */ 
  public static final String E4021906_APPAPI_PROCESS_DEPLOY_NOT_FOUND = "4021906_APPAPI_PROCESS_DEPLOY_NOT_FOUND";

   // API GROUP SYSTEM SETTING REST (2000-2099)
   /** APPAPI_GROUP_SYSTEM_SETTING_LIST_ERROR */ 
  public static final String E4022001_APPAPI_GROUP_SYSTEM_SETTING_LIST_ERROR = "4022001_APPAPI_GROUP_SYSTEM_SETTING_LIST_ERROR";
   /** APPAPI_GROUP_SYSTEM_SETTING_ADD_ERROR */ 
  public static final String E4022002_APPAPI_GROUP_SYSTEM_SETTING_ADD_ERROR = "4022002_APPAPI_GROUP_SYSTEM_SETTING_ADD_ERROR";
   /** APPAPI_GROUP_SYSTEM_SETTING_DELETE_ERROR */ 
  public static final String E4022003_APPAPI_GROUP_SYSTEM_SETTING_DELETE_ERROR = "4022003_APPAPI_GROUP_SYSTEM_SETTING_DELETE_ERROR";
   /** APPAPI_GROUP_SYSTEM_SETTING_NOT_FOUND */ 
  public static final String E4022004_APPAPI_GROUP_SYSTEM_SETTING_NOT_FOUND = "4022004_APPAPI_GROUP_SYSTEM_SETTING_NOT_FOUND";
   /** APPAPI_GROUP_SYSTEM_SETTING_UPDATE_INFO_ERROR */ 
  public static final String E4022005_APPAPI_GROUP_SYSTEM_SETTING_UPDATE_INFO_ERROR = "4022005_APPAPI_GROUP_SYSTEM_SETTING_UPDATE_INFO_ERROR";
   /** APPAPI_GROUP_SYSTEM_SETTING_INFO_ERROR */ 
  public static final String E4022006_APPAPI_GROUP_SYSTEM_SETTING_INFO_ERROR = "4022006_APPAPI_GROUP_SYSTEM_SETTING_INFO_ERROR";

   // API SYSTEM SETTING REST (2100-2199)
   /** APPAPI_SYSTEM_SETTING_LIST_ERROR */ 
  public static final String E4022101_APPAPI_SYSTEM_SETTING_LIST_ERROR = "4022101_APPAPI_SYSTEM_SETTING_LIST_ERROR";
   /** APPAPI_SYSTEM_SETTING_ADD_ERROR */ 
  public static final String E4022102_APPAPI_SYSTEM_SETTING_ADD_ERROR = "4022102_APPAPI_SYSTEM_SETTING_ADD_ERROR";
   /** APPAPI_SYSTEM_SETTING_DELETE_ERROR */ 
  public static final String E4022103_APPAPI_SYSTEM_SETTING_DELETE_ERROR = "4022103_APPAPI_SYSTEM_SETTING_DELETE_ERROR";
   /** APPAPI_SYSTEM_SETTING_NOT_FOUND */ 
  public static final String E4022104_APPAPI_SYSTEM_SETTING_NOT_FOUND = "4022104_APPAPI_SYSTEM_SETTING_NOT_FOUND";
   /** APPAPI_SYSTEM_SETTING_UPDATE_INFO_ERROR */ 
  public static final String E4022105_APPAPI_SYSTEM_SETTING_UPDATE_INFO_ERROR = "4022105_APPAPI_SYSTEM_SETTING_UPDATE_INFO_ERROR";
   /** APPAPI_SYSTEM_SETTING_INFO_ERROR */ 
  public static final String E4022106_APPAPI_SYSTEM_SETTING_INFO_ERROR = "4022106_APPAPI_SYSTEM_SETTING_INFO_ERROR";

   // API CERTIFICATE AUTHORITY REST (2200-2299)
   /** APPAPI_CA_MANAGEMENT_LIST_ERROR */ 
  public static final String E4022201_APPAPI_CA_MANAGEMENT_LIST_ERROR = "4022201_APPAPI_CA_MANAGEMENT_LIST_ERROR";
   /** APPAPI_CA_MANAGEMENT_ADD_ERROR */ 
  public static final String E4022202_APPAPI_CA_MANAGEMENT_ADD_ERROR = "4022202_APPAPI_CA_MANAGEMENT_ADD_ERROR";
   /** APPAPI_CA_MANAGEMENT_UPDATE_INFO_ERROR */ 
  public static final String E4022203_APPAPI_CA_MANAGEMENT_UPDATE_INFO_ERROR = "4022203_APPAPI_CA_MANAGEMENT_UPDATE_INFO_ERROR";
   /** APPAPI_CA_MANAGEMENT_DELETE_ERROR */ 
  public static final String E4022204_APPAPI_CA_MANAGEMENT_DELETE_ERROR = "4022204_APPAPI_CA_MANAGEMENT_DELETE_ERROR";
   /** APPAPI_CA_MANAGEMENT_INFO_ERROR */ 
  public static final String E4022205_APPAPI_CA_MANAGEMENT_INFO_ERROR = "4022205_APPAPI_CA_MANAGEMENT_INFO_ERROR";
   /** APPAPI_CA_MANAGEMENT_NOT_FOUND */ 
  public static final String E4022206_APPAPI_CA_MANAGEMENT_NOT_FOUND = "4022206_APPAPI_CA_MANAGEMENT_NOT_FOUND";

   // API ACCOUNT ORG REST (2300-2399)
   /** APPAPI_ACCOUNT_ORG_LIST_ERROR */ 
  public static final String E4022301_APPAPI_ACCOUNT_ORG_LIST_ERROR = "4022301_APPAPI_ACCOUNT_ORG_LIST_ERROR";
   /** APPAPI_ACCOUNT_ORG_ADD_ERROR */ 
  public static final String E4022302_APPAPI_ACCOUNT_ORG_ADD_ERROR = "4022302_APPAPI_ACCOUNT_ORG_ADD_ERROR";
   /** APPAPI_ACCOUNT_ORG_UPDATE_INFO_ERROR */ 
  public static final String E4022303_APPAPI_ACCOUNT_ORG_UPDATE_INFO_ERROR = "4022303_APPAPI_ACCOUNT_ORG_UPDATE_INFO_ERROR";
   /** APPAPI_ACCOUNT_ORG_DELETE_ERROR */ 
  public static final String E4022304_APPAPI_ACCOUNT_ORG_DELETE_ERROR = "4022304_APPAPI_ACCOUNT_ORG_DELETE_ERROR";
   /** APPAPI_ACCOUNT_ORG_INFO_ERROR */ 
  public static final String E4022305_APPAPI_ACCOUNT_ORG_INFO_ERROR = "4022305_APPAPI_ACCOUNT_ORG_INFO_ERROR";
   /** APPAPI_ACCOUNT_ORG_NOT_FOUND */ 
  public static final String E4022306_APPAPI_ACCOUNT_ORG_NOT_FOUND = "4022306_APPAPI_ACCOUNT_ORG_NOT_FOUND";

   // API REPOSITORY REST (2400-2499)
   /** APPAPI_REPOSITORY_LIST_ERROR */ 
  public static final String E4022401_APPAPI_REPOSITORY_LIST_ERROR = "4022401_APPAPI_REPOSITORY_LIST_ERROR";
   /** APPAPI_REPOSITORY_ADD_ERROR */ 
  public static final String E4022402_APPAPI_REPOSITORY_ADD_ERROR = "4022402_APPAPI_REPOSITORY_ADD_ERROR";
   /** APPAPI_REPOSITORY_UPDATE_INFO_ERROR */ 
  public static final String E4022403_APPAPI_REPOSITORY_UPDATE_INFO_ERROR = "4022403_APPAPI_REPOSITORY_UPDATE_INFO_ERROR";
   /** APPAPI_REPOSITORY_NOT_FOUND */ 
  public static final String E4022404_APPAPI_REPOSITORY_NOT_FOUND = "4022404_APPAPI_REPOSITORY_NOT_FOUND";
   /** APPAPI_REPOSITORY_DELETE_ERROR */ 
  public static final String E4022405_APPAPI_REPOSITORY_DELETE_ERROR = "4022405_APPAPI_REPOSITORY_DELETE_ERROR";
   /** APPAPI_REPOSITORY_INFO_ERROR */ 
  public static final String E4022406_APPAPI_REPOSITORY_INFO_ERROR = "4022406_APPAPI_REPOSITORY_INFO_ERROR";

   // API ROLE FOR TEAM REST (2500-2599)
   /** APPAPI_ROLE_FOR_TEAM_LIST_ERROR */ 
  public static final String E4022501_APPAPI_ROLE_FOR_TEAM_LIST_ERROR = "4022501_APPAPI_ROLE_FOR_TEAM_LIST_ERROR";
   /** APPAPI_ROLE_FOR_TEAM_ADD_ERROR */ 
  public static final String E4022502_APPAPI_ROLE_FOR_TEAM_ADD_ERROR = "4022502_APPAPI_ROLE_FOR_TEAM_ADD_ERROR";
   /** APPAPI_ROLE_FOR_TEAM_UPDATE_INFO_ERROR */ 
  public static final String E4022503_APPAPI_ROLE_FOR_TEAM_UPDATE_INFO_ERROR = "4022503_APPAPI_ROLE_FOR_TEAM_UPDATE_INFO_ERROR";
   /** APPAPI_ROLE_FOR_TEAM_NOT_FOUND */ 
  public static final String E4022504_APPAPI_ROLE_FOR_TEAM_NOT_FOUND = "4022504_APPAPI_ROLE_FOR_TEAM_NOT_FOUND";
   /** APPAPI_ROLE_FOR_TEAM_DELETE_ERROR */ 
  public static final String E4022505_APPAPI_ROLE_FOR_TEAM_DELETE_ERROR = "4022505_APPAPI_ROLE_FOR_TEAM_DELETE_ERROR";
   /** APPAPI_ROLE_FOR_TEAM_INFO_ERROR */ 
  public static final String E4022506_APPAPI_ROLE_FOR_TEAM_INFO_ERROR = "4022506_APPAPI_ROLE_FOR_TEAM_INFO_ERROR";
   /** APPAPI_ROLE_FOR_TEAM_NOT_FOUND_ROLE_ERROR */ 
  public static final String E4022507_APPAPI_ROLE_FOR_TEAM_NOT_FOUND_ROLE_ERROR = "4022507_APPAPI_ROLE_FOR_TEAM_NOT_FOUND_ROLE_ERROR";

   // API ROLE FOR COMPANY REST (2600-2699)
   /** APPAPI_ROLE_FOR_COMPANY_LIST_ERROR */ 
  public static final String E4022601_APPAPI_ROLE_FOR_COMPANY_LIST_ERROR = "4022601_APPAPI_ROLE_FOR_COMPANY_LIST_ERROR";
   /** APPAPI_ROLE_FOR_COMPANY_ADD_ERROR */ 
  public static final String E4022602_APPAPI_ROLE_FOR_COMPANY_ADD_ERROR = "4022602_APPAPI_ROLE_FOR_COMPANY_ADD_ERROR";
   /** APPAPI_ROLE_FOR_COMAPNY_UPDATE_INFO_ERROR */ 
  public static final String E4022603_APPAPI_ROLE_FOR_COMAPNY_UPDATE_INFO_ERROR = "4022603_APPAPI_ROLE_FOR_COMAPNY_UPDATE_INFO_ERROR";
   /** APPAPI_ROLE_FOR_COMPANY_NOT_FOUND */ 
  public static final String E4022604_APPAPI_ROLE_FOR_COMPANY_NOT_FOUND = "4022604_APPAPI_ROLE_FOR_COMPANY_NOT_FOUND";
   /** APPAPI_ROLE_FOR_COMPANY_DELETE_ERROR */ 
  public static final String E4022605_APPAPI_ROLE_FOR_COMPANY_DELETE_ERROR = "4022605_APPAPI_ROLE_FOR_COMPANY_DELETE_ERROR";
   /** APPAPI_ROLE_FOR_COMPANY_INFO_ERROR */ 
  public static final String E4022606_APPAPI_ROLE_FOR_COMPANY_INFO_ERROR = "4022606_APPAPI_ROLE_FOR_COMPANY_INFO_ERROR";
   /** APPAPI_ROLE_FOR_COMPANY_NOT_FOUND_ORG_ERROR */ 
  public static final String E4022607_APPAPI_ROLE_FOR_COMPANY_NOT_FOUND_ORG_ERROR = "4022607_APPAPI_ROLE_FOR_COMPANY_NOT_FOUND_ORG_ERROR";
   /** APPAPI_ROLE_FOR_COMPANY_NOT_FOUND_COMPANY_ERROR */ 
  public static final String E4022608_APPAPI_ROLE_FOR_COMPANY_NOT_FOUND_COMPANY_ERROR = "4022608_APPAPI_ROLE_FOR_COMPANY_NOT_FOUND_COMPANY_ERROR";

   // API CATEGORY REST (2700-2799)
   /** APPAPI_CATEGORY_LIST_ERROR */ 
  public static final String E4022701_APPAPI_CATEGORY_LIST_ERROR = "4022701_APPAPI_CATEGORY_LIST_ERROR";
   /** APPAPI_CATEGORY_ADD_ERROR */ 
  public static final String E4022702_APPAPI_CATEGORY_ADD_ERROR = "4022702_APPAPI_CATEGORY_ADD_ERROR";
   /** APPAPI_CATEGORY_UPDATE_INFO_ERROR */ 
  public static final String E4022703_APPAPI_CATEGORY_UPDATE_INFO_ERROR = "4022703_APPAPI_CATEGORY_UPDATE_INFO_ERROR";
   /** APPAPI_CATEGORY_DELETE_ERROR */ 
  public static final String E4022704_APPAPI_CATEGORY_DELETE_ERROR = "4022704_APPAPI_CATEGORY_DELETE_ERROR";
   /** APPAPI_CATEGORY_INFO_ERROR */ 
  public static final String E4022705_APPAPI_CATEGORY_INFO_ERROR = "4022705_APPAPI_CATEGORY_INFO_ERROR";
   /** APPAPI_CATEGORY_NOT_FOUND */ 
  public static final String E4022706_APPAPI_CATEGORY_NOT_FOUND = "4022706_APPAPI_CATEGORY_NOT_FOUND";

   // API EMAIL TEMPLATE REST (2800-2899)
   /** APPAPI_EMAIL_TEMPLATE_LIST_ERROR */ 
  public static final String E4022801_APPAPI_EMAIL_TEMPLATE_LIST_ERROR = "4022801_APPAPI_EMAIL_TEMPLATE_LIST_ERROR";
   /** APPAPI_EMAIL_TEMPLATE_ADD_ERROR */ 
  public static final String E4022802_APPAPI_EMAIL_TEMPLATE_ADD_ERROR = "4022802_APPAPI_EMAIL_TEMPLATE_ADD_ERROR";
   /** APPAPI_EMAIL_TEMPLATE_UPDATE_INFO_ERROR */ 
  public static final String E4022803_APPAPI_EMAIL_TEMPLATE_UPDATE_INFO_ERROR = "4022803_APPAPI_EMAIL_TEMPLATE_UPDATE_INFO_ERROR";
   /** APPAPI_EMAIL_TEMPLATE_NOT_FOUND */ 
  public static final String E4022804_APPAPI_EMAIL_TEMPLATE_NOT_FOUND = "4022804_APPAPI_EMAIL_TEMPLATE_NOT_FOUND";
   /** APPAPI_EMAIL_TEMPLATE_DELETE_ERROR */ 
  public static final String E4022805_APPAPI_EMAIL_TEMPLATE_DELETE_ERROR = "4022805_APPAPI_EMAIL_TEMPLATE_DELETE_ERROR";
   /** APPAPI_EMAIL_TEMPLATE_INFO_ERROR */ 
  public static final String E4022806_APPAPI_EMAIL_TEMPLATE_INFO_ERROR = "4022806_APPAPI_EMAIL_TEMPLATE_INFO_ERROR";

   // API_FORM_REST (2900-2999)
   /** APPAPI_FORM_LIST_ERROR */ 
  public static final String E4022901_APPAPI_FORM_LIST_ERROR = "4022901_APPAPI_FORM_LIST_ERROR";
   /** APPAPI_FORM_ADD_ERROR */ 
  public static final String E4022902_APPAPI_FORM_ADD_ERROR = "4022902_APPAPI_FORM_ADD_ERROR";
   /** APPAPI_FORM_UPDATE_INFO_ERROR */ 
  public static final String E4022903_APPAPI_FORM_UPDATE_INFO_ERROR = "4022903_APPAPI_FORM_UPDATE_INFO_ERROR";
   /** APPAPI_FORM_NOT_FOUND */ 
  public static final String E4022904_APPAPI_FORM_NOT_FOUND = "4022904_APPAPI_FORM_NOT_FOUND";
   /** APPAPI_FORM_DELETE_ERROR */ 
  public static final String E4022905_APPAPI_FORM_DELETE_ERROR = "4022905_APPAPI_FORM_DELETE_ERROR";
   /** APPAPI_FORM_INFO_ERROR */ 
  public static final String E4022906_APPAPI_FORM_INFO_ERROR = "4022906_APPAPI_FORM_INFO_ERROR";

   // API_ROLE_FOR_ITEM_REST (3000-3099)
   /** APPAPI_ROLE_FOR_ITEM_LIST_ERROR */ 
  public static final String E4023001_APPAPI_ROLE_FOR_ITEM_LIST_ERROR = "4023001_APPAPI_ROLE_FOR_ITEM_LIST_ERROR";
   /** APPAPI_ROLE_FOR_ITEM_ADD_ERROR */ 
  public static final String E4023002_APPAPI_ROLE_FOR_ITEM_ADD_ERROR = "4023002_APPAPI_ROLE_FOR_ITEM_ADD_ERROR";
   /** APPAPI_ROLE_FOR_ITEM_UPDATE_INFO_ERROR */ 
  public static final String E4023003_APPAPI_ROLE_FOR_ITEM_UPDATE_INFO_ERROR = "4023003_APPAPI_ROLE_FOR_ITEM_UPDATE_INFO_ERROR";
   /** APPAPI_ROLE_FOR_ITEM_NOT_FOUND */ 
  public static final String E4023004_APPAPI_ROLE_FOR_ITEM_NOT_FOUND = "4023004_APPAPI_ROLE_FOR_ITEM_NOT_FOUND";
   /** APPAPI_ROLE_FOR_ITEM_DELETE_ERROR */ 
  public static final String E4023005_APPAPI_ROLE_FOR_ITEM_DELETE_ERROR = "4023005_APPAPI_ROLE_FOR_ITEM_DELETE_ERROR";
   /** APPAPI_ROLE_FOR_ITEM_INFO_ERROR */ 
  public static final String E4023006_APPAPI_ROLE_FOR_ITEM_INFO_ERROR = "4023006_APPAPI_ROLE_FOR_ITEM_INFO_ERROR";
   /** APPAPI_ROLE_FOR_ITEM_NOT_FOUND_ITEM_ERROR */ 
  public static final String E4023006_APPAPI_ROLE_FOR_ITEM_NOT_FOUND_ITEM_ERROR = "4023006_APPAPI_ROLE_FOR_ITEM_NOT_FOUND_ITEM_ERROR";

   // API_GOURP_CONSTANT_REST (3100-3199)
   /** APPAPI_GROUP_CONSTANT_LIST_ERROR */ 
  public static final String E4023101_APPAPI_GROUP_CONSTANT_LIST_ERROR = "4023101_APPAPI_GROUP_CONSTANT_LIST_ERROR";
   /** APPAPI_GROUP_CONSTANT_ADD_ERROR */ 
  public static final String E4023102_APPAPI_GROUP_CONSTANT_ADD_ERROR = "4023102_APPAPI_GROUP_CONSTANT_ADD_ERROR";
   /** APPAPI_GROUP_CONSTANT_UPDATE_INFO_ERROR */ 
  public static final String E4023103_APPAPI_GROUP_CONSTANT_UPDATE_INFO_ERROR = "4023103_APPAPI_GROUP_CONSTANT_UPDATE_INFO_ERROR";
   /** APPAPI_GROUP_CONSTANT_NOT_FOUND */ 
  public static final String E4023104_APPAPI_GROUP_CONSTANT_NOT_FOUND = "4023104_APPAPI_GROUP_CONSTANT_NOT_FOUND";
   /** APPAPI_GROUP_CONSTANT_DELETE_ERROR */ 
  public static final String E4023105_APPAPI_GROUP_CONSTANT_DELETE_ERROR = "4023105_APPAPI_GROUP_CONSTANT_DELETE_ERROR";
   /** APPAPI_GROUP_CONSTANT_INFO_ERROR */ 
  public static final String E4023106_APPAPI_GROUP_CONSTANT_INFO_ERROR = "4023106_APPAPI_GROUP_CONSTANT_INFO_ERROR";

   // API_CONSTANT_REST (3200-3299)
   /** APPAPI_CONSTANT_LIST_ERROR */ 
  public static final String E4023201_APPAPI_CONSTANT_LIST_ERROR = "4023201_APPAPI_CONSTANT_LIST_ERROR";
   /** APPAPI_CONSTANT_ADD_ERROR */ 
  public static final String E4023202_APPAPI_CONSTANT_ADD_ERROR = "4023202_APPAPI_CONSTANT_ADD_ERROR";
   /** APPAPI_CONSTANT_UPDATE_INFO_ERROR */ 
  public static final String E4023203_APPAPI_CONSTANT_UPDATE_INFO_ERROR = "4023203_APPAPI_CONSTANT_UPDATE_INFO_ERROR";
   /** APPAPI_CONSTANT_NOT_FOUND */ 
  public static final String E4023204_APPAPI_CONSTANT_NOT_FOUND = "4023204_APPAPI_CONSTANT_NOT_FOUND";
   /** APPAPI_CONSTANT_DELETE_ERROR */ 
  public static final String E4023205_APPAPI_CONSTANT_DELETE_ERROR = "4023205_APPAPI_CONSTANT_DELETE_ERROR";
   /** APPAPI_CONSTANT_INFO_ERROR */ 
  public static final String E4023206_APPAPI_CONSTANT_INFO_ERROR = "4023206_APPAPI_CONSTANT_INFO_ERROR";

   // API POSITION PATH REST (3300-3399)
   /** APPAPI_POSITION_PATH_ADD_ERROR */ 
  public static final String E4023301_APPAPI_POSITION_PATH_ADD_ERROR = "4023301_APPAPI_POSITION_PATH_ADD_ERROR";
   /** APPAPI_POSITION_PATH_UPDATE_INFO_ERROR */ 
  public static final String E4023302_APPAPI_POSITION_PATH_UPDATE_INFO_ERROR = "4023302_APPAPI_POSITION_PATH_UPDATE_INFO_ERROR";
   /** APPAPI_POSITION_PATH_NOT_FOUND_ERROR */ 
  public static final String E4023303_APPAPI_POSITION_PATH_NOT_FOUND_ERROR = "4023303_APPAPI_POSITION_PATH_NOT_FOUND_ERROR";
   /** APPAPI_POSITION_PATH_DELETE_ERROR */ 
  public static final String E4023304_APPAPI_POSITION_PATH_DELETE_ERROR = "4023304_APPAPI_POSITION_PATH_DELETE_ERROR";

   // API DAY OFF REST (3400-3499)
   /** APPAPI_DAY_OFF_NOT_FOUND_ERROR */ 
  public static final String E4023401_APPAPI_DAY_OFF_NOT_FOUND_ERROR = "4023303_APPAPI_DAY_OFF_NOT_FOUND_ERROR";
   /** APPAPI_DAY_OFF_LIST_ERROR */ 
  public static final String E4023402_APPAPI_DAY_OFF_LIST_ERROR = "4023402_APPAPI_DAY_OFF_LIST_ERROR";
   /** APPAPI_DAY_OFF_UPDATE_INFO_ERROR */ 
  public static final String E4023403_APPAPI_DAY_OFF_UPDATE_INFO_ERROR = "4023403_APPAPI_DAY_OFF_UPDATE_INFO_ERROR";

   // API PROCESS PARAM REST (3500-3599)
   /** APPAPI_PROCESS_PARAM_ADD_ERROR */ 
  public static final String E4023501_APPAPI_PROCESS_PARAM_ADD_ERROR = "4023501_APPAPI_PROCESS_PARAM_ADD_ERROR";
   /** APPAPI_PROCESS_PARAM_UPDATE_INFO_ERROR */ 
  public static final String E4023502_APPAPI_PROCESS_PARAM_UPDATE_INFO_ERROR = "4023502_APPAPI_PROCESS_PARAM_UPDATE_INFO_ERROR";
   /** APPAPI_PROCESS_PARAM_DELETE_ERROR */ 
  public static final String E4023503_APPAPI_PROCESS_PARAM_DELETE_ERROR = "4023503_APPAPI_PROCESS_PARAM_DELETE_ERROR";
   /** APPAPI_PROCESS_PARAM_NOT_FOUND */ 
  public static final String E4023504_APPAPI_PROCESS_PARAM_NOT_FOUND = "4023504_APPAPI_PROCESS_PARAM_NOT_FOUND";

   // API PROCESS BUTTON REST (3600-3699)
   /** APPAPI_PROCESS_BUTTON_ADD_ERROR */ 
  public static final String E4023601_APPAPI_PROCESS_BUTTON_ADD_ERROR = "4023601_APPAPI_PROCESS_BUTTON_ADD_ERROR";
   /** APPAPI_PROCESS_BUTTON_UPDATE_INFO_ERROR */ 
  public static final String E4023602_APPAPI_PROCESS_BUTTON_UPDATE_INFO_ERROR = "4023602_APPAPI_PROCESS_BUTTON_UPDATE_INFO_ERROR";
   /** APPAPI_PROCESS_BUTTON_DELETE_ERROR */ 
  public static final String E4023603_APPAPI_PROCESS_BUTTON_DELETE_ERROR = "4023603_APPAPI_PROCESS_BUTTON_DELETE_ERROR";
   /** APPAPI_PROCESS_BUTTON_NOT_FOUND */ 
  public static final String E4023604_APPAPI_PROCESS_BUTTON_NOT_FOUND = "4023604_APPAPI_PROCESS_BUTTON_NOT_FOUND";
   /** APPAPI_PROCESS_BUTTON_ID_NOT_FOUND */ 
  public static final String E4023605_APPAPI_PROCESS_BUTTON_ID_NOT_FOUND = "4023605_APPAPI_PROCESS_BUTTON_ID_NOT_FOUND";

   // API PROCESS STATUS REST (3700-3799)
   /** APPAPI_PROCESS_STATUS_ADD_ERROR */ 
  public static final String E4023701_APPAPI_PROCESS_STATUS_ADD_ERROR = "4023701_APPAPI_PROCESS_STATUS_ADD_ERROR";
   /** APPAPI_PROCESS_STATUS_UPDATE_INFO_ERROR */ 
  public static final String E4023702_APPAPI_PROCESS_STATUS_UPDATE_INFO_ERROR = "4023702_APPAPI_PROCESS_STATUS_UPDATE_INFO_ERROR";
   /** APPAPI_PROCESS_STATUS_DELETE_ERROR */ 
  public static final String E4023703_APPAPI_PROCESS_STATUS_DELETE_ERROR = "4023703_APPAPI_PROCESS_STATUS_DELETE_ERROR";
   /** APPAPI_PROCESS_STATUS_NOT_FOUND */ 
  public static final String E4023704_APPAPI_PROCESS_STATUS_NOT_FOUND = "4023704_APPAPI_PROCESS_STATUS_NOT_FOUND";

   // API PROCESS PERMISSION REST (3800-3899)
   /** APPAPI_PROCESS_PERMISSION_ADD_ERROR */ 
  public static final String E4023801_APPAPI_PROCESS_PERMISSION_ADD_ERROR = "4023801_APPAPI_PROCESS_PERMISSION_ADD_ERROR";
   /** APPAPI_PROCESS_PERMISSION_UPDATE_INFO_ERROR */ 
  public static final String E4023802_APPAPI_PROCESS_PERMISSION_UPDATE_INFO_ERROR = "4023802_APPAPI_PROCESS_PERMISSION_UPDATE_INFO_ERROR";
   /** APPAPI_PROCESS_PERMISSION_DELETE_ERROR */ 
  public static final String E4023803_APPAPI_PROCESS_PERMISSION_DELETE_ERROR = "4023803_APPAPI_PROCESS_PERMISSION_DELETE_ERROR";
   /** APPAPI_PROCESS_PERMISSION_NOT_FOUND */ 
  public static final String E4023804_APPAPI_PROCESS_PERMISSION_NOT_FOUND = "4023804_APPAPI_PROCESS_PERMISSION_NOT_FOUND";
   /** APPAPI_PROCESS_PERMISSION_ID_NOT_FOUND */ 
  public static final String E4023805_APPAPI_PROCESS_PERMISSION_ID_NOT_FOUND = "4023805_APPAPI_PROCESS_PERMISSION_ID_NOT_FOUND";

   // API PROCESS STEP REST (3900-3999)
   /** APPAPI_PROCESS_STEP_ADD_ERROR */ 
  public static final String E4023901_APPAPI_PROCESS_STEP_ADD_ERROR = "4023901_APPAPI_PROCESS_STEP_ADD_ERROR";
   /** APPAPI_PROCESS_STEP_UPDATE_INFO_ERROR */ 
  public static final String E4023902_APPAPI_PROCESS_STEP_UPDATE_INFO_ERROR = "4023902_APPAPI_PROCESS_STEP_UPDATE_INFO_ERROR";
   /** APPAPI_PROCESS_STEP_DELETE_ERROR */ 
  public static final String E4023903_APPAPI_PROCESS_STEP_DELETE_ERROR = "4023903_APPAPI_PROCESS_STEP_DELETE_ERROR";
   /** APPAPI_PROCESS_STEP_NOT_FOUND */ 
  public static final String E4023904_APPAPI_PROCESS_STEP_NOT_FOUND = "4023904_APPAPI_PROCESS_STEP_NOT_FOUND";
   /** APPAPI_PROCESS_STEP_ID_NOT_FOUND */ 
  public static final String E4023905_APPAPI_PROCESS_STEP_ID_NOT_FOUND = "4023905_APPAPI_PROCESS_STEP_ID_NOT_FOUND";

   // API SLA CONFIG REST (4000-4099)
   /** APPAPI_SLA_CONFIG_LIST_ERROR */ 
  public static final String E4024001_APPAPI_SLA_CONFIG_LIST_ERROR = "4024001_APPAPI_SLA_CONFIG_LIST_ERROR";
   /** APPAPI_SLA_CONFIG_DELETE_ERROR */ 
  public static final String E4024002_APPAPI_SLA_CONFIG_DELETE_ERROR = "4024002_APPAPI_SLA_CONFIG_DELETE_ERROR";

   // API SLA CONFIG REST (4100-4199)
   /** APPAPI_SLA_CONFIG_DETAIL_LIST_ERROR */ 
  public static final String E4024101_APPAPI_SLA_CONFIG_DETAIL_LIST_ERROR = "4024101_APPAPI_SLA_CONFIG_DETAIL_LIST_ERROR";
   /** APPAPI_SLA_CONFIG_DETAIL_DELETE_ERROR */ 
  public static final String E4024102_APPAPI_SLA_CONFIG_DETAIL_DELETE_ERROR = "4024102_APPAPI_SLA_CONFIG_DETAIL_DELETE_ERROR";
   /** APPAPI_PROCESS_ALREADY_EXISTS */ 
  public static final String E4021406_APPAPI_PROCESS_ALREADY_EXISTS = "4021406_APPAPI_PROCESS_ALREADY_EXISTS";

   // API ACCOUNT TEAM REST (4200-4299)
   /** APPAPI_ACCOUNT_TEAM_ADD_ERROR */ 
  public static final String E4024201_APPAPI_ACCOUNT_TEAM_ADD_ERROR = "4024201_APPAPI_ACCOUNT_TEAM_ADD_ERROR";
   /** APPAPI_ACCOUNT_TEAM_UPDATE_INFO_ERROR */ 
  public static final String E4024202_APPAPI_ACCOUNT_TEAM_UPDATE_INFO_ERROR = "4024202_APPAPI_ACCOUNT_TEAM_UPDATE_INFO_ERROR";
   /** APPAPI_ACCOUNT_TEAM_DELETE_ERROR */ 
  public static final String E4024203_APPAPI_ACCOUNT_TEAM_DELETE_ERROR = "4024203_APPAPI_ACCOUNT_TEAM_DELETE_ERROR";
   /** APPAPI_ACCOUNT_TEAM_NOT_FOUND */ 
  public static final String E4024204_APPAPI_ACCOUNT_TEAM_NOT_FOUND = "4024204_APPAPI_ACCOUNT_TEAM_NOT_FOUND";
   /** APPAPI_ACCOUNT_TEAM_ID_NOT_FOUND */ 
  public static final String E4024205_APPAPI_ACCOUNT_TEAM_ID_NOT_FOUND = "4024205_APPAPI_ACCOUNT_TEAM_ID_NOT_FOUND";
   /** APPAPI_ACCOUNT_TEAM_CALL_SP_UPDATE_ROLE_ACCOUNT_TEAM */ 
  public static final String E4024206_APPAPI_ACCOUNT_TEAM_CALL_SP_UPDATE_ROLE_ACCOUNT_TEAM = "4024206_APPAPI_ACCOUNT_TEAM_CALL_SP_UPDATE_ROLE_ACCOUNT_TEAM";
   /** APPAPI_PROCESS_ACCOUNT_TEAM_ERROR */ 
  public static final String E4024207_APPAPI_PROCESS_ACCOUNT_TEAM_ERROR = "4024207_APPAPI_PROCESS_ACCOUNT_TEAM_ERROR";
   /** APPAPI_ACCOUNT_CALL_SP_UPDATE_ROLE_FOR_ACCOUNT */ 
  public static final String E402810_APPAPI_ACCOUNT_CALL_SP_UPDATE_ROLE_FOR_ACCOUNT = "402810_APPAPI_ACCOUNT_CALL_SP_UPDATE_ROLE_FOR_ACCOUNT";

   // API_ROLE_FOR_PROCESS_REST (4300-4399)
   /** APPAPI_ROLE_FOR_PROCESS_LIST_ERROR */ 
  public static final String E4024301_APPAPI_ROLE_FOR_PROCESS_LIST_ERROR = "4024301_APPAPI_ROLE_FOR_PROCESS_LIST_ERROR";
   /** APPAPI_ROLE_FOR_PROCESS_ADD_ERROR */ 
  public static final String E4024302_APPAPI_ROLE_FOR_PROCESS_ADD_ERROR = "4024302_APPAPI_ROLE_FOR_PROCESS_ADD_ERROR";
   /** APPAPI_ROLE_FOR_PROCESS_UPDATE_INFO_ERROR */ 
  public static final String E4024303_APPAPI_ROLE_FOR_PROCESS_UPDATE_INFO_ERROR = "4024303_APPAPI_ROLE_FOR_PROCESS_UPDATE_INFO_ERROR";
   /** APPAPI_ROLE_FOR_PROCESS_NOT_FOUND */ 
  public static final String E4024304_APPAPI_ROLE_FOR_PROCESS_NOT_FOUND = "4024304_APPAPI_ROLE_FOR_PROCESS_NOT_FOUND";
   /** APPAPI_ROLE_FOR_PROCESS_DELETE_ERROR */ 
  public static final String E4024305_APPAPI_ROLE_FOR_PROCESS_DELETE_ERROR = "4024305_APPAPI_ROLE_FOR_PROCESS_DELETE_ERROR";
   /** APPAPI_ROLE_FOR_PROCESS_INFO_ERROR */ 
  public static final String E4024306_APPAPI_ROLE_FOR_PROCESS_INFO_ERROR = "4024306_APPAPI_ROLE_FOR_PROCESS_INFO_ERROR";
   /** APPAPI_PROCESS_DEPLOY_ERROR */ 
  public static final String E4021407_APPAPI_PROCESS_DEPLOY_ERROR = "4021407_APPAPI_PROCESS_DEPLOY_ERROR";
   /** APPAPI_PROCESS_DEPLOY_CLONE_SLA_ERROR */ 
  public static final String E4021408_APPAPI_PROCESS_DEPLOY_CLONE_SLA_ERROR = "4021408_APPAPI_PROCESS_DEPLOY_CLONE_SLA_ERROR";
   /** APPAPI_PROCESS_DEPLOY_CLONE_ROLE_ERROR */ 
  public static final String E4021409_APPAPI_PROCESS_DEPLOY_CLONE_ROLE_ERROR = "4021409_APPAPI_PROCESS_DEPLOY_CLONE_ROLE_ERROR";

   // API DOCUMENT REST (4400-4499)
   /** APPAPI_DOCUMENT_LIST_ERROR */ 
  public static final String E4024401_APPAPI_DOCUMENT_LIST_ERROR = "4024401_APPAPI_DOCUMENT_LIST_ERROR";
   /** APPAPI_DOCUMENT_ADD_ERROR */ 
  public static final String E4024402_APPAPI_DOCUMENT_ADD_ERROR = "4024402_APPAPI_DOCUMENT_ADD_ERROR";
   /** APPAPI_DOCUMENT_ACTION_ERROR */ 
  public static final String E4024403_APPAPI_DOCUMENT_ACTION_ERROR = "4024403_APPAPI_DOCUMENT_ACTION_ERROR";
   /** APPAPI_DOCUMENT_NOT_FOUND */ 
  public static final String E4024404_APPAPI_DOCUMENT_NOT_FOUND = "4024404_APPAPI_DOCUMENT_NOT_FOUND";
   /** APPAPI_DOCUMENT_DELETE_ERROR */ 
  public static final String E4024405_APPAPI_DOCUMENT_DELETE_ERROR = "4024405_APPAPI_DOCUMENT_DELETE_ERROR";
   /** APPAPI_DOCUMENT_INFO_ERROR */ 
  public static final String E4024406_APPAPI_DOCUMENT_INFO_ERROR = "4024406_APPAPI_DOCUMENT_INFO_ERROR";
   /** APPAPI_BUSINESS_ALREADY_EXISTS */ 
  public static final String E4021306_APPAPI_BUSINESS_ALREADY_EXISTS = "4021306_APPAPI_BUSINESS_ALREADY_EXISTS";

   // API ROLE FOR ACCOUNT REST (4500-4599)
   /** APPAPI_ROLE_FOR_ACCOUNT_ADD_ERROR */ 
  public static final String E4024501_APPAPI_ROLE_FOR_ACCOUNT_ADD_ERROR = "4024501_APPAPI_ROLE_FOR_ACCOUNT_ADD_ERROR";
   /** APPAPI_ROLE_FOR_ACCOUNT_DELETE_ERROR */ 
  public static final String E4024502_APPAPI_ROLE_FOR_ACCOUNT_DELETE_ERROR = "4024502_APPAPI_ROLE_FOR_ACCOUNT_DELETE_ERROR";
   /** APPAPI_ROLE_FOR_ACCOUNT_NOT_FOUND_ERROR */ 
  public static final String E4024503_APPAPI_ROLE_FOR_ACCOUNT_NOT_FOUND_ERROR = "4024503_APPAPI_ROLE_FOR_ACCOUNT_NOT_FOUND_ERROR";
   /** APPAPI_ROLE_FOR_ACCOUNT_LIST_ERROR */ 
  public static final String E4024504_APPAPI_ROLE_FOR_ACCOUNT_LIST_ERROR = "4024504_APPAPI_ROLE_FOR_ACCOUNT_LIST_ERROR";

   // API ROLE FOR POSITION REST (4600-4699)
   /** APPAPI_ROLE_FOR_POSITION_ADD_ERROR */ 
  public static final String E4024601_APPAPI_ROLE_FOR_POSITION_ADD_ERROR = "4024601_APPAPI_ROLE_FOR_POSITION_ADD_ERROR";
   /** APPAPI_ROLE_FOR_POSITION_DELETE_ERROR */ 
  public static final String E4024602_APPAPI_ROLE_FOR_POSITION_DELETE_ERROR = "4024602_APPAPI_ROLE_FOR_POSITION_DELETE_ERROR";
   /** APPAPI_ROLE_FOR_POSITION_NOT_FOUND_ERROR */ 
  public static final String E4024603_APPAPI_ROLE_FOR_POSITION_NOT_FOUND_ERROR = "4024603_APPAPI_ROLE_FOR_POSITION_NOT_FOUND_ERROR";
   /** APPAPI_ROLE_FOR_POSITION_LIST_ERROR */ 
  public static final String E4024604_APPAPI_ROLE_FOR_POSITION_LIST_ERROR = "4024604_APPAPI_ROLE_FOR_POSITION_LIST_ERROR";
   /** APPAPI_ACCOUNT_TEAM_CALL_SP_UPDATE_ROLE_FOR_POSITION */ 
  public static final String E4024206_APPAPI_ACCOUNT_TEAM_CALL_SP_UPDATE_ROLE_FOR_POSITION = "4024206_APPAPI_ACCOUNT_TEAM_CALL_SP_UPDATE_ROLE_FOR_POSITION";

   // API DASH BOARD REST (4700-4799)
   /** APPAPI_DASH_BOARD_LIST_ERROR */ 
  public static final String E4024701_APPAPI_DASH_BOARD_LIST_ERROR = "4024701_APPAPI_DASH_BOARD_LIST_ERROR";
   /** APPAPI_DASH_BOARD_TODO_ERROR */ 
  public static final String E4024702_APPAPI_DASH_BOARD_TODO_ERROR = "4024702_APPAPI_DASH_BOARD_TODO_ERROR";
   /** APPAPI_DASH_BOARD_MY_DOCUMENT_ERROR */ 
  public static final String E4024703_APPAPI_DASH_BOARD_MY_DOCUMENT_ERROR = "4024703_APPAPI_DASH_BOARD_MY_DOCUMENT_ERROR";
   /** APPAPI_DASH_BOARD_TOTAL_ERROR */ 
  public static final String E4024704_APPAPI_DASH_BOARD_TOTAL_ERROR = "4024704_APPAPI_DASH_BOARD_TOTAL_ERROR";
   /** APPAPI_DASH_BOARD_DOCUMENT_TASK_ERROR */ 
  public static final String E4024705_APPAPI_DASH_BOARD_DOCUMENT_TASK_ERROR = "4024705_APPAPI_DASH_BOARD_DOCUMENT_TASK_ERROR";
   /** APPAPI_DASH_BOARD_DOCUMENT_TASK_READ_ERROR */ 
  public static final String E4024706_APPAPI_DASH_BOARD_DOCUMENT_TASK_READ_ERROR = "4024706_APPAPI_DASH_BOARD_DOCUMENT_TASK_READ_ERROR";
   /** APPAPI_DASH_BOARD_DOCUMENT_TASK_DELETE_ERROR */ 
  public static final String E4024707_APPAPI_DASH_BOARD_DOCUMENT_TASK_DELETE_ERROR = "4024707_APPAPI_DASH_BOARD_DOCUMENT_TASK_DELETE_ERROR";

   // API DOWNLOAD FILE REST (4800-4899)
   /** APPAPI_DOWNLOAD_FILE_LOCAL_ERROR */ 
  public static final String E4024801_APPAPI_DOWNLOAD_FILE_LOCAL_ERROR = "4024801_APPAPI_DOWNLOAD_FILE_LOCAL_ERROR";
   /** APPAPI_DOWNLOAD_FILE_PROCESS_ERROR */ 
  public static final String E4024802_APPAPI_DOWNLOAD_FILE_PROCESS_ERROR = "4024802_APPAPI_DOWNLOAD_FILE_PROCESS_ERROR";
   /** APPAPI_DOWNLOAD_FILE_OZR_ERROR */ 
  public static final String E4024803_APPAPI_DOWNLOAD_FILE_OZR_ERROR = "4024803_APPAPI_DOWNLOAD_FILE_OZR_ERROR";

   // API JPM SVC BOARD REST (4900-4999)
   /** APPAPI_JPM_SVC_BOARD_LIST_ERROR */ 
  public static final String E4024901_APPAPI_JPM_SVC_BOARD_LIST_ERROR = "4024901_APPAPI_JPM_SVC_BOARD_LIST_ERROR";
   /** APPAPI_JPM_SVC_BOARD_IMAGE_FORM_ERROR */ 
  public static final String E4024902_APPAPI_JPM_SVC_BOARD_IMAGE_FORM_ERROR = "4024902_APPAPI_JPM_SVC_BOARD_IMAGE_FORM_ERROR";

   // API APP NOTIFICATION (5000-5999)
   /** APPAPI_NOTIFICATION_NOT_FOUND_BY_ID_ERROR */ 
  public static final String E4025001_APPAPI_NOTIFICATION_NOT_FOUND_BY_ID_ERROR = "4025001_APPAPI_NOTIFICATION_NOT_FOUND_BY_ID_ERROR";
   /** APPAPI_NOTIFICATION_NOT_FOUND_BY_USER_ID_ERROR */ 
  public static final String E4025002_APPAPI_NOTIFICATION_NOT_FOUND_BY_USER_ID_ERROR = "4025002_APPAPI_NOTIFICATION_NOT_FOUND_BY_USER_ID_ERROR";
   /** APPAPI_NOTIFICATION_DELETE_BY_ID_ERROR */ 
  public static final String E4025003_APPAPI_NOTIFICATION_DELETE_BY_ID_ERROR = "4025003_APPAPI_NOTIFICATION_DELETE_BY_ID_ERROR";
   /** APPAPI_NOTIFICATION_DELETE_BY_USER_ID_ERROR */ 
  public static final String E4025004_APPAPI_NOTIFICATION_DELETE_BY_USER_ID_ERROR = "4025004_APPAPI_NOTIFICATION_DELETE_BY_USER_ID_ERROR";
   /** APPAPI_NOTIFICATION_GET_INFO_BY_ID_ERROR */ 
  public static final String E4025005_APPAPI_NOTIFICATION_GET_INFO_BY_ID_ERROR = "4025005_APPAPI_NOTIFICATION_GET_INFO_BY_ID_ERROR";
   /** APPAPI_NOTIFICATION_GET_INFO_BY_USER_ID_ERROR */ 
  public static final String E4025006_APPAPI_NOTIFICATION_GET_INFO_BY_USER_ID_ERROR = "4025006_APPAPI_NOTIFICATION_GET_INFO_BY_USER_ID_ERROR";
   /** APPAPI_NOTIFICATION_READ_ITEM_ERROR */ 
  public static final String E4025007_APPAPI_NOTIFICATION_READ_ITEM_ERROR = "4025007_APPAPI_NOTIFICATION_READ_ITEM_ERROR";
   /** APPAPI_NOTIFICATION_READ_ALL_ERROR */ 
  public static final String E4025008_APPAPI_NOTIFICATION_READ_ALL_ERROR = "4025008_APPAPI_NOTIFICATION_READ_ALL_ERROR";

   // API ATTACH FILE REST (5100 - 5199)
   /** APPAPI_ATTACH_FILE_UPLOAD_ERROR */ 
  public static final String E4025101_APPAPI_ATTACH_FILE_UPLOAD_ERROR = "4025101_APPAPI_ATTACH_FILE_UPLOAD_ERROR";
   /** APPAPI_ATTACH_FILE_LIST_ERROR */ 
  public static final String E4025102_APPAPI_ATTACH_FILE_LIST_ERROR = "4025102_APPAPI_ATTACH_FILE_LIST_ERROR";
   /** APPAPI_ATTACH_FILE_DELETE_ERROR */ 
  public static final String E4025103_APPAPI_ATTACH_FILE_DELETE_ERROR = "4025103_APPAPI_ATTACH_FILE_DELETE_ERROR";
   /** APPAPI_ATTACH_FILE_DOWNLOAD_ERROR */ 
  public static final String E4025104_APPAPI_ATTACH_FILE_DOWNLOAD_ERROR = "4025104_APPAPI_ATTACH_FILE_DOWNLOAD_ERROR";
   /** APPAPI_ATTACH_FILE_UPDATE_REFERENCE_ID_ERROR */ 
  public static final String E4025105_APPAPI_ATTACH_FILE_UPDATE_REFERENCE_ID_ERROR = "4025105_APPAPI_ATTACH_FILE_UPDATE_REFERENCE_ID_ERROR";
  
  /** APPAPI_COP_LIST_ERROR */ 
  public static final String E402801_APPAPI_COP_LIST_ERROR = "4025160_APPAPI_COP_LIST_ERROR";
  
  /** APPAPI_PRESENTATION_ERROR */ 
  public static final String E402801_APPAPI_PRESENTATION_ERROR = "4025160_APPAPI_PRESENTATION_ERROR";
  
  //API FORGOT PASSWORD - SECURITY QUESTION (6100 - 6199)
  public static final String E4026100_APPAPI_EMAIL_EXISTS_ERROR = "4026100_APPAPI_EMAIL_EXISTS_ERROR";
  public static final String E4026101_APPAPI_PHONE_EXISTS_ERROR = "4026101_APPAPI_PHONE_EXISTS_ERROR";
  public static final String E4026102_APPAPI_EMAIL_PHONE_REQUIRED_ERROR = "4026102_APPAPI_EMAIL_PHONE_REQUIRED_ERROR";
  public static final String E4026103_APPAPI_OTP_TYPE_INVALID_ERROR = "4026103_APPAPI_OTP_TYPE_INVALID_ERROR";
  public static final String E4026104_APPAPI_OTP_INVALID_ERROR = "4026104_APPAPI_OTP_INVALID_ERROR";
  public static final String E4026105_APPAPI_AGENT_CODE_EXISTS_ERROR = "4026105_APPAPI_AGENT_CODE_EXISTS_ERROR";
  public static final String E4026106_APPAPI_AGENT_CODE_DISCIPLINE_ERROR = "4026106_APPAPI_AGENT_CODE_DISCIPLINE_ERROR";
  public static final String E4026107_APPAPI_EMAIL_IS_NOT_CORRECT_ERROR = "4026107_APPAPI_EMAIL_IS_NOT_CORRECT_ERROR";
  public static final String E4026108_APPAPI_AGENT_NOT_INFORCE = "4026108_APPAPI_AGENT_NOT_INFORCE";
  public static final String E4026109_APPAPI_INVALID_NUMBER_OF_SMS = "4026109_APPAPI_INVALID_NUMBER_OF_SMS";
  public static final String E4026110_APPAPI_CAN_NOT_SEND_OTP = "4026110_APPAPI_CAN_NOT_SEND_OTP";
  public static final String E4026111_APPAPI_OTP_IS_NOT_CORRECT_ERROR = "4026110_APPAPI_OTP_IS_NOT_CORRECT_ERROR";
  public static final String E4026112_APPAPI_OTP_IS_EXPIRED_ERROR = "4026112_APPAPI_OTP_IS_EXPIRED_ERROR";
  public static final String E4026113_APPAPI_INCORRECT_OTP = "4026113_APPAPI_INCORRECT_OTP";
  //API FAVORITE (7100 - 7199)
  public static final String E4027100_APPAPI_LINK_EXISTS_ERROR = "4027100_APPAPI_LINK_EXISTS_ERROR";
  public static final String E4027101_APPAPI_ID_EXISTS_ERROR = "4027101_APPAPI_ID_EXISTS_ERROR";
  public static final String E4027102_APPAPI_LESS_THAN_NUMBER_RECORD = "4027102_APPAPI_LESS_THAN_NUMBER_RECORD";
  public static final String E4027103_APPAPI_ACCOUNT_OLD_PASSWORD_ERROR = "4027103_APPAPI_ACCOUNT_OLD_PASSWORD_ERROR";

  public static final String E9027100_APPAPI_NOT_NUMBER_K2 = "9027100_APPAPI_NOT_NUMBER_K2";
  public static final String E9027101_APPAPI_NOT_NUMBER_K2PLUS = "9027101_APPAPI_NOT_NUMBER_K2PLUS";

  public static final String E9028100_APPAPI_ID_NUMBER_INVALID = "9028100_APPAPI_ID_NUMBER_INVALID";
  
  public static final String E9029100_APPAPI_REJECT_REASON_REQUIRED = "9029100_APPAPI_REJECT_REASON_REQUIRED";
  public static final String E9029101_APPAPI_DETAIL_EMPTY_ERROR = "9029101_APPAPI_DETAIL_EMPTY_ERROR";
  public static final String E9029102_APPAPI_ATTENDANCED_ERROR = "9029102_APPAPI_ATTENDANCED_ERROR";
  public static final String E9029103_APPAPI_APPROVE_EMPTY_ERROR = "9029103_APPAPI_APPROVE_EMPTY_ERROR";
  
}