select 
	AUTH.ID										AS AUTHORITY_ID
    ,AUTH.ROLE_ID           					AS ROLE_ID
    ,ITEM.id                                    AS ITEM_ID
    ,AUHTOR_PIVOT.CAN_ACCESS_FLG                AS CAN_ACCESS_FLG
    ,AUHTOR_PIVOT.CAN_DISP_FLG                  AS CAN_DISP_FLG
    ,AUHTOR_PIVOT.CAN_EDIT_FLG                  AS CAN_EDIT_FLG
    ,ITEM.FUNCTION_TYPE                         AS AUTHORITY_TYPE
    ,ITEM.FUNCTION_NAME                         AS FUNCTION_NAME
    ,ITEM.FUNCTION_CODE                         AS FUNCTION_CODE
    ,ITEM.CREATED_ID							AS CREATED_ID
	,ITEM.CREATED_DATE							AS CREATED_DATE
	,ITEM.UPDATED_ID							AS UPDATED_ID
	,ITEM.UPDATED_DATE							AS UPDATED_DATE
	,ITEM.DELETED_ID							AS DELETED_ID
	,ITEM.DELETED_DATE							AS DELETED_DATE
  FROM  JCA_AUTHORITY AUTH
  LEFT JOIN JCA_ITEM ITEM
    ON ITEM.ID = AUTH.ITEM_ID
  LEFT JOIN VW_AUTHORITY_PIVOT AUHTOR_PIVOT
    ON AUHTOR_PIVOT.ITEM_ID = ITEM.ID
  WHERE
    ITEM.DELETED_ID	IS NULL
    --AND ITEM.DISPLAY_FLAG = '1' 
    AND AUTH.ID = /*authorityId*/