SELECT
    /*searchDto.roleId*/	       				AS ROLE_ID
    , ITEM.id                                   AS ITEM_ID
    , CASE WHEN AUHTOR_PIVOT.CAN_ACCESS_FLG IS NULL THEN 0
    ELSE AUHTOR_PIVOT.CAN_ACCESS_FLG END		AS CAN_ACCESS_FLG
    , CASE WHEN AUHTOR_PIVOT.CAN_DISP_FLG IS NULL THEN 0
    ELSE AUHTOR_PIVOT.CAN_ACCESS_FLG END		AS CAN_DISP_FLG
    , CASE WHEN AUHTOR_PIVOT.CAN_EDIT_FLG IS NULL THEN 0
    ELSE AUHTOR_PIVOT.CAN_ACCESS_FLG END		AS CAN_EDIT_FLG
    , ITEM.FUNCTION_TYPE                        AS AUTHORITY_TYPE
    , ITEM.FUNCTION_NAME                        AS FUNCTION_NAME
    , ITEM.FUNCTION_CODE                        AS FUNCTION_CODE
    , ITEM.CREATED_ID							AS CREATED_ID
	, ITEM.CREATED_DATE							AS CREATED_DATE
	, ITEM.UPDATED_ID							AS UPDATED_ID
	, ITEM.UPDATED_DATE							AS UPDATED_DATE
	, ITEM.DELETED_ID							AS DELETED_ID
	, ITEM.DELETED_DATE							AS DELETED_DATE
FROM
    JCA_ITEM ITEM
LEFT JOIN
  	JPM_PERMISSION_DEPLOY permission_
ON 
	ITEM.FUNCTION_CODE = permission_.DEPLOY_CODE
LEFT JOIN
    VW_AUTHORITY_PIVOT AUHTOR_PIVOT
ON
    AUHTOR_PIVOT.ITEM_ID = ITEM.ID
    AND AUHTOR_PIVOT.ROLE_ID = /*searchDto.roleId*/
WHERE
    ITEM.DELETED_ID	IS NULL
    AND permission_.DELETED_ID IS NULL
    --AND ITEM.DISPLAY_FLAG = '1'
    AND ITEM.FUNCTION_TYPE in /*searchDto.functionTypes*/()
  	AND permission_.PROCESS_DEPLOY_ID = /*searchDto.processDeployId*/
  	/*IF searchDto.companyId != null*/
	AND (ITEM.COMPANY_ID is null or ITEM.COMPANY_ID = /*searchDto.companyId*/1)
	/*END*/
	/*IF searchDto.companyId == null*/
	AND ITEM.COMPANY_ID is null
	/*END*/
		    
	/*IF orders != null*/
	ORDER BY /*$orders*/username
	-- ELSE ORDER BY item.DISPLAY_ORDER ASC
	/*END*/
	
	/*BEGIN*/
	  /*IF offset != null*/
			OFFSET /*offset*/ ROWS FETCH NEXT  /*size*/ ROWS ONLY
	  /*END*/
	/*END*/