SELECT 
    ITEM.id                                    AS ITEM_ID
    ,AUHTOR_PIVOT.CAN_ACCESS_FLG                AS CAN_ACCESS_FLG
    ,AUHTOR_PIVOT.CAN_DISP_FLG                  AS CAN_DISP_FLG
    ,AUHTOR_PIVOT.CAN_EDIT_FLG                  AS CAN_EDIT_FLG
    ,ITEM.FUNCTION_TYPE                         AS AUTHORITY_TYPE
    ,ITEM.FUNCTION_NAME                         AS FUNCTION_NAME
    ,ITEM.FUNCTION_CODE                         AS FUNCTION_CODE
FROM  
 	JCA_AUTHORITY AUTH
LEFT JOIN 
	JCA_ITEM ITEM
ON 
	ITEM.ID = AUTH.ITEM_ID
	AND ITEM.DELETED_ID = 0
	/*IF companyId != null */
	AND ITEM.COMPANY_ID = /*companyId*/
	/*END*/	
LEFT JOIN 
	VW_AUTHORITY_PIVOT AUHTOR_PIVOT
ON 
	AUHTOR_PIVOT.ITEM_ID = ITEM.ID
LEFT JOIN
	JCA_ROLE ROLE
ON
	ROLE.ID = AUTH.ROLE_ID
	AND ROLE.DELETED_ID = 0

WHERE
    ITEM.DELETED_ID	IS NULL
    --AND ITEM.DISPLAY_FLAG = '1' 
    AND AUTH.ROLE_ID = /*roleId*/
    /*IF companyId != null */
	AND ROLE.COMPANY_ID = /*companyId*/
	/*END*/	