SELECT
	attach.ID				AS ATTACH_FILE_ID
	, attach.FILE_NAME		AS FILE_NAME
	, attach.FILE_SIZE		AS FILE_SIZE
	, attach.FILE_TYPE		AS FILE_TYPE
	, attach.CONTENT_TYPE	AS CONTENT_TYPE
	, attach.COMPANY_ID		AS COMPANY_ID
	, attach.REPOSITORY_ID	AS REPOSITORY_ID
	, attach.FILE_PATH		AS FILE_PATH
	, attach.REFERENCE_ID	AS REFERENCE_ID
	, attach.REFERENCE_KEY	AS REFERENCE_KEY
	, attach.ATTACH_TYPE	AS ATTACH_TYPE
FROM
	JCA_ATTACH_FILE attach
WHERE
	attach.DELETED_ID IS NULL
	AND attach.ID =/*id*/
	