SELECT 
	  acc.ID 						as USER_ID
	  ,acc.CODE 					as CODE
	  ,acc.FULLNAME 				as FULL_NAME
	  ,acc.USERNAME 				as USERNAME
	  ,acc.EMAIL 					as EMAIL
	  ,acc.RECEIVED_NOTIFICATION 	as RECEIVED_NOTIFICATION
	  ,acc.RECEIVED_EMAIL 			as RECEIVED_EMAIL
	  ,acc.PHONE 					as PHONE_NUMBER
	  ,acc.GENDER 					as GENDER
	  ,acc.BIRTHDAY 				as BIRTHDAY
	  ,acc.ACTIVED 					as ACTIVED
	  ,acc.ENABLED 					as ENABLED
FROM 
	JCA_ACCOUNT acc
LEFT JOIN 
	JCA_ACCOUNT_TEAM accTeam 
ON 
	acc.ID = accTeam.ACCOUNT_ID 
	AND accTeam.DELETED_DATE IS NULL
WHERE 
acc.DELETED_ID = 0
AND acc.ENABLED = '1'
AND accTeam.TEAM_ID = /*TEAMID*/41