select GROUP_CODE, KIND, CODE, DISPLAY_ORDER, ACTIVED , CONVERT(DATE, CREATED_DATE) AS CREATED_DATE, CREATED_ID
, CONVERT(DATE, UPDATED_DATE) AS UPDATED_DATE, UPDATED_ID
, MAX(CASE WHEN LANG_ID = 1 THEN NAME ELSE NULL END)  AS NAME_EN
, MAX(CASE WHEN LANG_ID = 2 THEN NAME ELSE NULL END)  AS NAME_VI
, MAX(CASE WHEN LANG_ID = 1 THEN LANG_ID ELSE NULL END)  AS LANG_ID_EN
, MAX(CASE WHEN LANG_ID = 2 THEN LANG_ID ELSE NULL END)  AS LANG_ID_VI
, MAX(CASE WHEN LANG_ID = 1 THEN LANG_CODE ELSE NULL END)  AS LANG_ID_EN
, MAX(CASE WHEN LANG_ID = 2 THEN LANG_CODE ELSE NULL END)  AS LANG_ID_VI
, KIND as OLD_KIND
, CODE as OLD_CODE
, GROUP_CODE AS OLD_GROUP_CODE
from JCA_CONSTANT WITH(NOLOCK)
WHERE GROUP_CODE = /*groupCode*/'JCA_ADMIN_CHECKBOX'
group by CODE, KIND, GROUP_CODE, DISPLAY_ORDER, ACTIVED , CONVERT(DATE, CREATED_DATE), CREATED_ID, CONVERT(DATE, UPDATED_DATE), UPDATED_ID