select GROUP_CODE, KIND, CODE, DISPLAY_ORDER, ACTIVED 
, MAX(CASE WHEN LANG_ID = 1 THEN NAME ELSE NULL END)  AS NAME_EN
, MAX(CASE WHEN LANG_ID = 2 THEN NAME ELSE NULL END)  AS NAME_VI
from JCA_CONSTANT WITH(NOLOCK)
WHERE GROUP_CODE = /*groupCode*/''
AND KIND = /*kind*/''
AND CODE = /*code*/''
group by CODE, KIND, GROUP_CODE, DISPLAY_ORDER, ACTIVED 