
WITH T1 AS (
SELECT USER_ID,FUNCTION_CODE,JSON_CONFIG,ID FROM JCA_DATATABLE_CONFIG
WHERE FUNCTION_CODE = /*requestConfig.functionCode*/'' AND USER_ID = /*requestConfig.userId*/0
)

SELECT * FROM T1
UNION ALL
SELECT NULL AS USER_ID,FUNCTION_CODE,JSON_CONFIG, NULL AS ID
FROM JCA_DATATABLE_CONFIG_DEFAULT
WHERE ((SELECT count(*) FROM T1)=0) AND FUNCTION_CODE = /*requestConfig.functionCode*/'' 