SELECT ACC.id                 AS ACCOUNT_ID
		, vw.USERNAME		  AS USER_NAME
		, VW.ROLE_ID		  AS ROLE_ID
		, ACC.EMAIL		      AS EMAIL
FROM VW_AUTHORITY_DETAIL vw
INNER JOIN JCA_ACCOUNT acc
ON ACC.USERNAME = vw.username
WHERE
VW.ACTIVED = 1
AND vw.USERNAME	= /*userName*/'taitm'
AND ROLE_ACTIVED = 1
GROUP BY ACC.id, vw.USERNAME, VW.ROLE_ID, ACC.EMAIL;