SELECT 
	email.ID							AS ID
	,email.NAME							AS NAME
	,email.CODE							AS CODE
	,email.TEMPLATE_CONTENT				AS TEMPLATE_CONTENT
	,email.TEMPLATE_SUBJECT				AS TEMPLATE_SUBJECT
	,email.COMPANY_ID					AS COMPANY_ID
	,com.NAME							AS COMPANY_NAME
	,email.CREATED_DATE					AS CREATED_DATE
	,email.CREATED_ID					AS CREATED_ID
	,acc.USERNAME						AS CREATED_BY
FROM  
	JCA_EMAIL_TEMPLATE email
LEFT JOIN
	JCA_COMPANY com
ON
	com.ID = email.COMPANY_ID
LEFT JOIN
	JCA_ACCOUNT acc
ON
	acc.ID = com.CREATED_ID  	

WHERE
	email.DELETED_ID = 0
	AND email.CODE = /*code*/
	