SELECT 
	email.ID 				AS ID
	, email.TO_STRING		AS TO_STRING
	, email.CC_STRING 		AS CC_STRING
	, email.BCC_STRING		AS BCC_STRING
	, email.SUBJECT			AS SUBJECT
	, email.EMAIL_CONTENT 	AS EMAIL_CONTENT
	, email.SEND_DATE		AS SEND_DATE
	, email.SEND_STATUS 	AS SEND_STATUS
	, email.COMPANY_ID		AS COMPANY_ID
	, email.DEPARTMENT_ID 	AS DEPARTMENT_ID
FROM 
	JCA_EMAIL email
WHERE 
	email.DELETED_ID = 0
	AND email.ID = /*id*/