SELECT	CODE, DISPLAY_ORDER, ACTIVED, CONVERT(DATE, CREATED_DATE) AS CREATED_DATE, CREATED_ID
, CONVERT(DATE, UPDATED_DATE) AS UPDATED_DATE, UPDATED_ID
, MAX(CASE WHEN LANG_ID = 1 THEN NAME ELSE NULL END)  AS NAME_EN
, MAX(CASE WHEN LANG_ID = 2 THEN NAME ELSE NULL END)  AS NAME_VI
, MAX(CASE WHEN LANG_ID = 1 THEN LANG_ID ELSE NULL END)  AS LANG_ID_EN
, MAX(CASE WHEN LANG_ID = 2 THEN LANG_ID ELSE NULL END)  AS LANG_ID_VI
, MAX(CASE WHEN LANG_ID = 1 THEN LANG_CODE ELSE NULL END)  AS LANG_ID_EN
, MAX(CASE WHEN LANG_ID = 2 THEN LANG_CODE ELSE NULL END)  AS LANG_ID_VI
FROM JCA_GROUP_CONSTANT WITH(NOLOCK)
WHERE CODE = /*code*/'JCA_ADMIN_CALENDAR'
GROUP BY CODE, DISPLAY_ORDER, ACTIVED, CONVERT(DATE, CREATED_DATE), CREATED_ID, CONVERT(DATE, UPDATED_DATE), UPDATED_ID