INSERT INTO JCA_GROUP_SYSTEM_SETTING(GROUP_CODE, GROUP_NAME, COMPANY_ID, CREATED_ID, CREATED_DATE)
SELECT source_table.GROUP_CODE, source_table.GROUP_NAME, /*companyId*/1 COMPANY_ID, source_table.CREATED_ID, source_table.CREATED_DATE 
FROM JCA_GROUP_SYSTEM_SETTING source_table
LEFT JOIN JCA_GROUP_SYSTEM_SETTING target_table 
ON target_table.GROUP_CODE = source_table.GROUP_CODE 
AND target_table.COMPANY_ID = /*companyId*/1 
WHERE source_table.COMPANY_ID IS NULL 
