SELECT
	GROUP_SETTING.ID
    ,GROUP_SETTING.GROUP_CODE 								AS GROUP_CODE
    ,GROUP_SETTING.GROUP_NAME								AS GROUP_NAME
    ,GROUP_SETTING.COMPANY_ID								AS COMPANY_ID
    ,GROUP_SETTING.CREATED_DATE                       		AS CREATED_DATE
    ,GROUP_SETTING.CREATED_ID                        		AS CREATED_ID
    ,GROUP_SETTING.UPDATED_DATE                       		AS UPDATED_DATE      
    ,GROUP_SETTING.UPDATED_ID                         		AS UPDATED_ID
    ,GROUP_SETTING.DELETED_DATE                       		AS DELETED_DATE
    ,GROUP_SETTING.DELETED_ID                         		AS DELETED_ID
    
FROM JCA_GROUP_SYSTEM_SETTING GROUP_SETTING
WHERE GROUP_SETTING.DELETED_ID = 0 AND GROUP_SETTING.ID = /*id*/
;