SELECT
	menu.ID 						AS ID
	,menu.CODE						AS CODE
	,menu.DISPLAY_ORDER				AS DISPLAY_ORDER
	,menu.URL						AS URL
	,menu.ITEM_ID					AS ITEM_ID
	,menu.COMPANY_ID				AS COMPANY_ID
	,menu.CLASS_NAME				AS CLASS_NAME
	,menu.MENU_TYPE					AS MENU_TYPE
	,menu.STATUS					AS STATUS
	,menu.ACTIVED					AS ACTIVED
	,menu.GROUP_FLAG				AS GROUP_FLAG
FROM 
	JCA_MENU_DEFAULT menu