SELECT
	tem_lang.NOTI_ID			AS NOTI_ID
	,tem_lang.LANG_ID			AS LANG_ID
	,tem_lang.LANG_CODE			AS LANG_CODE
	,tem_lang.TEMPLATE_TITLE	AS TEMPLATE_TITLE
	,tem_lang.TEMPLATE_CONTENT	AS TEMPLATE_CONTENT
FROM 
	JCA_NOTI_TEMPLATE_LANG tem_lang
WHERE 
	tem_lang.NOTI_ID = /*templateId*/
