SELECT
	tem_lang.NOTI_ID			AS NOTI_ID
	,tem_lang.LANG_ID			AS LANG_ID
	,tem_lang.LANG_CODE			AS LANG_CODE
	,tem_lang.TEMPLATE_TITLE	AS TEMPLATE_TITLE
	,tem_lang.TEMPLATE_CONTENT	AS TEMPLATE_CONTENT
	,tem_lang.CREATED_DATE		AS CREATED_DATE
	,tem_lang.CREATED_ID		AS CREATED_ID
	,tem_lang.UPDATED_DATE		AS UPDATED_DATE
	,tem_lang.UPDATED_ID		AS UPDATED_ID
FROM 
	JCA_NOTI_TEMPLATE_LANG tem_lang
WHERE 
	tem_lang.NOTI_ID = /*templateId*/
	AND tem_lang.LANG_ID = /*langId*/
