SELECT 
	 team.ID 					AS TEAM_ID
	,team.CODE					AS CODE
	,team.NAME					AS NAME
	,team.NAME_ABV				AS NAME_ABV
	,team.DESCRIPTION			AS DESCRIPTION
	,team.CREATED_ID			AS CREATED_ID
	,team.CREATED_DATE			AS CREATED_DATE
	,team.UPDATED_ID			AS UPDATED_ID
	,team.UPDATED_DATE			AS UPDATED_DATE
	,team.DELETED_ID			AS DELETED_ID
	,team.DELETED_DATE			AS DELETED_DATE
	,co.name  					AS COMPANY_NAME
	,co.id  					AS COMPANY_ID
FROM JCA_TEAM team
LEFT JOIN
	JCA_COMPANY co ON team.company_id = co.id and co.DELETED_ID = 0
WHERE 
	team.DELETED_ID = 0
	AND team.id = /*id*/
