SELECT
    ID                  AS ID
    , NAME              AS NAME
    , CODE              AS CODE
    , PACKAGE_IMAGE_URL AS ICON_CLASSES
    , IMAGE_URL         AS IMAGE_URL
    , IMAGE_REPO_ID     AS IMAGE_REPO_ID
    , DISPLAY_ORDER     AS DISPLAY_ORDER
    , VERSION           AS VERSION
FROM
    jca_language
WHERE DELETED_ID = 0
ORDER BY
    DISPLAY_ORDER ASC