/*
 * Created on 2019-03-16 ( Date ISO 2019-03-16 - Time 22:52:42 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package vn.com.unit.ep2p.dto;

import java.math.BigDecimal;

/**
 * 
 *
 * @author hangnkm
 *
 */
public class BudgetDetailDto{

	private Long budgetId;

	private String costCenterCode;

	private String budgetYear;

	private String expenseCatLv1;
	
	private Double latestVersion;
	
	private Integer isActivity;

	private String accountCode;

	private String activityCode;

	private String activityName;
	
	private Integer isAllocated;

	private String responsibleParty;
	
	private BigDecimal originalAmount;
	
	private BigDecimal lockedAmount;

	private BigDecimal ytdAdjustAmount;

	private BigDecimal revisedAmount;

	private BigDecimal ytdPendingAmount;

	private BigDecimal ytdApprovedAmount;
	
	private BigDecimal remainingAmount;

	public Long getBudgetId() {
		return budgetId;
	}

	public String getCostCenterCode() {
		return costCenterCode;
	}

	public String getBudgetYear() {
		return budgetYear;
	}

	public String getExpenseCatLv1() {
		return expenseCatLv1;
	}

	public Integer getIsActivity() {
		return isActivity;
	}

	public String getAccountCode() {
		return accountCode;
	}

	public String getActivityCode() {
		return activityCode;
	}

	public String getActivityName() {
		return activityName;
	}

	public String getResponsibleParty() {
		return responsibleParty;
	}

	public BigDecimal getOriginalAmount() {
		return originalAmount;
	}

	public BigDecimal getLockedAmount() {
		return lockedAmount;
	}

	public BigDecimal getYtdAdjustAmount() {
		return ytdAdjustAmount;
	}

	public BigDecimal getRevisedAmount() {
		return revisedAmount;
	}

	public BigDecimal getYtdPendingAmount() {
		return ytdPendingAmount;
	}

	public BigDecimal getYtdApprovedAmount() {
		return ytdApprovedAmount;
	}

	public BigDecimal getRemainingAmount() {
		return remainingAmount;
	}

	public void setBudgetId(Long budgetId) {
		this.budgetId = budgetId;
	}

	public void setCostCenterCode(String costCenterCode) {
		this.costCenterCode = costCenterCode;
	}

	public void setBudgetYear(String budgetYear) {
		this.budgetYear = budgetYear;
	}

	public void setExpenseCatLv1(String expenseCatLv1) {
		this.expenseCatLv1 = expenseCatLv1;
	}

	public void setIsActivity(Integer isActivity) {
		this.isActivity = isActivity;
	}

	public void setAccountCode(String accountCode) {
		this.accountCode = accountCode;
	}

	public void setActivityCode(String activityCode) {
		this.activityCode = activityCode;
	}

	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}

	public void setResponsibleParty(String responsibleParty) {
		this.responsibleParty = responsibleParty;
	}

	public void setOriginalAmount(BigDecimal originalAmount) {
		this.originalAmount = originalAmount;
	}

	public void setLockedAmount(BigDecimal lockedAmount) {
		this.lockedAmount = lockedAmount;
	}

	public void setYtdAdjustAmount(BigDecimal ytdAdjustAmount) {
		this.ytdAdjustAmount = ytdAdjustAmount;
	}

	public void setRevisedAmount(BigDecimal revisedAmount) {
		this.revisedAmount = revisedAmount;
	}

	public void setYtdPendingAmount(BigDecimal ytdPendingAmount) {
		this.ytdPendingAmount = ytdPendingAmount;
	}

	public void setYtdApprovedAmount(BigDecimal ytdApprovedAmount) {
		this.ytdApprovedAmount = ytdApprovedAmount;
	}

	public void setRemainingAmount(BigDecimal remainingAmount) {
		this.remainingAmount = remainingAmount;
	}

	public Integer getIsAllocated() {
		return isAllocated;
	}

	public void setIsAllocated(Integer isAllocated) {
		this.isAllocated = isAllocated;
	}

	public Double getLatestVersion() {
		return latestVersion;
	}

	public void setLatestVersion(Double latestVersion) {
		this.latestVersion = latestVersion;
	}
	
	
	
	
}
