SELECT DISTINCT
    T.TAX_CODE as TAX_CODE_INB,
    T.BUSINESS_HOUSEHOLDS as BUSINESS_HOUSEHOLDS
FROM   
   STG_DMS.DS_TBL_PAYMENT_MONTH_TVTC_PAYROLL T
WHERE  T.AGT_ID = /*agentCode*/
AND (T.TAX_CODE IS NOT NULL OR T.TAX_CODE <> '') 
AND (T.BUSINESS_HOUSEHOLDS IS NOT NULL OR T.BUSINESS_HOUSEHOLDS <> '');