select distinct T1. AGENT_CODE, T2.AGENT_NAME , T2.AGENT_TYPE 
from STG_DMS.VW_AGENT_BRANCH T1
inner join STG_DMS.DMS_AGENT_DETAIL T2 on T1.AGENT_CODE=T2.AGENT_CODE  
inner join STG_DMS.DMS_AGENT_TYPE T3 on T1.AGENT_TYPE=T3.AGENT_TYPE   
inner join STG_DMS.DMS_HIERARCHY_CONFIG T4 on T1.AGENT_TYPE=T4.AGENT_TYPE  AND   T4.STRUCTURE ='0' AND T4.ORG_TYPE ='UO'
inner join RPT_ODS.F_AGENT_BRANCH T5 on T1.ORG_CODE = T5.ORG_CODE
where T1.ORG_CODE = /*orgCode*/ --MÃ don vi kinh doanh Ở MỤC 3.1  
and T5.AGENT_CODE = /*agentCode*/
AND T2.CHANNEL='AD'  
AND T3.CHANNEL ='AD'  
AND T3. STRUCT_NAME =('PARTNER')  
and T3.GROUP_TYPE ='AGENT';