SELECT
	A.ORG_CODE as OFFICE_CODE, A.OFFICE_NAME,
	(case when NVL(B.EMAIL_SS, '') = '' then NVL(A.EMAIL_CS, '')
		else NVL(B.EMAIL_SS, '') || '; ' || NVL(A.EMAIL_CS, '') end) EMAIL
FROM STG_DMS.DMS_ORGANIZATION A
left join STG_DMS.DMS_AA_GA_OFFICE B
on A.ORG_CODE = B.ORG_CODE
WHERE A.CHANNEL = 'AG'
AND A.ORG_TYPE = 'O'
AND A.INACTIVE = 0