select 
0 as Tree_Level, PARENT_GROUP, CHILD_GROUP, ORG_PARENT_ID, ORG_PARENT_NAME
, PARENT_AGENT_CODE, PARENT_AGENT_TYPE, PARENT_AGENT_NAME, 
	AGENT_CODE, AGENT_TYPE, AGENT_NAME, ORG_PARENT_ID AS ORG_ID, ORG_PARENT_NAME as ORG_NAME
FROM  RPT_ODS.D_ORG_AGENT_LEADER_STRUCTURE A
where A.AGENT_CODE = /*agentCode*/'336103' and A.PARENT_GROUP =  /*agentType*/'BM'
/*IF orgId != null && orgId != ''*/
AND A.ORG_ID = /*orgId*/'NWIDE'
/*END*/
;