SELECT A.AGENT_TYPE
	, A.AGENT_CODE
	, A.AGENT_NAME
	, B.ID_NUMBER
	, (case B.GENDER when 'M' then 'Nam'
    	when 'F' then 'Nữ'
    	else null end) GENDER
	, B.MOBILE_PHONE
	, B.EMAIL_ADDRESS1
	, NVL(C.FULL_ADDRESS, E.FULL_ADDRESS) as FULL_ADDRESS
	, D.TD_CODE TERRITORY
	, D.N_CODE AREA
	, D.R_CODE REGION
	, D.O_CODE OFFICE
	, A.AGENT_TYPE POSITION
	, A.SALES_OFFICE_CODE
	, A.SALES_OFFICE_NAME
FROM STG_DMS.DMS_AGENT_DETAIL A
LEFT JOIN STG_DMS.DMS_CLIENT_DETAIL B
	ON A.CLIENT_CODE = B.CLIENT_CODE
LEFT JOIN STG_DMS.DMS_CLIENT_ADDRESS C
	ON (A.CLIENT_CODE = C.CLIENT_CODE
	and C.ADDRESS_TYPE ='Pref')
LEFT JOIN RPT_ODS.D_CURRENT_ORG_HIERARCHY D
	ON (A.OFFICE_CODE = D.O_CODE)
LEFT JOIN STG_DMS.DMS_CLIENT_ADDRESS E
	ON (A.CLIENT_CODE = E.CLIENT_CODE
	and E.ADDRESS_TYPE ='Res')
WHERE 1=1
and A.AGENT_CODE IN /*agentCodes*/()
and A.CHANNEL = 'AG'