SELECT b.MOBILE_PHONE, b.EMAIL_ADDRESS1, b.EMAIL_ADDRESS2, b.EMAIL_ADDRESS3, a.AGENT_NAME, b.gender
FROM STG_DMS.DMS_AGENT_DETAIL a
join STG_DMS.DMS_CLIENT_DETAIL b on a.CLIENT_CODE = b.CLIENT_CODE
where a.AGENT_CODE = /*agentCode*/