select T1.ADDRESS || ', ' || ZIP3.NAME || ', ' || ZIP2.NAME || ', ' || ZIP1.NAME
from STG_DMS.DMS_ORGANIZATION T1
inner join STG_DMS.DMS_ORG_AGENT_DETAIL T2 on T1.ORG_ID = T2.ORG_ID and T2.ROLE_CODE='Main' and T2.EXPIRED_DATE is null
inner join RPT_ODS.ADP_VW_AGENT_HIERARCHY T3 on T2.AGENT_CODE = T3.AD_CODE
left join STG_ING.ZIPCODE ZIP1 on ZIP1.ZIPCODE = T1.PROVINCE
left join STG_ING.ZIPCODE ZIP2 on ZIP2.ZIPCODE = T1.DISTRICT
left join STG_ING.ZIPCODE ZIP3 on ZIP3.ZIPCODE = T1.WARD
where T3.AGENT_CODE=/*agentCode*/'521881'
FETCH FIRST 1 ROWS ONLY
