SELECT A.AGENT_CODE AS AGENT_CODE,
       A.AGENT_NAME AS AGENT_NAME,
       A.AGENT_TYPE AS POSITION
FROM STG_DMS.DMS_AGENT_DETAIL A
INNER JOIN STG_DMS.DMS_AGENT_TYPE B
ON A.AGENT_TYPE = B.AGENT_TYPE AND B.STATUS = '1'
AND A.CHANNEL = B.CHANNEL
WHERE A.channel = 'AG'
AND A.AGENT_STATUS_CODE = 1