with Agent_branch as (
select t1.agent_code, T1.agent_type,  t2.TYPE_LEVEL_NAME, t2.SUB_STRUCT_NAME
from STG_DMS.DMS_AGENT_DETAIL T1
inner join STG_DMS.DMS_AGENT_TYPE T2 on T1.AGENT_TYPE = T2.AGENT_TYPE
where T1.channel='AG' and t1.agent_status='Inforce' 
and t2.GROUP_TYPE ='AGENT' and  TYPE_LEVEL_NAME = case when SUB_STRUCT_NAME ='DFA' then 'UNIT' else 'BRANCH' end
and CAST(t1.agent_code AS VARCHAR(20)) = /*agentCode*/'116968'
)

SELECT A.AGENT_TYPE
	, A.AGENT_CODE
	, A.AGENT_NAME
	, B.ID_NUMBER
	, (case B.GENDER when 'M' then 'Nam'
    	when 'F' then 'Nữ'
    	else null end) GENDER
	, B.MOBILE_PHONE
	, B.EMAIL_ADDRESS1
	, NVL(C.FULL_ADDRESS, E.FULL_ADDRESS) as FULL_ADDRESS
	, D.TD_CODE TERRITORY
	, D.N_CODE AREA
	, D.R_CODE REGION
	, D.O_CODE OFFICE
	, A.AGENT_TYPE POSITION
	, A.SALES_OFFICE_CODE
	, A.SALES_OFFICE_NAME
FROM STG_DMS.DMS_AGENT_DETAIL A
LEFT JOIN STG_DMS.DMS_CLIENT_DETAIL B
	ON A.CLIENT_CODE = B.CLIENT_CODE
LEFT JOIN STG_DMS.DMS_CLIENT_ADDRESS C
	ON (A.CLIENT_CODE = C.CLIENT_CODE
	and C.ADDRESS_TYPE ='Pref')
LEFT JOIN RPT_ODS.D_CURRENT_ORG_HIERARCHY D
	ON (A.OFFICE_CODE = D.O_CODE)
LEFT JOIN STG_DMS.DMS_CLIENT_ADDRESS E
	ON (A.CLIENT_CODE = E.CLIENT_CODE
	and E.ADDRESS_TYPE ='Res')
WHERE 1=1
and A.AGENT_CODE IN (
	select t2.AGENT_KEY as participants 
	from Agent_branch T1 
	inner join  RPT_ODS.D_CURRENT_AGENT_HIERARCHY T2 on t1.agent_code = T2.LV1_AGENTCODE 
	inner join STG_DMS.DMS_AGENT_TYPE T3 on T2.LV1_AGENTTYPE = T3.AGENT_TYPE and T1.TYPE_LEVEL_NAME =t3.TYPE_LEVEL_NAME
	where T2.LV3_STATUS ='Inforce' and T1.TYPE_LEVEL_NAME ='BRANCH'  and  T3.SUB_STRUCT_NAME ='AGENT' 
	union 
	select AGENT_KEY as participants 
	from Agent_branch T1 
	inner join  RPT_ODS.D_CURRENT_AGENT_HIERARCHY T2 on t1.agent_code = T2.LV2_AGENTCODE
	inner join STG_DMS.DMS_AGENT_TYPE T3 on T2.LV2_AGENTTYPE = T3.AGENT_TYPE and T1.TYPE_LEVEL_NAME =t3.TYPE_LEVEL_NAME
	where T2.LV3_STATUS ='Inforce' and T1.TYPE_LEVEL_NAME ='UNIT'  AND T3.SUB_STRUCT_NAME ='DFA' 
	union 
	select distinct BDOH_CODE as participants 
	from Agent_branch T1 
	inner join  RPT_ODS.D_CURRENT_AGENT_HIERARCHY T2 on t1.agent_code = T2.LV1_AGENTCODE 
	inner join STG_DMS.DMS_AGENT_TYPE T3 on T2.LV1_AGENTTYPE = T3.AGENT_TYPE and T1.TYPE_LEVEL_NAME =t3.TYPE_LEVEL_NAME
	where T1.TYPE_LEVEL_NAME ='BRANCH'  and T3.SUB_STRUCT_NAME ='AGENT' 
	union 
	select distinct BDOH_CODE as participants 
	from Agent_branch T1 
	inner join  RPT_ODS.D_CURRENT_AGENT_HIERARCHY T2 on t1.agent_code = T2.LV2_AGENTCODE 
	inner join STG_DMS.DMS_AGENT_TYPE T3 on T2.LV2_AGENTTYPE = T3.AGENT_TYPE and T1.TYPE_LEVEL_NAME =t3.TYPE_LEVEL_NAME
	where T1.TYPE_LEVEL_NAME ='UNIT' AND T3.SUB_STRUCT_NAME ='DFA'
	union 
	select AGENT_KEY as participants 
	from Agent_branch T1 
	inner join  RPT_ODS.D_CURRENT_AGENT_HIERARCHY T2 on t1.agent_code = T2.GAD_CODE
	where T2.LV3_STATUS ='Inforce'
)
and A.CHANNEL = 'AG'