SELECT  AGENT_TYPE
FROM STG_DMS.DMS_AGENT_MOVEMENT
WHERE CHANNEL = 'AG'
  AND  AGENT_CODE = /*agentCode*/
  AND VARCHAR_FORMAT(EFFECTIVE_DATE, 'YYYYMM') <= /*yyyyMM*/
ORDER BY EFFECTIVE_DATE desc, ID desc
    FETCH FIRST 1 ROWS ONLY

