SELECT T2.USER_NAME
FROM STG_DMS.DMS_AGENT_DETAIL T1
INNER JOIN STG_DS.M_CONFIRM_DECREE T2 ON T1.AGENT_CODE = T2.AGENT_CODE
WHERE T1.AGENT_STATUS = 'Terminate' AND T1.CHANNEL = 'AG' AND T2.IS_DELETE = 0