select
COUNT(DISTINCT CASE WHEN BDTH_CODE = CAO_CODE THEN NULL ELSE BDTH_CODE END) AS COUNT_BDTH_CODE,
COUNT(DISTINCT CASE WHEN BDAH_CODE = BDTH_CODE THEN NULL ELSE BDAH_CODE END) AS COUNT_BDAH_CODE,
COUNT(DISTINCT CASE WHEN BDRH_CODE = BDAH_CODE THEN NULL ELSE BDRH_CODE END) AS COUNT_BDRH_CODE,
COUNT(DISTINCT CASE WHEN BDOH_CODE = BDRH_CODE THEN NULL ELSE BDOH_CODE END) AS COUNT_BDOH_CODE,
COUNT(DISTINCT O_CODE) COUNT_OFFICE_CODE
from RPT_ODS.D_CURRENT_ORG_HIERARCHY T1
inner join STG_DMS.DMS_ORGANIZATION T2 ON T1.O_CODE= T2.ORG_CODE AND  T2.INACTIVE='0'
where locate(/*agentGroupCode*/'NORTH;TH;243084', TREE_PATH) >0