select p.SERVICING_AGENT_KEY as AGENT_CODE, m.LI_NAME, RIGHT((1000000000 + m.POLICY_KEY), 9) as POLICY_KEY
from RPT_ODS.F_POLICY_MATURED_V2 m
inner join RPT_ODS.D_POLICY p
on m.POLICY_KEY = p.POLICY_KEY
where LAST_SURVEY_RESULT = '1'
and W_UPDATE_DATE > CURRENT TIMESTAMP - 30 minutes