 select DISTINCT A.BDOH_CODE AS AGENT_CODE, A.BDOH_NAME AS AGENT_NAME, A.BDOH_AGENTTYPE AS AGENT_TYPE
 , C.EMAIL_ADDRESS1 AS EMAIL, C.EMAIL_ADDRESS2, C.EMAIL_ADDRESS3
 from  RPT_ODS.D_CURRENT_AGENT_HIERARCHY A
 INNER JOIN stg_dms.DMS_AGENT_DETAIL B ON B.AGENT_CODE= A.BDOH_CODE
 inner join   stg_dms.DMS_CLIENT_DETAIL C  on B.CLIENT_CODE = C.CLIENT_CODE
 where O_CODE= /*orgId*/'236053'