SELECT a.AGENT_STATUS_CODE
,a.AGENT_STATUS
,t.TYPE_LEVEL agent_Level
, a.AGENT_TYPE agent_Type
,a.AGENT_NAME
,a.AGENT_CODE
,RPT_ODS.DS_FN_GET_AGENT_GROUP (a.AGENT_CODE ) Agent_Group
, RPT_ODS.DS_FN_IS_GAD ( a.AGENT_CODE ) IS_GAD
, t.GROUP_TYPE
, a.CHANNEL
FROM STG_DMS.DMS_AGENT_DETAIL a
LEFT JOIN STG_DMS.DMS_AGENT_TYPE t ON
       a.AGENT_TYPE = t.AGENT_TYPE
       AND a.CHANNEL = t.CHANNEL
where CAST(a.AGENT_CODE AS VARCHAR)  = /*agentCode*/  
--and a.CHANNEL = 'AG'