select distinct PAY.ORG_CODE  AS ID
, O.NAME
, PAY.ORG_CODE  AS kind
, PAY.ORG_CODE || ' - ' || O.NAME AS TITLE
, PAY.GAD_CODE
, PAY.ORG_CODE
, PAY.SEGMENT_GA
, PAY.BANK_ACCOUNT_NUMBER
, PAY.BANK_ACCOUNT_NAME
, PAY.OFFICE_NAME
, PAY.CUTOFF_DATE
, PAY.PAY_DATE
, PAY.FORWARD_PAID
, PAY.BONUS
, PAY.ALLOWANCE_PRETAX
, PAY.GROSS_MONTH
, PAY.DEDUCT_REQUEST
, PAY.HOLD_AMOUNT
, PAY.PAYMENT_AMOUNT
, PAY.DEBT_Y
, PAY.AMOUNT
, PAY.FLAG_GA
, PAY.TOTAL_DEDUCT
, OFFICE.REPORT_TO_GA
, D.AGENT_NAME as GAD_NAME
/*IF payroll == false*/
FROM STG_DMS.DS_TBL_PAYMENT_MONTH_GA PAY
/*END*/
/*IF payroll == true*/
FROM STG_DMS.DS_TBL_PAYMENT_MONTH_GA_PAYROLL PAY
/*END*/
INNER JOIN STG_DMS.DMS_ORGANIZATION O
ON(PAY.ORG_CODE = O.ORG_CODE)
INNER JOIN STG_DMS.DMS_AA_GA_OFFICE OFFICE
ON(PAY.ORG_CODE = OFFICE.ORG_CODE)
LEFT JOIN STG_DMS.DMS_AGENT_DETAIL D ON D.AGENT_CODE = PAY.GAD_CODE 
where PAY.GAD_CODE = /*agentCode*/'515650'
/*IF orgCode != null && orgCode != ''*/
AND PAY.ORG_CODE = /*orgCode*/'GASTA'
/*END*/
AND VARCHAR_FORMAT (PAY.CUTOFF_DATE, 'YYYYMM') = /*cutoffDate*/'2021-09-30'
;