select
  ca.PROVINCE PROVINCE_CODE,
  zp.NAME PROVINCE_NAME,
  ca.DISTRICT DISTRICT_CODE,
  zd.NAME DISTRICT_NAME,
  ca.WARD WARD_CODE,
  zw.NAME WARD_NAME,
  ca.ADDRESS,
  c.TAX_CODE,
  c.TAX_GROUP
FROM        STG_DMS.DMS_AGENT_DETAIL a
left JOIN STG_DMS.DMS_CLIENT_DETAIL c
  ON a.CLIENT_CODE = c.CLIENT_CODE
LEFT JOIN STG_DMS.DMS_CLIENT_ADDRESS ca
  ON ca.CLIENT_CODE = a.CLIENT_CODE
  and ca.ADDRESS_TYPE = 'Res'
LEFT JOIN STG_ING.ZIPCODE zp
  ON zp.PROVINCE = ca.PROVINCE
  and zp.WARD = 0
  and zp.DISTRICT = 0
LEFT JOIN STG_ING.ZIPCODE zd
  ON zd.DISTRICT = ca.DISTRICT
  and zd.PROVINCE = zp.PROVINCE
  and zd.WARD = 0
LEFT JOIN STG_ING.ZIPCODE zw
  ON zw.WARD = ca.WARD
WHERE a.AGENT_CODE = /*agentCode*/