select 
0 as Tree_Level, PARENT_GROUP, CHILD_GROUP, ORG_PARENT_ID, ORG_PARENT_NAME
, PARENT_AGENT_CODE, PARENT_AGENT_TYPE, PARENT_AGENT_NAME, 
	AGENT_CODE, AGENT_TYPE, AGENT_NAME, A.ORG_ID AS ORG_ID, A.ORG_NAME as ORG_NAME, A.ORG_NAME as ORG_NAME_FIRST
FROM  RPT_ODS.D_ORG_AGENT_LEADER_STRUCTURE A
INNER JOIN STG_DMS.DMS_ORGANIZATION O
ON(O.ORG_CODE = A.ORG_ID)
WHERE NVL(O.INACTIVE, 0) = 0
AND A.AGENT_CODE = /*agentCode*/'243080' and A.CHILD_GROUP =  /*agentGroup*/'CAO'
/*IF orgId != null && orgId != ''*/
AND A.ORG_ID = /*orgId*/'NWIDE'
/*END*/
;