SELECT CASE WHEN C.POLICY_TYPE = 'ACTIVE' THEN '5' ELSE '6' END AS TYPE
, SUM(C.TOTAL_POLICY) AS TOTAL_PROPOSAL
FROM Table( RPT_ODS.DS_FN_LIST_POLICY_BY_LEADER_SUM_ACTIVE_CANCEL( /*agentCode*/'214732',/*agentGroup*/'BM',/*orgCode*/'GANT2')) C
GROUP BY C.POLICY_TYPE

