SELECT CASE WHEN C.POLICY_TYPE = 'ACTIVE' THEN '5' ELSE '6' END AS TYPE
, SUM(C.TOTAL_POLICY) AS TOTAL_PROPOSAL
FROM TABLE( RPT_ODS.DS_FN_LIST_POLICY_BY_LEADER_SUM_ACTIVE_CANCEL ( /*agentCode*/, /*agentGroup*/, /*orgCode*/)) C
GROUP BY POLICY_TYPE;