SELECT 'Support' as ROLE_NAME
FROM STG_DMS.DMS_AGENT_DETAIL
WHERE CHANNEL = 'AG'
AND AGENT_TYPE='EMP'
AND (AGENT_NAME like '%_AT' or AGENT_NAME like '%_SM')
AND CAST(AGENT_CODE AS VARCHAR(20)) = /*agentCode*/'155472'
UNION
SELECT 'Manager' as ROLE_NAME
FROM STG_DMS.DMS_AGENT_TYPE A
INNER JOIN STG_DMS.DMS_AGENT_DETAIL B
	ON B.AGENT_TYPE = A.AGENT_TYPE
WHERE A.CHANNEL='AG'
AND A.GROUP_TYPE ='AGENT'
AND A.TYPE_LEVEL_NAME = (case when SUB_STRUCT_NAME ='DFA' then 'UNIT' else 'BRANCH' end)
AND A.STATUS = 1
AND B.CHANNEL='AG'
AND CAST(B.AGENT_CODE AS VARCHAR(20)) = /*agentCode*/'155472'
UNION
SELECT ROLE_NAME
FROM (SELECT AGENT_CODE, ROLE_NAME, ROW_NUMBER () OVER (PARTITION BY AGENT_CODE ORDER BY IDX) ORDERBY
	FROM(
		SELECT DISTINCT BDTH_CODE AGENT_CODE, 1 IDX, 'BDTH' ROLE_NAME
		FROM RPT_ODS.D_CURRENT_ORG_HIERARCHY
		UNION ALL
		SELECT DISTINCT BDAH_CODE AGENT_CODE, 2 IDX, 'BDAH' ROLE_NAME
		FROM RPT_ODS.D_CURRENT_ORG_HIERARCHY
		UNION ALL
		SELECT DISTINCT BDRH_CODE AGENT_CODE, 3 IDX, 'BDRH' ROLE_NAME
		FROM RPT_ODS.D_CURRENT_ORG_HIERARCHY
		UNION ALL
		SELECT DISTINCT BDOH_CODE AGENT_CODE, 4 IDX, 'BDOH' ROLE_NAME
		FROM RPT_ODS.D_CURRENT_ORG_HIERARCHY))
	WHERE ORDERBY = 1
AND CAST(AGENT_CODE AS VARCHAR(20)) = /*agentCode*/'155472'
UNION 
SELECT 'CAO' as ROLE_NAME
FROM RPT_ODS.D_CURRENT_AGENT_HIERARCHY
WHERE CAO_CODE = /*agentCode*/'155472'
ORDER BY ROLE_NAME desc