select DLVN_LV4_CODE 	AS ZONE_CODE
, DLVN_LV4_NAME			AS ZONE
, DLVN_LV3_CODE			AS REGIONAL_CODE
, DLVN_LV3_NAME			AS REGIONAL
, DLVN_LV2_CODE			AS AREA_CODE
, DLVN_LV2_NAME			AS AREA
, DLVN_LV4_MAN_CODE		AS ZD_CODE
, (case when PNR_LV6_PARTNER_CODE <> 'VNPST' then PNR_LV6_CODE	else PNR_LV5_CODE end)	AS BU_CODE
from RPT_ODS.D_AD_CURRENT_ORG_HIERARCHY
where 1=1
/*IF buCode != null && buCode != ''*/
and (case when PNR_LV6_PARTNER_CODE <> 'VNPST' then PNR_LV6_CODE	else PNR_LV5_CODE end) = /*buCode*/'90900181'
/*END*/