SELECT 
    T.TAX_CODE as TAX_CODE_INB,
    T.BUSINESS_HOUSEHOLDS as BUSINESS_HOUSEHOLDS,
    T.BANK_INB as BANK_ACCOUNT_NUMBER,
    T.BANK_INB_NAME as BANK_ACCOUNT_NAME,
    C.ID as TRAINED_ID,
    A.AGENT_TYPE as AGENT_TYPE,
    A.AGENT_NAME as AGENT_NAME
FROM   
   STG_DMS.DS_TBL_PAYMENT_MONTH_TVTC_PAYROLL T
    INNER JOIN STG_DMS.DMS_AGENT_DETAIL A  
		ON (A.AGENT_CODE = T.AGT_ID AND VARCHAR_FORMAT(T.cutoff_date, 'YYYYMM') = /*cutOffDateYYYYMM*/)
    LEFT JOIN STG_DMS.DMS_AGENT_TRAINED C
    ON (C.AGENT_CODE = T.AGT_ID AND  LENGTH(TRIM(C.OFFICE_CODE)) = 0 AND VARCHAR_FORMAT(C.EFFECTIVE_DATE, 'YYYYMM') = /*cutOffDateYYYYMM*/)
WHERE A.AGENT_CODE = /*agentCode*/;