SELECT
    A.AGENT_CODE AS AGENTCODE, A.AGENT_NAME, B.GENDER
FROM STG_DMS.DMS_AGENT_DETAIL A
         INNER JOIN STG_DMS.DMS_CLIENT_DETAIL B
                    ON A.CLIENT_CODE = B.CLIENT_CODE AND B.GENDER IS NOT NULL
WHERE A.CHANNEL = 'AG'
  AND A.AGENT_STATUS_CODE = '1'
  AND VARCHAR_FORMAT(DOB, 'MMdd') = VARCHAR_FORMAT(CURRENT TIMESTAMP, 'MMdd')
  AND CURRENT TIME < TIME('08:45:00')