WITH OrgList AS (
select distinct PAY.ORG_CODE  AS ID
	, O.NAME
	, PAY.ORG_CODE  AS kind
	, PAY.ORG_CODE || ' - ' || O.NAME AS TITLE
	, PAY.GAD_CODE
	, PAY.ORG_CODE
	, PAY.SEGMENT_GA
	, PAY.BANK_ACCOUNT_NUMBER
	, PAY.BANK_ACCOUNT_NAME
	, PAY.OFFICE_NAME
  , PAY.CUTOFF_DATE
	, ROW_NUMBER() OVER (PARTITION BY PAY.ORG_CODE order by PAY.CUTOFF_DATE desc) as RN
		FROM STG_DMS.DS_TBL_PAYMENT_YEAR_GA PAY
	INNER JOIN STG_DMS.DMS_ORGANIZATION O
		ON(PAY.ORG_CODE = O.ORG_CODE)
	INNER JOIN STG_DMS.DMS_AA_GA_OFFICE OFFICE
		ON(PAY.ORG_CODE = OFFICE.ORG_CODE)
	where PAY.GAD_CODE = /*agentCode*/
		AND VARCHAR_FORMAT (PAY.CUTOFF_DATE, 'YYYY') = /*cutoffDate*/
 
	)
SELECT 
ID
, NAME
, kind
, TITLE
, GAD_CODE
, ORG_CODE
, SEGMENT_GA
, BANK_ACCOUNT_NUMBER
, BANK_ACCOUNT_NAME
, OFFICE_NAME
FROM 
    OrgList
WHERE RN = 1
ORDER BY 
    CUTOFF_DATE DESC;