WITH MonthLatest AS (
    SELECT 
        A.AGENT_CODE, 
        A.AGENT_STATUS, 
        A.AGENT_TYPE, 
        E.CUTOFF_DATE, 
        E.GROSS_Y_INDIRECT,
        B.TAX_CODE,
        ROW_NUMBER() OVER (PARTITION BY A.AGENT_CODE ORDER BY E.CUTOFF_DATE DESC) AS RN
    FROM STG_DMS.DMS_AGENT_DETAIL A
    LEFT JOIN STG_DMS.DMS_CLIENT_DETAIL B ON A.CLIENT_CODE = B.CLIENT_CODE
    LEFT JOIN STG_DMS.DMS_CLIENT_ADDRESS C ON A.CLIENT_CODE = C.CLIENT_CODE
    LEFT JOIN STG_DMS.DMS_AA_GA_OFFICE D ON A.AGENT_CODE = D.GAD_CODE  
    LEFT JOIN STG_DMS.DS_TBL_PAYMENT_YEAR_TVTC E ON A.AGENT_CODE = E.AGENT_CODE
    WHERE A.CHANNEL = 'AG' 
        AND B.TAX_CODE <> '' 
        AND B.TAX_CODE IS NOT NULL 
        AND B.ITRUST_FLAG = 0  
        AND C.MAIN_ADDRESS = 1
        AND (D.INACTIVE = 1 OR D.INACTIVE IS NULL)
		AND A.AGENT_CODE = /*agentCode*/
        AND (E.CUTOFF_DATE >= DATE(SUBSTR(CHAR(CURRENT DATE), 1, 4) || '-01-01')  -- nam hien hanh
        OR  (DATE(SUBSTR(CHAR(CURRENT DATE), 1, 4) || '-01-01') <= CURRENT_DATE
        AND CURRENT_DATE <= DATE(SUBSTR(CHAR(CURRENT DATE), 1, 4) || '-01-31')))
)
SELECT 
    AGENT_CODE, 
    AGENT_STATUS, 
    AGENT_TYPE, 
    CUTOFF_DATE, 
    TAX_CODE,
    GROSS_Y_INDIRECT
FROM 
    MonthLatest
WHERE RN = 1
    AND GROSS_Y_INDIRECT <= 118800000
ORDER BY 
    CUTOFF_DATE DESC;