SELECT 
	A.HDTDL_NO,
	A.AG_CONTRACT_DATE,
	A.HDDV_NO,
	A.SE_CONTRACT_DATE,
	A.COMPANY,
	A.TAX_CODE_ORG,
	B.ADDRESS,
	C.ID as TRAINED_ID
FROM STG_DMS.DS_TBL_PAYMENT_MONTH_GA_PAYROLL A
INNER JOIN STG_DMS.DMS_ORGANIZATION B
ON A.ORG_CODE = B.ORG_CODE
LEFT JOIN STG_DMS.DMS_AGENT_TRAINED C
ON A.GAD_CODE = C.AGENT_CODE
AND C.OFFICE_CODE IN (
  SELECT ORG_CODE
  FROM STG_DMS.DMS_AA_GA_OFFICE
  WHERE REPORT_TO_GA = /*officeCode*/
  OR ORG_CODE= /*officeCode*/
)
AND VARCHAR_FORMAT(C.EFFECTIVE_DATE, 'yyyyMM') = /*period*/
WHERE A.GAD_CODE = /*agentCode*/
AND A.ORG_CODE = /*officeCode*/
AND VARCHAR_FORMAT(A.CUTOFF_DATE, 'yyyyMM') = /*period*/;