SELECT  
	T1.PARTNER_CODE AS PARTNER ---Doi tac
	,T7.CODE AS AREA_CODE ---Khu vuc code
	,T7.NAME AS AREA ---Khu vuc Name
	,T6.CODE AS REGIONAL_CODE---Vung code
	,T6.NAME AS REGIONAL---Vung Name
	,T5.CODE AS ZONE_CODE---Cum code
	,T5.NAME AS ZONE---Cum Name
	,T4.CODE AS BU_CODE---BU code
	,T4.NAME AS BU ---BU name
FROM STG_DMS.DMS_ORG_AGENT_DETAIL T1
	INNER JOIN STG_DMS.DMS_AGENT_DETAIL T2 ON T1.Agent_code = T2.Agent_code
	INNER JOIN STG_DMS.DMS_ORGANIZATION_STRUCTURE T3  ON T1.ORG_ID = T3.ORG_ID --BU 
	INNER JOIN STG_DMS.DMS_ORGANIZATION T4  ON T3.ORG_ID = T4.ORG_ID -- BU (code & name)
	INNER JOIN STG_DMS.DMS_ORGANIZATION T5  ON T4.ORG_MAPPING_ID = T5.ORG_ID AND T5.ORG_TYPE ='AR' --Cum (code & name)
	INNER JOIN STG_DMS.DMS_ORGANIZATION T6  ON T5.ORG_PARENT = T6.ORG_ID  AND T6.ORG_TYPE ='TE'--Vung (code & name)
	INNER JOIN STG_DMS.DMS_ORGANIZATION T7  ON T6.ORG_PARENT = T7.ORG_ID AND T7.ORG_TYPE ='NW' --Khu vuc (code & name)
	WHERE NVL(T1.EXPIRED_DATE, '9999-12-31') between CURRENT DATE and '9999-12-31'---dang con hieu luc
	AND T1.Channel ='AD' --chi lay kenh AD
	AND T2.AGENT_STATUS='Active' --dang con active
	AND T3.STRUCTURE =1 ---chi lay cau truc DLVN 
	AND T1.agent_code =/*agentCode*/'279731'
--getOrgLocationByAgent
