SELECT  
	T6.PARTNER_CODE AS PARTNER ---Doi tac
	,T5.CODE AS AREA_CODE ---Khu vuc code
	,T5.NAME AS AREA ---Khu vuc Name
	,T4.CODE AS REGIONAL_CODE ---Vung code
	,T4.NAME AS REGIONAL ---Vung Name
	,T3.CODE AS ZONE_CODE ---Cum code
	,T3.NAME AS ZONE ---Cum Name
	,T6.CODE AS BU_CODE ---BU code
	,T6.NAME AS BU ---BU name
FROM STG_DMS.DMS_AGENT_DETAIL T1
	INNER JOIN STG_DMS.DMS_ORG_AGENT_DETAIL T2  ON T1.Agent_code = T2.Agent_code  --AR 
	INNER JOIN STG_DMS.DMS_ORGANIZATION T3  ON T2.ORG_ID = T3.ORG_ID  AND T3.ORG_TYPE ='AR'--AR Name
	INNER JOIN STG_DMS.DMS_ORGANIZATION T4  ON T3.ORG_PARENT = T4.ORG_ID  AND T4.ORG_TYPE ='TE'--Vung (code & name)
	INNER JOIN STG_DMS.DMS_ORGANIZATION T5  ON T4.ORG_PARENT = T5.ORG_ID AND T5.ORG_TYPE ='NW' --Khu vuc (code & name)
	INNER JOIN STG_DMS.DMS_ORGANIZATION T6  ON T2.ORG_ID = T6.ORG_MAPPING_ID AND T6.ORG_TYPE ='UO'  -- BU (code & name)
WHERE T1.Channel ='AD' --chi lay kenh AD
	AND T1.AGENT_STATUS='Active' --dang con active
	AND NVL(T2.EXPIRED_DATE, '9999-12-31') between CURRENT DATE and '9999-12-31'---dang con hieu luc
	AND T1.agent_code =/*agentCode*/'506448' --ZD
ORDER BY T6.PARTNER_CODE---Doi tac