select distinct NVL(BDOH_CODE, NVL(BDRH_CODE, NVL(BDAH_CODE, NVL(BDTH_CODE, null)))) as AGENT_CODE,
  NVL(BDOH_NAME, NVL(BDRH_NAME, NVL(BDAH_NAME, NVL(BDTH_NAME, null)))) as AGENT_NAME
from RPT_ODS.D_CURRENT_AGENT_HIERARCHY
where OFFICE_CODE = /*officeCode*/'GDTHX'
